import Isotope.Basic
import Isotope.CategoryTheory.Freyd
import Isotope.CategoryTheory.Monad
import Isotope.CategoryTheory.Premonoidal
import Isotope.Elgot.Basic
import Isotope.Elgot.Nondet
import Isotope.LambdaIter
import Isotope.LambdaSSA
import Isotope.LambdaCase
import Isotope.LambdaSeq
