import Isotope.LambdaIter.Signature
import Isotope.LambdaIter.Subtyping

/-!
# The empty base-type set and the empty instruction set

`lambda_{iter, seq, case}` are parameterized by a type universe `τ` and an
instruction set `Φ`.  This file makes the *smallest* choice of both
first-class: no base types and no instructions.  Everything the three calculi
ask of a signature — `TypeFormers`, `Subtyping`, `HasTy`, `HasEff`, `Bot` — is
supplied here once, and the three calculi share it verbatim, since they share
`Ty`, `Subty` and `BoundCtx`.

The point is *not* that the resulting calculus is empty.  `EmptyTy` is the
universe freely generated by `1`, `0`, `⊗` and `⊕` alone; it is infinite
(`Ty.instInfiniteEmptyTy`), it contains the booleans `1 ⊕ 1` and every finite
type, and the terms over it are exactly the ones definable with no primitives
whatsoever.  What is absent is *base* types, not types.

## Effects

`EmptyEff := PUnit` is the one-element pointed effect set: the initial object
among pointed effect sets, so that the empty signature is initial among
signatures.  This is a deliberate correction of the ad-hoc empty model in
`Subtyping/Semantics/Models/Null.lean`, whose effect set `Eff` has *two*
elements; a `⊥`-preserving map out of a two-element pointed set is not unique,
so `Eff` is not initial.  `Null` remains a perfectly good named example of the
empty base/instruction sets at a *larger* effect set, and is re-derived from
this file.
-/

universe u v

namespace Isotope.LambdaIter

/-- The empty base-type set: no base types at all. -/
abbrev EmptyBase : Type u := PEmpty.{u + 1}

/-- The type universe over no base types: the simple types freely generated by
`1`, `0`, `⊗` and `⊕`.  This carries `TypeFormers` and `Subtyping` from the
generic `Ty` instances, so nothing calculus-specific is needed. -/
abbrev EmptyTy : Type u := Ty EmptyBase.{u}

/-- The empty instruction set: no primitive instructions at all. -/
abbrev EmptyInstr : Type u := PEmpty.{u + 1}

/-- The one-element pointed effect set, initial among pointed effect sets. -/
abbrev EmptyEff : Type u := PUnit.{u + 1}

/-- The empty instruction set is typed over the empty type universe, vacuously.

Tautological by construction: there is nothing to type, so the assignment is
`PEmpty.elim`.  It is recorded as an instance so that the generic typing
judgments of all three calculi elaborate at the empty signature. -/
instance instHasTyEmpty : HasTy EmptyInstr.{u} EmptyTy.{u} where
  src := PEmpty.elim
  trg := PEmpty.elim

/-- The empty instruction set carries effects, vacuously. -/
instance instHasEffEmpty : HasEff EmptyInstr.{u} EmptyEff.{u} where
  eff := PEmpty.elim

/-- The unique element of `EmptyEff` is its bottom. -/
instance instBotEmptyEff : Bot EmptyEff.{u} := ⟨PUnit.unit⟩

/-- The empty signature: no base types, no instructions, one effect. -/
instance instSignatureEmpty : Signature EmptyInstr.{u} EmptyTy.{u} EmptyEff.{u} where

@[simp] theorem emptyEff_eq (e : EmptyEff.{u}) : e = (⊥ : EmptyEff.{u}) := rfl

/-- Every instruction of the empty signature is pure — vacuously, since there
are none. -/
theorem emptyInstr_isPure (f : EmptyInstr.{u}) :
    IsPure (⊥ : EmptyEff.{u}) f := f.elim

/-- The empty instruction set is, in fact, empty. -/
instance : IsEmpty EmptyInstr.{u} := inferInstanceAs (IsEmpty PEmpty)

/-- The empty base-type set is, in fact, empty. -/
example : IsEmpty EmptyBase.{u} := inferInstanceAs (IsEmpty PEmpty)

namespace EmptyTy

/-- The booleans of the empty universe: `1 ⊕ 1`.  No base type is needed. -/
abbrev boolTy : EmptyTy.{u} := .coprod .unit .unit

/-- Iterated tensor: `pow A n` is `A` tensored with itself `n` times. -/
def pow (A : EmptyTy.{u}) : Nat → EmptyTy.{u}
  | 0 => .unit
  | n + 1 => .tensor A (pow A n)

@[simp] theorem pow_zero (A : EmptyTy.{u}) : pow A 0 = .unit := rfl

@[simp] theorem pow_succ (A : EmptyTy.{u}) (n : Nat) :
    pow A (n + 1) = .tensor A (pow A n) := rfl

/-- `pow boolTy` is injective: distinct widths give distinct types. -/
theorem pow_boolTy_injective : Function.Injective (pow boolTy.{u}) := by
  intro m n h
  induction m generalizing n with
  | zero => cases n with
    | zero => rfl
    | succ n => exact absurd h (by simp [pow])
  | succ m ih => cases n with
    | zero => exact absurd h (by simp [pow])
    | succ n =>
      simp only [pow_succ, Ty.tensor.injEq, true_and] at h
      exact congrArg Nat.succ (ih h)

/-- **The empty universe is not a trivial universe.**  It has infinitely many
types, namely the powers of `1 ⊕ 1`, even though it has no base types. -/
instance : Infinite EmptyTy.{u} := Infinite.of_injective _ pow_boolTy_injective

end EmptyTy

end Isotope.LambdaIter
