import Isotope.LambdaIter.Signature.Category
import Isotope.LambdaIter.Signature.Examples
import Isotope.LambdaIter.Ty.Lift
import Mathlib.CategoryTheory.Limits.Shapes.IsTerminal

/-!
# The empty signature is initial

The empty signature — no base types, no instructions, one effect — is the
initial object of `Sig`.  The three components of the unique morphism out of
it come from three separate facts, and it is worth keeping them apart, since
only the first is the "freeness" one usually quotes:

* **Types.**  `Ty EmptyBase` is freely generated by the four type formers over
  no base types, so a former-preserving map out of it is determined
  (`Ty.lift_unique`).  There is exactly one map `EmptyBase → T.Ty`, hence
  exactly one former-preserving map `EmptyTy → T.Ty`.
* **Instructions.**  A map out of `PEmpty` exists and is unique by
  `funext` and `PEmpty.elim`.  This *is* a real uniqueness statement, not a
  vacuous one: it says the three coherence fields `instr_src`, `instr_trg`
  and `instr_eff` impose no constraint, so no *choice* is left either.
* **Effects.**  Uniqueness here is **not** automatic from emptiness — there
  are no instructions, so `instr_eff` says nothing about the effect map.  It
  comes from `EmptyEff` being a *singleton* together with the requirement
  `eff_pure`.  This is exactly why the empty signature must use
  `EmptyEff = PUnit` and not a larger effect set: `Sig.ofNull`, whose base and
  instruction sets are also empty but whose effect set has two elements, is
  **not** initial (`Sig.ofNull_not_isInitial` below).

The last point is the only place in this file where a design decision is
load-bearing, and it is recorded as a theorem rather than a comment.
-/

namespace Isotope.LambdaIter

namespace Sig

open CategoryTheory

universe u

/-- The empty signature as an object of `Sig`: no base types, no instructions,
one effect. -/
def empty : Sig.{u} where
  Ty := EmptyTy.{u}
  formers := inferInstance
  Instr := EmptyInstr.{u}
  Eff := EmptyEff.{u}
  pureEff := PUnit.unit
  hasTy := inferInstance
  hasEff := inferInstance

@[simp] theorem empty_Ty : empty.{u}.Ty = EmptyTy.{u} := rfl
@[simp] theorem empty_Instr : empty.{u}.Instr = EmptyInstr.{u} := rfl
@[simp] theorem empty_Eff : empty.{u}.Eff = EmptyEff.{u} := rfl

/-- **Existence.**  The canonical morphism out of the empty signature: types go
by the free extension of the empty map, instructions by `PEmpty.elim`, and the
one effect to the target's pure effect. -/
def fromEmpty (T : Sig.{u}) : empty.{u} ⟶ T where
  ty := Ty.lift PEmpty.elim
  instr := PEmpty.elim
  eff := fun _ => T.pureEff
  ty_tensor _ _ := rfl
  ty_unit := rfl
  ty_coprod _ _ := rfl
  ty_empty := rfl
  instr_src f := f.elim
  instr_trg f := f.elim
  instr_eff f := f.elim
  eff_pure := rfl

@[simp] theorem fromEmpty_ty (T : Sig.{u}) :
    (fromEmpty T).ty = Ty.lift PEmpty.elim := rfl

/-- **Uniqueness of the type component**, i.e. freeness of `EmptyTy`. -/
theorem fromEmpty_ty_unique {T : Sig.{u}} (F : empty.{u} ⟶ T) :
    F.ty = Ty.lift PEmpty.elim :=
  Ty.lift_unique (fun a => a.elim) F.ty_tensor F.ty_unit F.ty_coprod F.ty_empty

/-- **Uniqueness of the instruction component.**  Both maps are out of an
empty type. -/
theorem fromEmpty_instr_unique {T : Sig.{u}} (F : empty.{u} ⟶ T) :
    F.instr = PEmpty.elim := funext fun f => f.elim

/-- **Uniqueness of the effect component.**  This uses `eff_pure` and the fact
that `EmptyEff` is a singleton; emptiness of the instruction set alone would
not suffice. -/
theorem fromEmpty_eff_unique {T : Sig.{u}} (F : empty.{u} ⟶ T) :
    F.eff = fun _ => T.pureEff := funext fun _ => F.eff_pure

/-- **The empty signature is initial**: there is exactly one signature
morphism out of it into any signature. -/
instance uniqueFromEmpty (T : Sig.{u}) : Unique (empty.{u} ⟶ T) where
  default := fromEmpty T
  uniq F :=
    Hom.ext (fromEmpty_ty_unique F) (fromEmpty_instr_unique F)
      (fromEmpty_eff_unique F)

/-- **The empty signature is the initial object of `Sig`.** -/
def isInitialEmpty : Limits.IsInitial empty.{u} := Limits.IsInitial.ofUnique _

instance : Limits.HasInitial Sig.{u} := Limits.hasInitial_of_unique empty.{u}

/-- Any two morphisms out of the empty signature agree. -/
theorem hom_from_empty_eq {T : Sig.{u}} (F G : empty.{u} ⟶ T) : F = G :=
  Subsingleton.elim F G

/-- The empty signature really is *smaller*: emptiness of the base and
instruction sets alone does not make a signature initial.  `Sig.ofNull` has no
base types and no instructions, yet it has two distinct endomorphisms, so it
is not initial. -/
theorem ofNull_not_isInitial : ¬ Nonempty (Limits.IsInitial ofNull) := by
  rintro ⟨h⟩
  exact collapseNullEff_ne_id
    ((h.hom_ext collapseNullEff (𝟙 ofNull)))

/-- The concrete morphism from the empty signature into the null signature. -/
example : empty.{0} ⟶ ofNull := fromEmpty ofNull

/-- The concrete morphism from the empty signature into the bitvector
signature. -/
example : empty.{0} ⟶ ofBitVec := fromEmpty ofBitVec

end Sig

end Isotope.LambdaIter
