import Isotope.Elgot.RA.Monad

/-!
# The memory-access constants

Transcribed from Dvir, Kammar and Lahav (`release-acquire`), §7.2 of the TOPLAS
journal version (§6.3 of the ESOP full version):

```
⟦store ℓ,v⟧  := { κ ⟨μ, μ ⊎ {ℓ:v@[q,t)⟪κ[ℓ↦t]⟫}⟩ κ[ℓ↦t] ◁ () ∈ Trace 1 }★
⟦rmw ℓ,Φ⟧    := ⟦rmwᴿᴼ ℓ,Φ⟧ ∪ ⟦rmwᴿᴹᵂ ℓ,Φ⟧
⟦rmwᴿᴼ ℓ,Φ⟧  := { κ ⟨μ,μ⟩ κ ◁ ν.vl ∈ Trace Val | κ ↣ ν ∈ μ_ℓ, Φ(ν.vl) = ⊥ }★
⟦rmwᴿᴹᵂ ℓ,Φ⟧ := { κ ⟨μ, μ ⊎ {ε}⟩ κ[ℓ↦t] ◁ ν.vl ∈ Trace Val
                | κ ↣ ν ∈ μ_ℓ, ε = ℓ:Φ(ν.vl)@[ν.t, t)⟪κ[ℓ↦t]⟫ }★
```

As the paper says, "requiring the resulting pre-traces to form traces ensures
the constraints on their timestamps and segment hold", so the `IsTrace`
conjunct in each generating set is the paper's own side condition, not an
addition of ours.  Also as in the paper, loading is restricted to messages the
*initial* view already points to (`κ ↣ ν`); the more permissive loads are
recovered by `Rewind`-closure.

Parallel composition `∥∥∥` is **not** formalized; see the honest boundary in
`Isotope/Elgot/RA.lean`.
-/

namespace Isotope.Elgot.RA

variable {Loc Val : Type} [DecidableEq Loc]

/-- `κ[ℓ ↦ t]`. -/
def setView (κ : View Loc) (ℓ : Loc) (t : ℚ) : View Loc := Function.update κ ℓ t

@[simp] theorem setView_self (κ : View Loc) (ℓ : Loc) (t : ℚ) :
    setView κ ℓ t ℓ = t := Function.update_self ..

@[simp] theorem setView_of_ne {κ : View Loc} {ℓ ℓ' : Loc} (t : ℚ) (h : ℓ' ≠ ℓ) :
    setView κ ℓ t ℓ' = κ ℓ' := Function.update_of_ne h ..

theorem le_setView {κ : View Loc} {ℓ : Loc} {t : ℚ} (h : κ ℓ ≤ t) :
    κ ≤ setView κ ℓ t := by
  intro ℓ'
  by_cases hℓ : ℓ' = ℓ
  · subst hℓ; simpa using h
  · simp [setView_of_ne t hℓ]

/-- The message `ℓ:v@[q, t)⟪κ[ℓ↦t]⟫` written by a store or a read-modify-write. -/
def writeMsg (ℓ : Loc) (v : Val) (q t : ℚ) (κ : View Loc) (h : q < t) : Msg Loc Val where
  lc := ℓ
  vl := v
  i := q
  vw := setView κ ℓ t
  lt := by simpa using h

@[simp] theorem writeMsg_lc (ℓ : Loc) (v : Val) (q t : ℚ) (κ : View Loc) (h : q < t) :
    (writeMsg ℓ v q t κ h).lc = ℓ := rfl

@[simp] theorem writeMsg_vl (ℓ : Loc) (v : Val) (q t : ℚ) (κ : View Loc) (h : q < t) :
    (writeMsg ℓ v q t κ h).vl = v := rfl

@[simp] theorem writeMsg_i (ℓ : Loc) (v : Val) (q t : ℚ) (κ : View Loc) (h : q < t) :
    (writeMsg ℓ v q t κ h).i = q := rfl

@[simp] theorem writeMsg_vw (ℓ : Loc) (v : Val) (q t : ℚ) (κ : View Loc) (h : q < t) :
    (writeMsg ℓ v q t κ h).vw = setView κ ℓ t := rfl

@[simp] theorem writeMsg_t (ℓ : Loc) (v : Val) (q t : ℚ) (κ : View Loc) (h : q < t) :
    (writeMsg ℓ v q t κ h).t = t := by simp [Msg.t]

/-- The traces generated by `⟦store ℓ,v⟧`, before closure. -/
def storeGen (ℓ : Loc) (v : Val) : Set (PreTrace Loc Val Unit) :=
  {τ | ∃ (κ : View Loc) (μ : Memory Loc Val) (q t : ℚ) (h : q < t),
    τ = ⟨κ, Chro.single ⟨μ, insert (writeMsg ℓ v q t κ h) μ⟩, setView κ ℓ t, ()⟩ ∧ IsTrace τ}

theorem storeGen_isTrace (ℓ : Loc) (v : Val) :
    IsTraceSet (storeGen (Val := Val) ℓ v) := by
  rintro τ ⟨κ, μ, q, t, h, -, hτ⟩; exact hτ

/-- `⟦store ℓ,v⟧`. -/
def store (ℓ : Loc) (v : Val) : Comp Loc Val Unit :=
  Comp.close (storeGen ℓ v) (storeGen_isTrace ℓ v)

/-- The traces generated by the read-only branch of `⟦rmw ℓ,Φ⟧`. -/
def rmwROGen (ℓ : Loc) (Φ : Val → Option Val) : Set (PreTrace Loc Val Val) :=
  {τ | ∃ (κ : View Loc) (μ : Memory Loc Val) (ν : Msg Loc Val),
    ν ∈ μ ∧ ν.lc = ℓ ∧ PointsTo κ ν ∧ Φ ν.vl = none ∧
    τ = ⟨κ, Chro.single ⟨μ, μ⟩, κ, ν.vl⟩ ∧ IsTrace τ}

/-- The traces generated by the read-modify-write branch of `⟦rmw ℓ,Φ⟧`. -/
def rmwRMWGen (ℓ : Loc) (Φ : Val → Option Val) : Set (PreTrace Loc Val Val) :=
  {τ | ∃ (κ : View Loc) (μ : Memory Loc Val) (ν : Msg Loc Val) (w : Val) (t : ℚ)
      (h : ν.t < t),
    ν ∈ μ ∧ ν.lc = ℓ ∧ PointsTo κ ν ∧ Φ ν.vl = some w ∧
    τ = ⟨κ, Chro.single ⟨μ, insert (writeMsg ℓ w ν.t t κ h) μ⟩, setView κ ℓ t, ν.vl⟩ ∧
    IsTrace τ}

theorem rmwGen_isTrace (ℓ : Loc) (Φ : Val → Option Val) :
    IsTraceSet (rmwROGen ℓ Φ ∪ rmwRMWGen ℓ Φ) := by
  rintro τ (⟨κ, μ, ν, -, -, -, -, -, hτ⟩ | ⟨κ, μ, ν, w, t, h, -, -, -, -, -, hτ⟩) <;> exact hτ

/-- `⟦rmw ℓ,Φ⟧`. -/
def rmw (ℓ : Loc) (Φ : Val → Option Val) : Comp Loc Val Val :=
  Comp.close (rmwROGen ℓ Φ ∪ rmwRMWGen ℓ Φ) (rmwGen_isTrace ℓ Φ)

/-- `⟦load ℓ⟧ := ⟦rmw ℓ, (λ_. ⊥)⟧`: the read-modify-write whose modifier is
everywhere undefined, hence the read-only branch alone. -/
def load (ℓ : Loc) : Comp Loc Val Val := rmw ℓ (fun _ ↦ none)

theorem rmwRMWGen_eq_empty_of_none (ℓ : Loc) :
    rmwRMWGen (Val := Val) ℓ (fun _ ↦ none) = ∅ := by
  ext τ
  simp only [rmwRMWGen, Set.mem_setOf_eq, Set.mem_empty_iff_false, iff_false]
  rintro ⟨κ, μ, ν, w, t, h, -, -, -, hΦ, -⟩
  exact absurd hΦ (by simp)

theorem load_eq (ℓ : Loc) :
    load (Val := Val) ℓ
      = Comp.close (rmwROGen ℓ (fun _ ↦ none)) (fun τ hτ ↦ rmwGen_isTrace ℓ _ τ (Or.inl hτ)) := by
  apply Comp.ext
  simp only [load, rmw, Comp.traces_close, rmwRMWGen_eq_empty_of_none, Set.union_empty]

end Isotope.Elgot.RA
