import Isotope.Elgot.RA.Closure

/-!
# The release/acquire trace monad, uniformly in the rule set

Transcribed from Dvir, Kammar and Lahav (`release-acquire`), §6.3 of the ESOP
full version / §7.2 "Monad structure" of the TOPLAS journal version:

```
T X          := P★(Trace X)
return r     := { κ ⟨μ,μ⟩ κ ◁ r ∈ Trace X | κ ∈ View, μ ∈ Mem }★
P >>= f      := { α ξη ω ◁ s ∈ Trace Y | α ξ κ ◁ r ∈ P, κ ⊑ σ, σ η ω ◁ s ∈ f r }★
```

Everything is parameterized by the rule set `★ = R`, so `Comp cRules` is the
`𝔠`-model and `Comp gcRules` is the paper's **Concrete model** `C` (the ESOP
version's `M`).

## What is proved here, and what is not

* **Both unit laws hold for every `R` with `𝔠 ⊆ R ⊆ 𝔤𝔠`** — in particular for
  the Concrete model.  The paper states that `C` is a monad (Proposition 7.7;
  ESOP Proposition 6.6) **without proof**, and gives no argument for either
  unit law anywhere, for any model: its one piece of supporting argument
  (Example 8.6, journal p.41) covers associativity only.  So
  `Comp.pure_bind` and `Comp.bind_pure` below are **original work, not a port**.

  The proof runs on a single invariant: every trace in the closure of
  `return r` has no local messages (`Closure.Refines.own_empty`), hence every
  one of its transitions is a *stutter* `⟨μ,μ⟩` and its memories form a
  `⊆`-chain.  A pure trace can therefore be grown out of the other operand by a
  `Rewind` and a run of `Stutter`s, or absorbed into it by a run of `Stutter`s
  and a `Forward`.

* **Associativity is proved *in this file* for `R ⊆ 𝔠` only.**  It rests on
  *deferral of closure* at the seam (`bindGen_closure_left`/`right`), which is
  **false for the `𝔤` rules**: `Loosen`, `Expel` and `Condense` replace
  messages in the closing memory of the left operand, so neither
  `ChroStep.c_sub` nor `ChroStep.o_sub` holds and the seam condition
  `τ.ch.c ⊆ υ.ch.o` is not transported backwards along a rewrite.  For the
  Concrete model `𝔤𝔠` the paper's own route is taken instead — Proposition 7.5
  and Rewrite Castling reduce it to the `𝔠` case proved here; see
  `Isotope/Elgot/RA/Generating.lean`, `Isotope/Elgot/RA/Castling.lean` and
  `Isotope/Elgot/RA/Assoc.lean`.
-/

universe u

namespace Isotope.Elgot.RA

variable {Loc Val : Type} {R : RuleSet} {A B C : Type u}

/-! ## Associativity of the seam -/

theorem PreTrace.seam_assoc {τ : PreTrace Loc Val A} {υ : PreTrace Loc Val B}
    {ζ : PreTrace Loc Val C} (h₁ : τ.ch.c ⊆ υ.ch.o) (h₂ : υ.ch.c ⊆ ζ.ch.o) :
    (τ.seam υ h₁).seam ζ (by simpa using h₂)
      = τ.seam (υ.seam ζ h₂) (by simpa using h₁) := by
  simp only [PreTrace.seam, PreTrace.mk.injEq, true_and, and_true]
  exact Chro.append_assoc _ _ _ h₁ h₂

/-! ## Generating sets -/

/-- The traces generated by `return r`, before closure. -/
def pureGen (r : A) : Set (PreTrace Loc Val A) :=
  {τ | ∃ (κ : View Loc) (μ : Memory Loc Val), WellFormed μ ∧ PointsDownInto κ μ ∧
    τ = ⟨κ, Chro.single ⟨μ, μ⟩, κ, r⟩}

theorem pureGen_isTrace (r : A) : IsTraceSet (pureGen (Loc := Loc) (Val := Val) r) := by
  rintro τ ⟨κ, μ, hwf, hpd, rfl⟩
  refine ⟨?_, hpd, le_refl _, hpd, ?_⟩
  · intro T hT
    simp only [Chro.single_toList, List.mem_singleton] at hT
    subst hT
    exact ⟨hwf, hwf, subset_refl _⟩
  · intro ν hν
    simp only [Chro.single_own, Transition.own, Set.diff_self] at hν
    exact absurd hν (by simp)

theorem pureGen_own (r : A) {τ : PreTrace Loc Val A} (h : τ ∈ pureGen r) :
    τ.ch.own = ∅ := by
  obtain ⟨κ, μ, -, -, rfl⟩ := h
  simp [Transition.own]

theorem pureGen_ret (r : A) {τ : PreTrace Loc Val A} (h : τ ∈ pureGen r) : τ.ret = r := by
  obtain ⟨κ, μ, -, -, rfl⟩ := h; rfl

/-- The traces generated by `P >>= f`, before closure. -/
def bindGen (P : Set (PreTrace Loc Val A)) (F : A → Set (PreTrace Loc Val B)) :
    Set (PreTrace Loc Val B) :=
  {π | ∃ (τ : PreTrace Loc Val A) (υ : PreTrace Loc Val B) (h : τ.ch.c ⊆ υ.ch.o),
    τ ∈ P ∧ υ ∈ F τ.ret ∧ τ.fvw ≤ υ.ivw ∧ π = τ.seam υ h}

theorem bindGen_isTrace {P : Set (PreTrace Loc Val A)} {F : A → Set (PreTrace Loc Val B)}
    (hP : IsTraceSet P) (hF : ∀ a, IsTraceSet (F a)) : IsTraceSet (bindGen P F) := by
  rintro π ⟨τ, υ, h, hτ, hυ, hs, rfl⟩
  exact (hP _ hτ).append (hF _ _ hυ) hs h

theorem bindGen_mono {P Q : Set (PreTrace Loc Val A)} {F G : A → Set (PreTrace Loc Val B)}
    (hPQ : P ⊆ Q) (hFG : ∀ a, F a ⊆ G a) : bindGen P F ⊆ bindGen Q G := by
  rintro π ⟨τ, υ, h, hτ, hυ, hs, rfl⟩
  exact ⟨τ, υ, h, hPQ hτ, hFG _ hυ, hs, rfl⟩

@[simp] theorem bindGen_empty (F : A → Set (PreTrace Loc Val B)) :
    bindGen (∅ : Set (PreTrace Loc Val A)) F = ∅ := by
  ext π; simp only [bindGen, Set.mem_setOf_eq, Set.mem_empty_iff_false, iff_false]
  rintro ⟨τ, υ, h, hτ, -⟩
  exact hτ

theorem bindGen_iUnion_left {ι : Sort*} (P : ι → Set (PreTrace Loc Val A))
    (F : A → Set (PreTrace Loc Val B)) :
    bindGen (⋃ i, P i) F = ⋃ i, bindGen (P i) F := by
  ext π
  simp only [bindGen, Set.mem_setOf_eq, Set.mem_iUnion]
  constructor
  · rintro ⟨τ, υ, h, ⟨i, hi⟩, hυ, hs, rfl⟩; exact ⟨i, τ, υ, h, hi, hυ, hs, rfl⟩
  · rintro ⟨i, τ, υ, h, hi, hυ, hs, rfl⟩; exact ⟨τ, υ, h, ⟨i, hi⟩, hυ, hs, rfl⟩

theorem bindGen_iUnion_right {ι : Sort*} (P : Set (PreTrace Loc Val A))
    (F : ι → A → Set (PreTrace Loc Val B)) :
    bindGen P (fun a ↦ ⋃ i, F i a) = ⋃ i, bindGen P (F i) := by
  ext π
  simp only [bindGen, Set.mem_setOf_eq, Set.mem_iUnion]
  constructor
  · rintro ⟨τ, υ, h, hτ, ⟨i, hi⟩, hs, rfl⟩; exact ⟨i, τ, υ, h, hτ, hi, hs, rfl⟩
  · rintro ⟨i, τ, υ, h, hτ, hi, hs, rfl⟩; exact ⟨τ, υ, h, hτ, ⟨i, hi⟩, hs, rfl⟩

/-! ## Rewriting is a congruence for the seam — for the `𝔠` rules only

The three properties used below are: the closing memory only grows
(`ChroStep.c_sub`), the opening memory only shrinks (`ChroStep.o_sub`), and the
rule's list split extends across an append (`ChroStep.appendLeft/Right`).  All
three fail for `𝔤`, which is why the results of this section carry
`R ⊆ cRules`. -/

/-- Rewriting the left operand of a seam. -/
theorem seam_left_step (hR : R ⊆ cRules) {τ₀ τ : PreTrace Loc Val A}
    {υ : PreTrace Loc Val B} (hstep : Step R τ₀ τ) (hτ : IsTrace τ) (hυ : IsTrace υ)
    (h : τ.ch.c ⊆ υ.ch.o) (hs : τ.fvw ≤ υ.ivw) :
    ∃ h₀ : τ₀.ch.c ⊆ υ.ch.o, τ₀.fvw ≤ υ.ivw ∧
      Refines R (τ₀.seam υ h₀) (τ.seam υ h) := by
  cases hstep with
  | chro hx hc =>
      refine ⟨fun _ hy ↦ h (hc.c_sub (hR hx) hy), hs,
        Refines.single ⟨?_, hτ.append hυ hs h⟩⟩
      exact Step.chro hx (hc.appendLeft (hR hx) _ _)
  | forward hx hκ => exact ⟨h, le_trans hκ hs, Refines.refl _⟩
  | rewind hx hα =>
      exact ⟨h, hs, Refines.single ⟨Step.rewind hx hα, hτ.append hυ hs h⟩⟩
  | condense hx => exact absurd (hR hx) (by simp)

theorem seam_left_refines (hR : R ⊆ cRules) {τ₀ τ : PreTrace Loc Val A}
    {υ : PreTrace Loc Val B} (hr : Refines R τ₀ τ) (_hτ : IsTrace τ) (hυ : IsTrace υ)
    (h : τ.ch.c ⊆ υ.ch.o) (hs : τ.fvw ≤ υ.ivw) :
    ∃ h₀ : τ₀.ch.c ⊆ υ.ch.o, τ₀.fvw ≤ υ.ivw ∧
      Refines R (τ₀.seam υ h₀) (τ.seam υ h) := by
  induction hr using Relation.ReflTransGen.head_induction_on with
  | refl => exact ⟨h, hs, Refines.refl _⟩
  | head hstep _ ih =>
      obtain ⟨hc, hsc, hrc⟩ := ih
      obtain ⟨ha, hsa, hra⟩ := seam_left_step hR hstep.1 hstep.2 hυ hc hsc
      exact ⟨ha, hsa, hra.trans hrc⟩

/-- Rewriting the right operand of a seam. -/
theorem seam_right_step (hR : R ⊆ cRules) {τ : PreTrace Loc Val A}
    {υ₀ υ : PreTrace Loc Val B} (hstep : Step R υ₀ υ) (hτ : IsTrace τ) (hυ : IsTrace υ)
    (h : τ.ch.c ⊆ υ.ch.o) (hs : τ.fvw ≤ υ.ivw) :
    ∃ h₀ : τ.ch.c ⊆ υ₀.ch.o, τ.fvw ≤ υ₀.ivw ∧
      Refines R (τ.seam υ₀ h₀) (τ.seam υ h) := by
  cases hstep with
  | chro hx hc =>
      refine ⟨fun _ hy ↦ hc.o_sub (hR hx) (h hy), hs,
        Refines.single ⟨?_, hτ.append hυ hs h⟩⟩
      exact Step.chro hx (hc.appendRight (hR hx) _ _)
  | forward hx hκ =>
      exact ⟨h, hs, Refines.single ⟨Step.forward hx hκ, hτ.append hυ hs h⟩⟩
  | rewind hx hα => exact ⟨h, le_trans hs hα, Refines.refl _⟩
  | condense hx => exact absurd (hR hx) (by simp)

theorem seam_right_refines (hR : R ⊆ cRules) {τ : PreTrace Loc Val A}
    {υ₀ υ : PreTrace Loc Val B} (hr : Refines R υ₀ υ) (hτ : IsTrace τ) (_hυ : IsTrace υ)
    (h : τ.ch.c ⊆ υ.ch.o) (hs : τ.fvw ≤ υ.ivw) :
    ∃ h₀ : τ.ch.c ⊆ υ₀.ch.o, τ.fvw ≤ υ₀.ivw ∧
      Refines R (τ.seam υ₀ h₀) (τ.seam υ h) := by
  induction hr using Relation.ReflTransGen.head_induction_on with
  | refl => exact ⟨h, hs, Refines.refl _⟩
  | head hstep _ ih =>
      obtain ⟨hc, hsc, hrc⟩ := ih
      obtain ⟨ha, hsa, hra⟩ := seam_right_step hR hstep.1 hτ hstep.2 hc hsc
      exact ⟨ha, hsa, hra.trans hrc⟩

/-! ## Deferral of closure, for `R ⊆ 𝔠` -/

theorem bindGen_closure_left (hR : R ⊆ cRules) {P : Set (PreTrace Loc Val A)}
    {F : A → Set (PreTrace Loc Val B)} (hP : IsTraceSet P) (hF : ∀ a, IsTraceSet (F a)) :
    bindGen (closure R P) F ⊆ closure R (bindGen P F) := by
  rintro π ⟨τ, υ, h, ⟨τ₀, hτ₀, hrf⟩, hυ, hs, rfl⟩
  have hτ : IsTrace τ := hrf.isTrace (hP _ hτ₀)
  obtain ⟨h₀, hs₀, hr⟩ := seam_left_refines hR hrf hτ (hF _ _ hυ) h hs
  refine ⟨τ₀.seam υ h₀, ⟨τ₀, υ, h₀, hτ₀, ?_, hs₀, rfl⟩, hr⟩
  rw [hrf.ret_eq]; exact hυ

theorem bindGen_closure_right (hR : R ⊆ cRules) {P : Set (PreTrace Loc Val A)}
    {F : A → Set (PreTrace Loc Val B)} (hP : IsTraceSet P) (hF : ∀ a, IsTraceSet (F a)) :
    bindGen P (fun a ↦ closure R (F a)) ⊆ closure R (bindGen P F) := by
  rintro π ⟨τ, υ, h, hτ, ⟨υ₀, hυ₀, hrf⟩, hs, rfl⟩
  have hυ : IsTrace υ := hrf.isTrace (hF _ _ hυ₀)
  obtain ⟨h₀, hs₀, hr⟩ := seam_right_refines hR hrf (hP _ hτ) hυ h hs
  exact ⟨τ.seam υ₀ h₀, ⟨τ, υ₀, h₀, hτ, hυ₀, hs₀, rfl⟩, hr⟩

theorem closure_bindGen_closure_left (hR : R ⊆ cRules) {P : Set (PreTrace Loc Val A)}
    {F : A → Set (PreTrace Loc Val B)} (hP : IsTraceSet P) (hF : ∀ a, IsTraceSet (F a)) :
    closure R (bindGen (closure R P) F) = closure R (bindGen P F) :=
  Set.Subset.antisymm
    (closure_subset_of_closed (closure_closed R _) (bindGen_closure_left hR hP hF))
    (closure_mono (bindGen_mono subset_closure (fun _ ↦ subset_refl _)))

theorem closure_bindGen_closure_right (hR : R ⊆ cRules) {P : Set (PreTrace Loc Val A)}
    {F : A → Set (PreTrace Loc Val B)} (hP : IsTraceSet P) (hF : ∀ a, IsTraceSet (F a)) :
    closure R (bindGen P (fun a ↦ closure R (F a))) = closure R (bindGen P F) :=
  Set.Subset.antisymm
    (closure_subset_of_closed (closure_closed R _) (bindGen_closure_right hR hP hF))
    (closure_mono (bindGen_mono (subset_refl _) (fun _ ↦ subset_closure)))

/-! ## Associativity of the generating sets -/

theorem bindGen_assoc (P : Set (PreTrace Loc Val A)) (F : A → Set (PreTrace Loc Val B))
    (G : B → Set (PreTrace Loc Val C)) :
    bindGen (bindGen P F) G = bindGen P (fun a ↦ bindGen (F a) G) := by
  ext π
  constructor
  · rintro ⟨ζ, w, h, ⟨τ, υ, h', hτ, hυ, hs', rfl⟩, hw, hs, rfl⟩
    simp only [PreTrace.seam_ch, Chro.append_c, PreTrace.seam_ret, PreTrace.seam_fvw] at h hw hs
    refine ⟨τ, υ.seam w h, by simpa using h', hτ, ⟨υ, w, h, hυ, hw, hs, rfl⟩,
      by simpa using hs', ?_⟩
    exact PreTrace.seam_assoc h' h
  · rintro ⟨τ, ζ, h, hτ, ⟨υ, w, h', hυ, hw, hs', rfl⟩, hs, rfl⟩
    simp only [PreTrace.seam_ch, Chro.append_o, PreTrace.seam_ivw] at h hs
    refine ⟨τ.seam υ h, w, by simpa using h', ⟨τ, υ, h, hτ, hυ, hs, rfl⟩, hw,
      by simpa using hs', ?_⟩
    exact (PreTrace.seam_assoc h h').symm

/-! ## Well-formedness at the ends of a trace -/

theorem IsTrace.wf_o {τ : PreTrace Loc Val A} (h : IsTrace τ) : WellFormed τ.ch.o :=
  (h.wf _ τ.ch.first_mem).opening

theorem IsTrace.wf_c {τ : PreTrace Loc Val A} (h : IsTrace τ) : WellFormed τ.ch.c := by
  obtain ⟨T, hT, hc⟩ := listC_mem τ.ch.toList τ.ch.toList_ne_nil
  change WellFormed (listC τ.ch.toList)
  rw [hc]
  exact (h.wf T hT).closing

/-! ## Traces without local messages are runs of stutters

This is the engine of both unit laws.  A trace with `ξ.own = ∅` has
`ρᵢ ⊆ μᵢ`, and `Transition.WF` has `μᵢ ⊆ ρᵢ`, so every transition is a stutter
`⟨μ,μ⟩`; chronicle adjacency then makes the memories a `⊆`-chain. -/

/-- Every transition of a trace with no local messages is a stutter between
well-formed memories. -/
theorem IsTrace.stutter_of_own_empty {τ : PreTrace Loc Val A} (hτ : IsTrace τ)
    (h : τ.ch.own = ∅) : ∀ T ∈ τ.ch.toList, T.opening = T.closing ∧ WellFormed T.opening := by
  rw [Chro.own_eq_listOwn, listOwn_eq_empty_iff] at h
  intro T hT
  exact ⟨Set.Subset.antisymm (hτ.wf T hT).sub (h T hT), (hτ.wf T hT).opening⟩

/-- Such a trace's opening memory is contained in its closing memory. -/
theorem IsTrace.o_sub_c_of_own_empty {τ : PreTrace Loc Val A} (hτ : IsTrace τ)
    (h : τ.ch.own = ∅) : τ.ch.o ⊆ τ.ch.c :=
  listO_sub_listC τ.ch.toList τ.ch.chain_toList
    (fun T hT ↦ (hτ.stutter_of_own_empty h T hT).1)

/-- …and is contained in every one of its memories. -/
theorem IsTrace.o_sub_mem_of_own_empty {τ : PreTrace Loc Val A} (hτ : IsTrace τ)
    (h : τ.ch.own = ∅) {T : Transition Loc Val} (hT : T ∈ τ.ch.toList) :
    τ.ch.o ⊆ T.opening :=
  listO_sub_of_mem τ.ch.toList τ.ch.chain_toList
    (fun T hT ↦ (hτ.stutter_of_own_empty h T hT).1) T hT

/-- Prefixing a trace by a run of stutter transitions gives a trace. -/
theorem isTrace_stutterPrefix {α : View Loc} {υ : PreTrace Loc Val B} (hυ : IsTrace υ)
    (hα : α ≤ υ.ivw) (L : List (Transition Loc Val)) (ξ : Chro Loc Val)
    (hξ : ξ.toList = L ++ υ.ch.toList)
    (hst : ∀ T ∈ L, T.opening = T.closing ∧ WellFormed T.opening)
    (hpd : PointsDownInto α ξ.o) :
    IsTrace (⟨α, ξ, υ.fvw, υ.ret⟩ : PreTrace Loc Val B) where
  wf := by
    intro T hT
    rw [hξ, List.mem_append] at hT
    rcases hT with hT | hT
    · obtain ⟨he, hw⟩ := hst T hT
      exact ⟨hw, he ▸ hw, he ▸ subset_refl _⟩
    · exact hυ.wf T hT
  openPts := hpd
  mono := le_trans hα hυ.mono
  closePts := by
    change PointsDownInto υ.fvw ξ.c
    rw [Chro.c, hξ, listC_append_of_ne_nil _ _ υ.ch.toList_ne_nil]
    exact hυ.closePts
  own := by
    intro ν hν
    rw [Chro.own_eq_listOwn, hξ, listOwn_append] at hν
    rcases hν with hν | hν
    · rw [listOwn_eq_empty_iff.mpr (fun T hT ↦ (hst T hT).1 ▸ subset_refl _)] at hν
      exact absurd hν (by simp)
    · obtain ⟨h1, h2, h3⟩ := hυ.own ν hν
      exact ⟨le_trans hα h1, h2, lt_of_le_of_lt (hα ν.lc) h3⟩

/-- Growing a run of stutter transitions in front of a trace, one `Stutter` at
a time. -/
theorem stutter_prefix (hSt : Rule.St ∈ R) {α : View Loc} {υ : PreTrace Loc Val B}
    (hυ : IsTrace υ) (hα : α ≤ υ.ivw) :
    ∀ (L : List (Transition Loc Val)) (ξ : Chro Loc Val), ξ.toList = L ++ υ.ch.toList →
      (∀ T ∈ L, T.opening = T.closing ∧ WellFormed T.opening) →
      PointsDownInto α ξ.o →
      Refines R (⟨α, υ.ch, υ.fvw, υ.ret⟩ : PreTrace Loc Val B) ⟨α, ξ, υ.fvw, υ.ret⟩ := by
  intro L
  induction L with
  | nil =>
      intro ξ hξ _ _
      rw [List.nil_append] at hξ
      cases Chro.ext_toList hξ
      exact Refines.refl _
  | cons T L ih =>
      intro ξ hξ hst hpd
      have hne : L ++ υ.ch.toList ≠ [] := by
        simp [List.append_eq_nil_iff, υ.ch.toList_ne_nil]
      have hchain : List.IsChain Adj (L ++ υ.ch.toList) := by
        have := ξ.chain_toList
        rw [hξ, List.cons_append] at this
        exact (List.isChain_cons.mp this).2
      set ξ' : Chro Loc Val := Chro.ofList (L ++ υ.ch.toList) hne hchain with hξ'
      have hξ'l : ξ'.toList = L ++ υ.ch.toList := Chro.ofList_toList _ _ _
      have hTo : T.opening ⊆ ξ'.o := by
        rw [Chro.o, hξ'l]
        have := ξ.chain_toList
        rw [hξ, List.cons_append] at this
        rw [(hst T (by simp)).1]
        exact adj_listO this hne
      have hpd' : PointsDownInto α ξ'.o := by
        have : PointsDownInto α T.opening := by
          have : ξ.o = T.opening := by rw [Chro.o, hξ, List.cons_append, listO_cons]
          rwa [this] at hpd
        exact this.mono hTo
      have hstep : TStep R ⟨α, ξ', υ.fvw, υ.ret⟩ ⟨α, ξ, υ.fvw, υ.ret⟩ := by
        refine ⟨Step.chro hSt (ChroStep.stutter ξ' ξ [] (L ++ υ.ch.toList) T.opening
          (by rw [hξ'l, List.nil_append]) ?_), ?_⟩
        · rw [hξ, List.nil_append, List.cons_append]
          congr 1
          exact Transition.stutter_eq (hst T (by simp)).1
        · exact isTrace_stutterPrefix hυ hα (T :: L) ξ hξ hst hpd
      exact (ih ξ' hξ'l (fun S hS ↦ hst S (by simp [hS])) hpd').tail hstep

/-- Appending a run of stutter transitions to a trace gives a trace. -/
theorem isTrace_stutterSuffix {τ : PreTrace Loc Val A} (hτ : IsTrace τ)
    (L : List (Transition Loc Val)) (ξ : Chro Loc Val)
    (hξ : ξ.toList = τ.ch.toList ++ L)
    (hst : ∀ T ∈ L, T.opening = T.closing ∧ WellFormed T.opening)
    (hcl : ∀ T ∈ L, PointsDownInto τ.fvw T.opening) :
    IsTrace (⟨τ.ivw, ξ, τ.fvw, τ.ret⟩ : PreTrace Loc Val A) where
  wf := by
    intro T hT
    rw [hξ, List.mem_append] at hT
    rcases hT with hT | hT
    · exact hτ.wf T hT
    · obtain ⟨he, hw⟩ := hst T hT
      exact ⟨hw, he ▸ hw, he ▸ subset_refl _⟩
  openPts := by
    change PointsDownInto τ.ivw ξ.o
    rw [Chro.o, hξ, listO_append_of_ne_nil _ _ τ.ch.toList_ne_nil]
    exact hτ.openPts
  mono := hτ.mono
  closePts := by
    change PointsDownInto τ.fvw ξ.c
    rcases List.eq_nil_or_concat' L with rfl | ⟨L', T, rfl⟩
    · rw [Chro.c, hξ, List.append_nil]; exact hτ.closePts
    · have hne : L' ++ [T] ≠ [] := by simp
      obtain ⟨S, hS, hc⟩ := listC_mem (L' ++ [T]) hne
      rw [Chro.c, hξ, listC_append_of_ne_nil _ _ hne, hc, ← (hst S hS).1]
      exact hcl S hS
  own := by
    intro ν hν
    rw [Chro.own_eq_listOwn, hξ, listOwn_append] at hν
    rcases hν with hν | hν
    · exact hτ.own ν hν
    · rw [listOwn_eq_empty_iff.mpr (fun T hT ↦ (hst T hT).1 ▸ subset_refl _)] at hν
      exact absurd hν (by simp)

/-- Growing a run of stutter transitions after a trace, one `Stutter` at a
time. -/
theorem stutter_suffix (hSt : Rule.St ∈ R) {τ : PreTrace Loc Val A} (hτ : IsTrace τ) :
    ∀ (L : List (Transition Loc Val)) (ξ : Chro Loc Val), ξ.toList = τ.ch.toList ++ L →
      (∀ T ∈ L, T.opening = T.closing ∧ WellFormed T.opening) →
      (∀ T ∈ L, PointsDownInto τ.fvw T.opening) →
      Refines R (⟨τ.ivw, τ.ch, τ.fvw, τ.ret⟩ : PreTrace Loc Val A) ⟨τ.ivw, ξ, τ.fvw, τ.ret⟩ := by
  intro L
  induction L using List.reverseRecOn with
  | nil =>
      intro ξ hξ _ _
      rw [List.append_nil] at hξ
      cases Chro.ext_toList hξ
      exact Refines.refl _
  | append_singleton L T ih =>
      intro ξ hξ hst hcl
      have hne : τ.ch.toList ++ L ≠ [] := by
        simp [List.append_eq_nil_iff, τ.ch.toList_ne_nil]
      have hchain : List.IsChain Adj (τ.ch.toList ++ L) := by
        have := ξ.chain_toList
        rw [hξ, ← List.append_assoc] at this
        exact (List.isChain_append.mp this).1
      set ξ' : Chro Loc Val := Chro.ofList (τ.ch.toList ++ L) hne hchain with hξ'
      have hξ'l : ξ'.toList = τ.ch.toList ++ L := Chro.ofList_toList _ _ _
      have hstep : TStep R ⟨τ.ivw, ξ', τ.fvw, τ.ret⟩ ⟨τ.ivw, ξ, τ.fvw, τ.ret⟩ := by
        refine ⟨Step.chro hSt (ChroStep.stutter ξ' ξ (τ.ch.toList ++ L) [] T.opening
          (by rw [hξ'l, List.append_nil]) ?_), ?_⟩
        · rw [hξ, ← List.append_assoc]
          congr 1
          exact congrArg (fun S ↦ [S]) (Transition.stutter_eq (hst T (by simp)).1)
        · exact isTrace_stutterSuffix hτ (L ++ [T]) ξ hξ hst hcl
      exact (ih ξ' hξ'l (fun S hS ↦ hst S (by simp [hS]))
        (fun S hS ↦ hcl S (by simp [hS]))).tail hstep

/-! ## The unit laws

**Original work**: the paper asserts that `C` (and `A`) is a monad
(Propositions 7.7/7.8, ESOP 6.6/6.7) with no proof, and argues neither unit law
for any of its models.  Both hold for every rule set between `𝔠` and `𝔤𝔠`. -/

theorem closure_pureGen_own (hRg : R ⊆ gcRules) (r : A) {τ : PreTrace Loc Val A}
    (h : τ ∈ closure R (pureGen r)) : τ.ch.own = ∅ := by
  obtain ⟨τ₀, hτ₀, hr⟩ := h
  exact hr.own_empty hRg (pureGen_own r hτ₀)

theorem closure_pureGen_ret (r : A) {τ : PreTrace Loc Val A}
    (h : τ ∈ closure R (pureGen r)) : τ.ret = r := by
  obtain ⟨τ₀, hτ₀, hr⟩ := h
  rw [← hr.ret_eq]; exact pureGen_ret r hτ₀

/-- Left neutrality, for every `𝔠 ⊆ R ⊆ 𝔤𝔠`. -/
theorem closure_bindGen_pureGen_left (hcR : cRules ⊆ R) (hRg : R ⊆ gcRules) (r : A)
    (F : A → Set (PreTrace Loc Val B)) (hF : ∀ a, IsTraceSet (F a))
    (hFc : ∀ a, Closed R (F a)) :
    closure R (bindGen (closure R (pureGen r)) F) = F r := by
  apply Set.Subset.antisymm
  · refine closure_subset_of_closed (hFc r) ?_
    rintro π ⟨τ, υ, h, hτ, hυ, hs, rfl⟩
    have hτ' : IsTrace τ := (pureGen_isTrace r).closure _ hτ
    have hown : τ.ch.own = ∅ := closure_pureGen_own hRg r hτ
    have hret : τ.ret = r := closure_pureGen_ret r hτ
    rw [hret] at hυ
    have hυ' : IsTrace υ := hF _ _ hυ
    have hα : τ.ivw ≤ υ.ivw := le_trans hτ'.mono hs
    have hoc : τ.ch.o ⊆ υ.ch.o :=
      subset_trans (hτ'.o_sub_c_of_own_empty hown) h
    have hpd0 : PointsDownInto τ.ivw υ.ch.o := hτ'.openPts.mono hoc
    have hmid : IsTrace (⟨τ.ivw, υ.ch, υ.fvw, υ.ret⟩ : PreTrace Loc Val B) :=
      isTrace_stutterPrefix hυ' hα [] υ.ch (by simp) (by simp) hpd0
    have hstep : TStep R υ ⟨τ.ivw, υ.ch, υ.fvw, υ.ret⟩ :=
      ⟨Step.rewind (hcR (by simp)) hα, hmid⟩
    refine (hFc r).mem_of_refines hυ ((Refines.single hstep).trans ?_)
    exact stutter_prefix (hcR (by simp)) hυ' hα τ.ch.toList (τ.ch.append υ.ch h)
      (by simp) (fun T hT ↦ hτ'.stutter_of_own_empty hown T hT)
      (by simpa using hτ'.openPts)
  · intro υ hυ
    have hυ' : IsTrace υ := hF _ _ hυ
    refine ⟨PreTrace.seam ⟨υ.ivw, Chro.single ⟨υ.ch.o, υ.ch.o⟩, υ.ivw, r⟩ υ (by simp),
      ⟨_, υ, _, subset_closure ⟨υ.ivw, υ.ch.o, hυ'.wf_o, hυ'.openPts, rfl⟩, hυ,
        le_refl _, rfl⟩, ?_⟩
    refine Refines.single ⟨Step.chro (hcR (by simp))
      (ChroStep.mumble _ _ [] υ.ch.rest υ.ch.o υ.ch.o υ.ch.first.closing ?_ ?_), hυ'⟩
    · simp only [Chro.append_toList, Chro.single_toList, List.nil_append,
        List.singleton_append]
      rfl
    · simp only [List.nil_append]
      rfl

/-- Right neutrality, for every `𝔠 ⊆ R ⊆ 𝔤𝔠`. -/
theorem closure_bindGen_pureGen_right (hcR : cRules ⊆ R) (hRg : R ⊆ gcRules)
    (P : Set (PreTrace Loc Val A)) (hP : IsTraceSet P) (hPc : Closed R P) :
    closure R (bindGen P (fun a ↦ closure R (pureGen a))) = P := by
  apply Set.Subset.antisymm
  · refine closure_subset_of_closed hPc ?_
    rintro π ⟨τ, υ, h, hτ, hυ, hs, rfl⟩
    have hτ' : IsTrace τ := hP _ hτ
    have hυ' : IsTrace υ := (pureGen_isTrace τ.ret).closure _ hυ
    have hown : υ.ch.own = ∅ := closure_pureGen_own hRg τ.ret hυ
    have hret : υ.ret = τ.ret := closure_pureGen_ret τ.ret hυ
    have hcl : ∀ T ∈ υ.ch.toList, PointsDownInto τ.fvw T.opening := fun T hT ↦
      hτ'.closePts.mono (subset_trans h (hυ'.o_sub_mem_of_own_empty hown hT))
    have hmid : IsTrace (⟨τ.ivw, τ.ch.append υ.ch h, τ.fvw, τ.ret⟩ : PreTrace Loc Val A) :=
      isTrace_stutterSuffix hτ' υ.ch.toList (τ.ch.append υ.ch h) (by simp)
        (fun T hT ↦ hυ'.stutter_of_own_empty hown T hT) hcl
    have hfw : τ.fvw ≤ υ.fvw := le_trans hs hυ'.mono
    have hstep : TStep R ⟨τ.ivw, τ.ch.append υ.ch h, τ.fvw, τ.ret⟩ (τ.seam υ h) := by
      refine ⟨?_, hτ'.append hυ' hs h⟩
      have : PreTrace.seam τ υ h = ⟨τ.ivw, τ.ch.append υ.ch h, υ.fvw, τ.ret⟩ := by
        rw [PreTrace.seam, hret]
      rw [this]
      exact Step.forward (hcR (by simp)) hfw
    refine hPc.mem_of_refines hτ ((?_ : Refines R τ _).tail hstep)
    exact stutter_suffix (hcR (by simp)) hτ' υ.ch.toList (τ.ch.append υ.ch h) (by simp)
      (fun T hT ↦ hυ'.stutter_of_own_empty hown T hT) hcl
  · intro τ hτ
    have hτ' : IsTrace τ := hP _ hτ
    obtain ⟨l, T, hl, hc⟩ := listC_concat τ.ch.toList τ.ch.toList_ne_nil
    refine ⟨PreTrace.seam τ ⟨τ.fvw, Chro.single ⟨τ.ch.c, τ.ch.c⟩, τ.fvw, τ.ret⟩ (by simp),
      ⟨τ, _, _, hτ, subset_closure ⟨τ.fvw, τ.ch.c, hτ'.wf_c, hτ'.closePts, rfl⟩,
        le_refl _, rfl⟩, ?_⟩
    refine Refines.single ⟨Step.chro (hcR (by simp))
      (ChroStep.mumble _ _ l [] T.opening τ.ch.c τ.ch.c ?_ ?_), hτ'⟩
    · simp only [Chro.append_toList, Chro.single_toList]
      rw [hl]
      simp only [List.append_assoc, List.cons_append, List.nil_append]
      rw [show T = ⟨T.opening, T.closing⟩ from rfl, ← hc]
      rfl
    · rw [hl]
      have hTc : τ.ch.c = T.closing := hc
      rw [hTc]

/-! ## The carrier -/

/-- The release/acquire trace monad at rule set `R`: `R`-closed sets of
`A`-traces.  `Comp cRules` is the `𝔠`-model; `Comp gcRules` is the paper's
Concrete model `C` (journal §7.4, p.34). -/
structure Comp (R : RuleSet) (Loc Val : Type) (A : Type u) where
  /-- The set of traces. -/
  traces : Set (PreTrace Loc Val A)
  /-- Every element is a trace. -/
  isTrace : IsTraceSet traces
  /-- The set is `R`-closed. -/
  closed : Closed R traces

namespace Comp

@[ext] theorem ext {P Q : Comp R Loc Val A} (h : P.traces = Q.traces) : P = Q := by
  cases P; cases Q; cases h; rfl

instance : Membership (PreTrace Loc Val A) (Comp R Loc Val A) where
  mem P τ := τ ∈ P.traces

theorem mem_def {P : Comp R Loc Val A} {τ : PreTrace Loc Val A} :
    τ ∈ P ↔ τ ∈ P.traces := Iff.rfl

/-- Close a set of traces. -/
def close (R : RuleSet) (S : Set (PreTrace Loc Val A)) (hS : IsTraceSet S) :
    Comp R Loc Val A where
  traces := closure R S
  isTrace := hS.closure
  closed := closure_closed R S

@[simp] theorem traces_close (R : RuleSet) (S : Set (PreTrace Loc Val A))
    (hS : IsTraceSet S) : (close R S hS).traces = closure R S := rfl

/-- `return r`. -/
protected def pure (r : A) : Comp R Loc Val A := close R (pureGen r) (pureGen_isTrace r)

/-- `P >>= f`. -/
protected def bind (P : Comp R Loc Val A) (f : A → Comp R Loc Val B) : Comp R Loc Val B :=
  close R (bindGen P.traces (fun a ↦ (f a).traces))
    (bindGen_isTrace P.isTrace (fun a ↦ (f a).isTrace))

instance : _root_.Monad (Comp R Loc Val) where
  pure := Comp.pure
  bind := Comp.bind

@[simp] theorem traces_pure (r : A) :
    (Pure.pure r : Comp R Loc Val A).traces = closure R (pureGen r) := rfl

@[simp] theorem traces_bind (P : Comp R Loc Val A) (f : A → Comp R Loc Val B) :
    (P >>= f).traces = closure R (bindGen P.traces (fun a ↦ (f a).traces)) := rfl

/-- **Left Neutrality** (journal §7.1, p.27).  **Original work**: the paper states that the Concrete
model is a monad (Proposition 7.7; ESOP Proposition 6.6) without proof, and
argues no unit law anywhere. -/
theorem left_neutrality (hcR : cRules ⊆ R) (hRg : R ⊆ gcRules) (r : A)
    (f : A → Comp R Loc Val B) : (Pure.pure r : Comp R Loc Val A) >>= f = f r := by
  apply ext
  rw [traces_bind, traces_pure]
  exact closure_bindGen_pureGen_left hcR hRg r _ (fun a ↦ (f a).isTrace)
    (fun a ↦ (f a).closed)

/-- **Right Neutrality** (journal §7.1, p.27).  **Original work**, as for
`left_neutrality`. -/
theorem right_neutrality (hcR : cRules ⊆ R) (hRg : R ⊆ gcRules) (P : Comp R Loc Val A) :
    P >>= Pure.pure = P := by
  apply ext
  rw [traces_bind]
  exact closure_bindGen_pureGen_right hcR hRg P.traces P.isTrace P.closed

/-- **Associativity** (journal §7.1, p.27), for `R ⊆ 𝔠`.  It uses deferral of
closure at the seam, which is false for the `𝔤` rules; for the Concrete model
see `Concrete.associativity` in `Isotope/Elgot/RA/Assoc.lean`. -/
theorem associativity (hR : R ⊆ cRules) (P : Comp R Loc Val A) (f : A → Comp R Loc Val B)
    (g : B → Comp R Loc Val C) : P >>= f >>= g = P >>= fun a ↦ f a >>= g := by
  apply ext
  change closure R (bindGen (closure R (bindGen P.traces (fun a ↦ (f a).traces)))
      (fun b ↦ (g b).traces))
    = closure R (bindGen P.traces
      (fun a ↦ closure R (bindGen (f a).traces (fun b ↦ (g b).traces))))
  rw [closure_bindGen_closure_left hR
      (bindGen_isTrace P.isTrace (fun a ↦ (f a).isTrace)) (fun b ↦ (g b).isTrace),
    closure_bindGen_closure_right hR P.isTrace
      (fun a ↦ bindGen_isTrace (f a).isTrace (fun b ↦ (g b).isTrace)),
    bindGen_assoc]

instance : LawfulMonad (Comp cRules Loc Val) := LawfulMonad.mk'
  (id_map := fun x ↦ right_neutrality (subset_refl _) cRules_subset_gcRules x)
  (pure_bind := fun a f ↦ left_neutrality (subset_refl _) cRules_subset_gcRules a f)
  (bind_assoc := fun x f g ↦ associativity (subset_refl _) x f g)

/-! ## Order, bottom, and unions

`T X` is ordered by inclusion (§7.2), `∅` is `R`-closed, and closedness is a
Horn condition, hence preserved by arbitrary unions.  These are the only
ingredients the iteration operator needs, and they hold at every rule set. -/

instance : PartialOrder (Comp R Loc Val A) where
  le P Q := P.traces ⊆ Q.traces
  le_refl _ := subset_refl _
  le_trans _ _ _ h₁ h₂ := subset_trans h₁ h₂
  le_antisymm _ _ h₁ h₂ := ext (Set.Subset.antisymm h₁ h₂)

theorem le_def {P Q : Comp R Loc Val A} : P ≤ Q ↔ P.traces ⊆ Q.traces := Iff.rfl

instance : OrderBot (Comp R Loc Val A) where
  bot := ⟨∅, fun _ h ↦ absurd h (by simp), closed_empty⟩
  bot_le _ := by intro τ hτ; exact absurd hτ (by simp)

@[simp] theorem traces_bot : (⊥ : Comp R Loc Val A).traces = ∅ := rfl

/-- The union of a family of computations. -/
def iUnion {ι : Sort*} (x : ι → Comp R Loc Val A) : Comp R Loc Val A where
  traces := ⋃ i, (x i).traces
  isTrace := by
    rintro τ hτ
    rw [Set.mem_iUnion] at hτ
    obtain ⟨i, hi⟩ := hτ
    exact (x i).isTrace _ hi
  closed := closed_iUnion (fun i ↦ (x i).closed)

@[simp] theorem traces_iUnion {ι : Sort*} (x : ι → Comp R Loc Val A) :
    (iUnion x).traces = ⋃ i, (x i).traces := rfl

theorem le_iUnion {ι : Sort*} (x : ι → Comp R Loc Val A) (i : ι) : x i ≤ iUnion x := by
  intro τ hτ; rw [traces_iUnion, Set.mem_iUnion]; exact ⟨i, hτ⟩

theorem iUnion_le {ι : Sort*} {x : ι → Comp R Loc Val A} {P : Comp R Loc Val A}
    (h : ∀ i, x i ≤ P) : iUnion x ≤ P := by
  intro τ hτ
  rw [traces_iUnion, Set.mem_iUnion] at hτ
  obtain ⟨i, hi⟩ := hτ
  exact h i hi

theorem iUnion_const {ι : Sort*} [Nonempty ι] (P : Comp R Loc Val A) :
    iUnion (fun _ : ι ↦ P) = P := by
  apply ext
  rw [traces_iUnion, Set.iUnion_const]

theorem bot_bind (f : A → Comp R Loc Val B) : (⊥ : Comp R Loc Val A) >>= f = ⊥ := by
  apply ext; simp

theorem bind_bot (P : Comp R Loc Val A) : (P >>= fun _ ↦ (⊥ : Comp R Loc Val B)) = ⊥ := by
  apply ext
  rw [traces_bind]
  have h : bindGen P.traces (fun _ ↦ (⊥ : Comp R Loc Val B).traces) = ∅ := by
    ext π
    simp only [traces_bot, Set.mem_empty_iff_false, iff_false]
    rintro ⟨τ, υ, h, -, hυ, -⟩
    exact absurd hυ (by simp)
  rw [h, closure_empty, traces_bot]

theorem bind_mono {P Q : Comp R Loc Val A} {f g : A → Comp R Loc Val B} (h : P ≤ Q)
    (hfg : ∀ a, f a ≤ g a) : P >>= f ≤ Q >>= g := by
  rw [le_def, traces_bind, traces_bind]
  exact closure_mono (bindGen_mono h (fun a ↦ hfg a))

theorem bind_mono_right {P : Comp R Loc Val A} {f g : A → Comp R Loc Val B}
    (hfg : ∀ a, f a ≤ g a) : P >>= f ≤ P >>= g := bind_mono (le_refl P) hfg

theorem iUnion_bind {ι : Sort*} (x : ι → Comp R Loc Val A) (f : A → Comp R Loc Val B) :
    iUnion x >>= f = iUnion (fun i ↦ x i >>= f) := by
  apply ext
  rw [traces_bind, traces_iUnion, traces_iUnion, bindGen_iUnion_left, closure_iUnion]
  rfl

theorem bind_iUnion {ι : Sort*} (P : Comp R Loc Val A) (f : ι → A → Comp R Loc Val B) :
    (P >>= fun a ↦ iUnion (fun i ↦ f i a)) = iUnion (fun i ↦ P >>= f i) := by
  apply ext
  rw [traces_bind, traces_iUnion]
  rw [show (fun a ↦ (iUnion (fun i ↦ f i a)).traces) = (fun a ↦ ⋃ i, (f i a).traces) from rfl]
  rw [bindGen_iUnion_right, closure_iUnion]
  rfl

end Comp

end Isotope.Elgot.RA
