import Isotope.Elgot.RA.Closure

/-!
# The release/acquire trace monad

Transcribed from Dvir, Kammar and Lahav (`release-acquire`), §6.3 of the ESOP
full version / §7.2 "Monad structure" of the TOPLAS journal version:

```
T X          := P★(Trace X)
return r     := { κ ⟨μ,μ⟩ κ ◁ r ∈ Trace X | κ ∈ View, μ ∈ Mem }★
P >>= f      := { α ξη ω ◁ s ∈ Trace Y | α ξ κ ◁ r ∈ P, κ ⊑ σ, σ η ω ◁ s ∈ f r }★
```

with `★ = 𝔠`.  Note that `σ` is redundant: the seam condition is exactly
`κ ⊑ (the initial view of the second trace)`.

The paper states that the `𝔤𝔠`- and `𝔤𝔠𝔞`-monad structures are monads
(Propositions 6.6/6.7, journal 7.7/7.8) **without proof**, and says nothing
about `𝔠` alone.  The `LawfulMonad` instance below is therefore ours, not the
paper's; see the honest boundary in `Isotope/Elgot/RA.lean`.
-/

universe u

namespace Isotope.Elgot.RA

variable {Loc Val : Type} {A B C : Type u}

/-! ## Associativity of the seam -/

theorem PreTrace.seam_assoc {τ : PreTrace Loc Val A} {υ : PreTrace Loc Val B}
    {ζ : PreTrace Loc Val C} (h₁ : τ.ch.c ⊆ υ.ch.o) (h₂ : υ.ch.c ⊆ ζ.ch.o) :
    (τ.seam υ h₁).seam ζ (by simpa using h₂)
      = τ.seam (υ.seam ζ h₂) (by simpa using h₁) := by
  simp only [PreTrace.seam, PreTrace.mk.injEq, true_and, and_true]
  exact Chro.append_assoc _ _ _ h₁ h₂

/-! ## Generating sets -/

/-- The traces generated by `return r`, before closure. -/
def pureGen (r : A) : Set (PreTrace Loc Val A) :=
  {τ | ∃ (κ : View Loc) (μ : Memory Loc Val), WellFormed μ ∧ PointsDownInto κ μ ∧
    τ = ⟨κ, Chro.single ⟨μ, μ⟩, κ, r⟩}

theorem pureGen_isTrace (r : A) : IsTraceSet (pureGen (Loc := Loc) (Val := Val) r) := by
  rintro τ ⟨κ, μ, hwf, hpd, rfl⟩
  refine ⟨?_, hpd, le_refl _, hpd, ?_⟩
  · intro T hT
    simp only [Chro.single_toList, List.mem_singleton] at hT
    subst hT
    exact ⟨hwf, hwf, subset_refl _⟩
  · intro ν hν
    simp only [Chro.single_own, Transition.own, Set.diff_self] at hν
    exact absurd hν (by simp)

/-- The traces generated by `P >>= f`, before closure. -/
def bindGen (P : Set (PreTrace Loc Val A)) (F : A → Set (PreTrace Loc Val B)) :
    Set (PreTrace Loc Val B) :=
  {π | ∃ (τ : PreTrace Loc Val A) (υ : PreTrace Loc Val B) (h : τ.ch.c ⊆ υ.ch.o),
    τ ∈ P ∧ υ ∈ F τ.ret ∧ τ.fvw ≤ υ.ivw ∧ π = τ.seam υ h}

theorem bindGen_isTrace {P : Set (PreTrace Loc Val A)} {F : A → Set (PreTrace Loc Val B)}
    (hP : IsTraceSet P) (hF : ∀ a, IsTraceSet (F a)) : IsTraceSet (bindGen P F) := by
  rintro π ⟨τ, υ, h, hτ, hυ, hs, rfl⟩
  exact (hP _ hτ).append (hF _ _ hυ) hs h

theorem bindGen_mono {P Q : Set (PreTrace Loc Val A)} {F G : A → Set (PreTrace Loc Val B)}
    (hPQ : P ⊆ Q) (hFG : ∀ a, F a ⊆ G a) : bindGen P F ⊆ bindGen Q G := by
  rintro π ⟨τ, υ, h, hτ, hυ, hs, rfl⟩
  exact ⟨τ, υ, h, hPQ hτ, hFG _ hυ, hs, rfl⟩

@[simp] theorem bindGen_empty (F : A → Set (PreTrace Loc Val B)) :
    bindGen (∅ : Set (PreTrace Loc Val A)) F = ∅ := by
  ext π; simp only [bindGen, Set.mem_setOf_eq, Set.mem_empty_iff_false, iff_false]
  rintro ⟨τ, υ, h, hτ, -⟩
  exact hτ

theorem bindGen_iUnion_left {ι : Sort*} (P : ι → Set (PreTrace Loc Val A))
    (F : A → Set (PreTrace Loc Val B)) :
    bindGen (⋃ i, P i) F = ⋃ i, bindGen (P i) F := by
  ext π
  simp only [bindGen, Set.mem_setOf_eq, Set.mem_iUnion]
  constructor
  · rintro ⟨τ, υ, h, ⟨i, hi⟩, hυ, hs, rfl⟩; exact ⟨i, τ, υ, h, hi, hυ, hs, rfl⟩
  · rintro ⟨i, τ, υ, h, hi, hυ, hs, rfl⟩; exact ⟨τ, υ, h, ⟨i, hi⟩, hυ, hs, rfl⟩

theorem bindGen_iUnion_right {ι : Sort*} (P : Set (PreTrace Loc Val A))
    (F : ι → A → Set (PreTrace Loc Val B)) :
    bindGen P (fun a ↦ ⋃ i, F i a) = ⋃ i, bindGen P (F i) := by
  ext π
  simp only [bindGen, Set.mem_setOf_eq, Set.mem_iUnion]
  constructor
  · rintro ⟨τ, υ, h, hτ, ⟨i, hi⟩, hs, rfl⟩; exact ⟨i, τ, υ, h, hτ, hi, hs, rfl⟩
  · rintro ⟨i, τ, υ, h, hτ, hi, hs, rfl⟩; exact ⟨τ, υ, h, hτ, ⟨i, hi⟩, hs, rfl⟩

/-! ## Rewriting is a congruence for the seam -/

/-- Rewriting the left operand of a seam. -/
theorem seam_left_step {τ₀ τ : PreTrace Loc Val A} {υ : PreTrace Loc Val B}
    (hstep : Step τ₀ τ) (hτ : IsTrace τ) (hυ : IsTrace υ)
    (h : τ.ch.c ⊆ υ.ch.o) (hs : τ.fvw ≤ υ.ivw) :
    ∃ h₀ : τ₀.ch.c ⊆ υ.ch.o, τ₀.fvw ≤ υ.ivw ∧
      Refines (τ₀.seam υ h₀) (τ.seam υ h) := by
  cases hstep with
  | chro hc =>
      refine ⟨fun _ hx ↦ h (hc.c_sub hx), hs, Refines.single ⟨?_, hτ.append hυ hs h⟩⟩
      exact Step.chro (hc.appendLeft _ _)
  | forward hκ => exact ⟨h, le_trans hκ hs, Refines.refl _⟩
  | rewind hα =>
      exact ⟨h, hs, Refines.single ⟨Step.rewind hα, hτ.append hυ hs h⟩⟩

theorem seam_left_refines {τ₀ τ : PreTrace Loc Val A} {υ : PreTrace Loc Val B}
    (hr : Refines τ₀ τ) (_hτ : IsTrace τ) (hυ : IsTrace υ)
    (h : τ.ch.c ⊆ υ.ch.o) (hs : τ.fvw ≤ υ.ivw) :
    ∃ h₀ : τ₀.ch.c ⊆ υ.ch.o, τ₀.fvw ≤ υ.ivw ∧
      Refines (τ₀.seam υ h₀) (τ.seam υ h) := by
  induction hr using Relation.ReflTransGen.head_induction_on with
  | refl => exact ⟨h, hs, Refines.refl _⟩
  | head hstep _ ih =>
      obtain ⟨hc, hsc, hrc⟩ := ih
      obtain ⟨ha, hsa, hra⟩ := seam_left_step hstep.1 hstep.2 hυ hc hsc
      exact ⟨ha, hsa, hra.trans hrc⟩

/-- Rewriting the right operand of a seam. -/
theorem seam_right_step {τ : PreTrace Loc Val A} {υ₀ υ : PreTrace Loc Val B}
    (hstep : Step υ₀ υ) (hτ : IsTrace τ) (hυ : IsTrace υ)
    (h : τ.ch.c ⊆ υ.ch.o) (hs : τ.fvw ≤ υ.ivw) :
    ∃ h₀ : τ.ch.c ⊆ υ₀.ch.o, τ.fvw ≤ υ₀.ivw ∧
      Refines (τ.seam υ₀ h₀) (τ.seam υ h) := by
  cases hstep with
  | chro hc =>
      refine ⟨fun _ hx ↦ hc.o_sub (h hx), hs,
        Refines.single ⟨?_, hτ.append hυ hs h⟩⟩
      exact Step.chro (hc.appendRight _ _)
  | forward hκ =>
      exact ⟨h, hs, Refines.single ⟨Step.forward hκ, hτ.append hυ hs h⟩⟩
  | rewind hα => exact ⟨h, le_trans hs hα, Refines.refl _⟩

theorem seam_right_refines {τ : PreTrace Loc Val A} {υ₀ υ : PreTrace Loc Val B}
    (hr : Refines υ₀ υ) (hτ : IsTrace τ) (_hυ : IsTrace υ)
    (h : τ.ch.c ⊆ υ.ch.o) (hs : τ.fvw ≤ υ.ivw) :
    ∃ h₀ : τ.ch.c ⊆ υ₀.ch.o, τ.fvw ≤ υ₀.ivw ∧
      Refines (τ.seam υ₀ h₀) (τ.seam υ h) := by
  induction hr using Relation.ReflTransGen.head_induction_on with
  | refl => exact ⟨h, hs, Refines.refl _⟩
  | head hstep _ ih =>
      obtain ⟨hc, hsc, hrc⟩ := ih
      obtain ⟨ha, hsa, hra⟩ := seam_right_step hstep.1 hτ hstep.2 hc hsc
      exact ⟨ha, hsa, hra.trans hrc⟩

/-! ## Deferral of closure -/

theorem bindGen_closure_left {P : Set (PreTrace Loc Val A)} {F : A → Set (PreTrace Loc Val B)}
    (hP : IsTraceSet P) (hF : ∀ a, IsTraceSet (F a)) :
    bindGen (closure P) F ⊆ closure (bindGen P F) := by
  rintro π ⟨τ, υ, h, ⟨τ₀, hτ₀, hrf⟩, hυ, hs, rfl⟩
  have hτ : IsTrace τ := hrf.isTrace (hP _ hτ₀)
  obtain ⟨h₀, hs₀, hr⟩ := seam_left_refines hrf hτ (hF _ _ hυ) h hs
  refine ⟨τ₀.seam υ h₀, ⟨τ₀, υ, h₀, hτ₀, ?_, hs₀, rfl⟩, hr⟩
  rw [hrf.ret_eq]; exact hυ

theorem bindGen_closure_right {P : Set (PreTrace Loc Val A)} {F : A → Set (PreTrace Loc Val B)}
    (hP : IsTraceSet P) (hF : ∀ a, IsTraceSet (F a)) :
    bindGen P (fun a ↦ closure (F a)) ⊆ closure (bindGen P F) := by
  rintro π ⟨τ, υ, h, hτ, ⟨υ₀, hυ₀, hrf⟩, hs, rfl⟩
  have hυ : IsTrace υ := hrf.isTrace (hF _ _ hυ₀)
  obtain ⟨h₀, hs₀, hr⟩ := seam_right_refines hrf (hP _ hτ) hυ h hs
  exact ⟨τ.seam υ₀ h₀, ⟨τ, υ₀, h₀, hτ, hυ₀, hs₀, rfl⟩, hr⟩

theorem closure_bindGen_closure_left {P : Set (PreTrace Loc Val A)}
    {F : A → Set (PreTrace Loc Val B)} (hP : IsTraceSet P) (hF : ∀ a, IsTraceSet (F a)) :
    closure (bindGen (closure P) F) = closure (bindGen P F) :=
  Set.Subset.antisymm
    (closure_subset_of_closed (closure_closed _) (bindGen_closure_left hP hF))
    (closure_mono (bindGen_mono subset_closure (fun _ ↦ subset_refl _)))

theorem closure_bindGen_closure_right {P : Set (PreTrace Loc Val A)}
    {F : A → Set (PreTrace Loc Val B)} (hP : IsTraceSet P) (hF : ∀ a, IsTraceSet (F a)) :
    closure (bindGen P (fun a ↦ closure (F a))) = closure (bindGen P F) :=
  Set.Subset.antisymm
    (closure_subset_of_closed (closure_closed _) (bindGen_closure_right hP hF))
    (closure_mono (bindGen_mono (subset_refl _) (fun _ ↦ subset_closure)))

/-! ## Associativity -/

theorem bindGen_assoc (P : Set (PreTrace Loc Val A)) (F : A → Set (PreTrace Loc Val B))
    (G : B → Set (PreTrace Loc Val C)) :
    bindGen (bindGen P F) G = bindGen P (fun a ↦ bindGen (F a) G) := by
  ext π
  constructor
  · rintro ⟨ζ, w, h, ⟨τ, υ, h', hτ, hυ, hs', rfl⟩, hw, hs, rfl⟩
    simp only [PreTrace.seam_ch, Chro.append_c, PreTrace.seam_ret, PreTrace.seam_fvw] at h hw hs
    refine ⟨τ, υ.seam w h, by simpa using h', hτ, ⟨υ, w, h, hυ, hw, hs, rfl⟩,
      by simpa using hs', ?_⟩
    exact PreTrace.seam_assoc h' h
  · rintro ⟨τ, ζ, h, hτ, ⟨υ, w, h', hυ, hw, hs', rfl⟩, hs, rfl⟩
    simp only [PreTrace.seam_ch, Chro.append_o, PreTrace.seam_ivw] at h hs
    refine ⟨τ.seam υ h, w, by simpa using h', ⟨τ, υ, h, hτ, hυ, hs, rfl⟩, hw,
      by simpa using hs', ?_⟩
    exact (PreTrace.seam_assoc h h').symm

/-! ## Well-formedness at the ends of a trace -/

theorem IsTrace.wf_o {τ : PreTrace Loc Val A} (h : IsTrace τ) : WellFormed τ.ch.o :=
  (h.wf _ τ.ch.first_mem).opening

theorem IsTrace.wf_c {τ : PreTrace Loc Val A} (h : IsTrace τ) : WellFormed τ.ch.c := by
  obtain ⟨T, hT, hc⟩ := listC_mem τ.ch.toList τ.ch.toList_ne_nil
  change WellFormed (listC τ.ch.toList)
  rw [hc]
  exact (h.wf T hT).closing

/-! ## The unit laws -/

theorem closure_bindGen_pureGen_left (r : A) (F : A → Set (PreTrace Loc Val B))
    (hF : ∀ a, IsTraceSet (F a)) (hFc : ∀ a, Closed (F a)) :
    closure (bindGen (closure (pureGen r)) F) = F r := by
  rw [closure_bindGen_closure_left (pureGen_isTrace r) hF]
  apply Set.Subset.antisymm
  · refine closure_subset_of_closed (hFc r) ?_
    rintro π ⟨τ, υ, h, hτ, hυ, hs, rfl⟩
    obtain ⟨κ, μ, hwf, hpd, rfl⟩ := hτ
    have hυ' : IsTrace υ := hF _ _ hυ
    have hτ' : IsTrace (⟨κ, Chro.single ⟨μ, μ⟩, κ, r⟩ : PreTrace Loc Val A) :=
      pureGen_isTrace r _ ⟨κ, μ, hwf, hpd, rfl⟩
    -- `Rewind` the initial view of `υ` down to `κ`, then `Stutter` in `⟨μ,μ⟩`.
    have hmid : IsTrace (⟨κ, υ.ch, υ.fvw, υ.ret⟩ : PreTrace Loc Val B) := by
      refine ⟨hυ'.wf, hpd.mono h, le_trans hs hυ'.mono, hυ'.closePts, ?_⟩
      intro ν hν
      obtain ⟨h1, h2, h3⟩ := hυ'.own ν hν
      exact ⟨le_trans hs h1, h2, lt_of_le_of_lt (hs ν.lc) h3⟩
    have hstep1 : TStep υ ⟨κ, υ.ch, υ.fvw, υ.ret⟩ := ⟨Step.rewind hs, hmid⟩
    have hstep2 : TStep (⟨κ, υ.ch, υ.fvw, υ.ret⟩ : PreTrace Loc Val B)
        (PreTrace.seam ⟨κ, Chro.single ⟨μ, μ⟩, κ, r⟩ υ h) := by
      refine ⟨Step.chro (ChroStep.stutter _ _ [] υ.ch.toList μ (by simp) ?_), hτ'.append hυ' hs h⟩
      simp [Chro.append_toList]
    exact (hFc r).mem_of_refines hυ ((Refines.single hstep1).tail hstep2)
  · intro υ hυ
    have hυ' : IsTrace υ := hF _ _ hυ
    refine ⟨PreTrace.seam ⟨υ.ivw, Chro.single ⟨υ.ch.o, υ.ch.o⟩, υ.ivw, r⟩ υ (by simp),
      ⟨_, υ, _, ⟨υ.ivw, υ.ch.o, hυ'.wf_o, hυ'.openPts, rfl⟩, hυ, le_refl _, rfl⟩, ?_⟩
    refine Refines.single ⟨Step.chro (ChroStep.mumble _ _ [] υ.ch.rest υ.ch.o υ.ch.o
      υ.ch.first.closing ?_ ?_), hυ'⟩
    · simp only [Chro.append_toList, Chro.single_toList, List.nil_append,
        List.singleton_append]
      rfl
    · simp only [List.nil_append]
      rfl

theorem closure_bindGen_pureGen_right (P : Set (PreTrace Loc Val A))
    (hP : IsTraceSet P) (hPc : Closed P) :
    closure (bindGen P (fun a ↦ closure (pureGen a))) = P := by
  rw [closure_bindGen_closure_right hP (fun a ↦ pureGen_isTrace a)]
  apply Set.Subset.antisymm
  · refine closure_subset_of_closed hPc ?_
    rintro π ⟨τ, υ, h, hτ, hυ, hs, rfl⟩
    obtain ⟨κ, μ, hwf, hpd, rfl⟩ := hυ
    have hτ' : IsTrace τ := hP _ hτ
    have hυ' : IsTrace (⟨κ, Chro.single ⟨μ, μ⟩, κ, τ.ret⟩ : PreTrace Loc Val A) :=
      pureGen_isTrace τ.ret _ ⟨κ, μ, hwf, hpd, rfl⟩
    have hmid : IsTrace (⟨τ.ivw, τ.ch.append (Chro.single ⟨μ, μ⟩) h, τ.fvw, τ.ret⟩ :
        PreTrace Loc Val A) := by
      refine ⟨?_, by simpa using hτ'.openPts, hτ'.mono, ?_, ?_⟩
      · intro T hT
        simp only [Chro.append_toList, Chro.single_toList, List.mem_append,
          List.mem_singleton] at hT
        rcases hT with hT | rfl
        · exact hτ'.wf T hT
        · exact ⟨hwf, hwf, subset_refl _⟩
      · simpa using hτ'.closePts.mono h
      · intro ν hν
        rw [Chro.append_own, Chro.single_own] at hν
        rcases hν with hν | hν
        · exact hτ'.own ν hν
        · simp only [Transition.own, Set.diff_self] at hν; exact absurd hν (by simp)
    have hstep1 : TStep τ ⟨τ.ivw, τ.ch.append (Chro.single ⟨μ, μ⟩) h, τ.fvw, τ.ret⟩ := by
      refine ⟨Step.chro (ChroStep.stutter _ _ τ.ch.toList [] μ (by simp) ?_), hmid⟩
      simp [Chro.append_toList]
    have hstep2 : TStep (⟨τ.ivw, τ.ch.append (Chro.single ⟨μ, μ⟩) h, τ.fvw, τ.ret⟩ :
        PreTrace Loc Val A)
        (PreTrace.seam τ ⟨κ, Chro.single ⟨μ, μ⟩, κ, τ.ret⟩ h) :=
      ⟨Step.forward hs, hτ'.append hυ' hs h⟩
    exact hPc.mem_of_refines hτ ((Refines.single hstep1).tail hstep2)
  · intro τ hτ
    have hτ' : IsTrace τ := hP _ hτ
    obtain ⟨l, T, hl, hc⟩ := listC_concat τ.ch.toList τ.ch.toList_ne_nil
    refine ⟨PreTrace.seam τ ⟨τ.fvw, Chro.single ⟨τ.ch.c, τ.ch.c⟩, τ.fvw, τ.ret⟩ (by simp),
      ⟨τ, _, _, hτ, ⟨τ.fvw, τ.ch.c, hτ'.wf_c, hτ'.closePts, rfl⟩, le_refl _, rfl⟩, ?_⟩
    refine Refines.single ⟨Step.chro (ChroStep.mumble _ _ l [] T.opening τ.ch.c τ.ch.c ?_ ?_),
      hτ'⟩
    · simp only [Chro.append_toList, Chro.single_toList]
      rw [hl]
      simp only [List.append_assoc, List.cons_append, List.nil_append]
      rw [show T = ⟨T.opening, T.closing⟩ from rfl, ← hc]
      rfl
    · rw [hl]
      have hTc : τ.ch.c = T.closing := hc
      rw [hTc]

/-! ## The carrier -/

/-- The release/acquire trace monad: `𝔠`-closed sets of `A`-traces. -/
structure Comp (Loc Val : Type) (A : Type u) where
  /-- The set of traces. -/
  traces : Set (PreTrace Loc Val A)
  /-- Every element is a trace. -/
  isTrace : IsTraceSet traces
  /-- The set is `𝔠`-closed. -/
  closed : Closed traces

namespace Comp

@[ext] theorem ext {P Q : Comp Loc Val A} (h : P.traces = Q.traces) : P = Q := by
  cases P; cases Q; cases h; rfl

instance : Membership (PreTrace Loc Val A) (Comp Loc Val A) where
  mem P τ := τ ∈ P.traces

theorem mem_def {P : Comp Loc Val A} {τ : PreTrace Loc Val A} :
    τ ∈ P ↔ τ ∈ P.traces := Iff.rfl

/-- Close a set of traces. -/
def close (S : Set (PreTrace Loc Val A)) (hS : IsTraceSet S) : Comp Loc Val A where
  traces := closure S
  isTrace := hS.closure
  closed := closure_closed S

@[simp] theorem traces_close (S : Set (PreTrace Loc Val A)) (hS : IsTraceSet S) :
    (close S hS).traces = closure S := rfl

/-- `return r`. -/
protected def pure (r : A) : Comp Loc Val A := close (pureGen r) (pureGen_isTrace r)

/-- `P >>= f`. -/
protected def bind (P : Comp Loc Val A) (f : A → Comp Loc Val B) : Comp Loc Val B :=
  close (bindGen P.traces (fun a ↦ (f a).traces))
    (bindGen_isTrace P.isTrace (fun a ↦ (f a).isTrace))

instance : _root_.Monad (Comp Loc Val) where
  pure := Comp.pure
  bind := Comp.bind

@[simp] theorem traces_pure (r : A) :
    (Pure.pure r : Comp Loc Val A).traces = closure (pureGen r) := rfl

@[simp] theorem traces_bind (P : Comp Loc Val A) (f : A → Comp Loc Val B) :
    (P >>= f).traces = closure (bindGen P.traces (fun a ↦ (f a).traces)) := rfl

theorem pure_bind (r : A) (f : A → Comp Loc Val B) :
    (Pure.pure r : Comp Loc Val A) >>= f = f r := by
  apply ext
  rw [traces_bind, traces_pure]
  exact closure_bindGen_pureGen_left r _ (fun a ↦ (f a).isTrace) (fun a ↦ (f a).closed)

theorem bind_pure (P : Comp Loc Val A) : P >>= Pure.pure = P := by
  apply ext
  rw [traces_bind]
  exact closure_bindGen_pureGen_right P.traces P.isTrace P.closed

theorem bind_assoc (P : Comp Loc Val A) (f : A → Comp Loc Val B) (g : B → Comp Loc Val C) :
    P >>= f >>= g = P >>= fun a ↦ f a >>= g := by
  apply ext
  change closure (bindGen (closure (bindGen P.traces (fun a ↦ (f a).traces)))
      (fun b ↦ (g b).traces))
    = closure (bindGen P.traces
      (fun a ↦ closure (bindGen (f a).traces (fun b ↦ (g b).traces))))
  rw [closure_bindGen_closure_left (bindGen_isTrace P.isTrace (fun a ↦ (f a).isTrace))
      (fun b ↦ (g b).isTrace),
    closure_bindGen_closure_right P.isTrace
      (fun a ↦ bindGen_isTrace (f a).isTrace (fun b ↦ (g b).isTrace)),
    bindGen_assoc]

instance : LawfulMonad (Comp Loc Val) := LawfulMonad.mk'
  (id_map := fun x ↦ bind_pure x)
  (pure_bind := fun a f ↦ pure_bind a f)
  (bind_assoc := fun x f g ↦ bind_assoc x f g)

/-! ## Order, bottom, and unions

`T X` is ordered by inclusion (§7.2), `∅` is `𝔠`-closed, and closedness is a
Horn condition, hence preserved by arbitrary unions.  These are the only
ingredients the iteration operator needs. -/

instance : PartialOrder (Comp Loc Val A) where
  le P Q := P.traces ⊆ Q.traces
  le_refl _ := subset_refl _
  le_trans _ _ _ h₁ h₂ := subset_trans h₁ h₂
  le_antisymm _ _ h₁ h₂ := ext (Set.Subset.antisymm h₁ h₂)

theorem le_def {P Q : Comp Loc Val A} : P ≤ Q ↔ P.traces ⊆ Q.traces := Iff.rfl

instance : OrderBot (Comp Loc Val A) where
  bot := ⟨∅, fun _ h ↦ absurd h (by simp), closed_empty⟩
  bot_le _ := by intro τ hτ; exact absurd hτ (by simp)

@[simp] theorem traces_bot : (⊥ : Comp Loc Val A).traces = ∅ := rfl

/-- The union of a family of computations. -/
def iUnion {ι : Sort*} (x : ι → Comp Loc Val A) : Comp Loc Val A where
  traces := ⋃ i, (x i).traces
  isTrace := by
    rintro τ hτ
    rw [Set.mem_iUnion] at hτ
    obtain ⟨i, hi⟩ := hτ
    exact (x i).isTrace _ hi
  closed := closed_iUnion (fun i ↦ (x i).closed)

@[simp] theorem traces_iUnion {ι : Sort*} (x : ι → Comp Loc Val A) :
    (iUnion x).traces = ⋃ i, (x i).traces := rfl

theorem le_iUnion {ι : Sort*} (x : ι → Comp Loc Val A) (i : ι) : x i ≤ iUnion x := by
  intro τ hτ; rw [traces_iUnion, Set.mem_iUnion]; exact ⟨i, hτ⟩

theorem iUnion_le {ι : Sort*} {x : ι → Comp Loc Val A} {P : Comp Loc Val A}
    (h : ∀ i, x i ≤ P) : iUnion x ≤ P := by
  intro τ hτ
  rw [traces_iUnion, Set.mem_iUnion] at hτ
  obtain ⟨i, hi⟩ := hτ
  exact h i hi

theorem iUnion_const {ι : Sort*} [Nonempty ι] (P : Comp Loc Val A) :
    iUnion (fun _ : ι ↦ P) = P := by
  apply ext
  rw [traces_iUnion, Set.iUnion_const]

theorem bot_bind (f : A → Comp Loc Val B) : (⊥ : Comp Loc Val A) >>= f = ⊥ := by
  apply ext; simp

theorem bind_mono {P Q : Comp Loc Val A} {f g : A → Comp Loc Val B} (h : P ≤ Q)
    (hfg : ∀ a, f a ≤ g a) : P >>= f ≤ Q >>= g := by
  rw [le_def, traces_bind, traces_bind]
  exact closure_mono (bindGen_mono h (fun a ↦ hfg a))

theorem bind_mono_right {P : Comp Loc Val A} {f g : A → Comp Loc Val B}
    (hfg : ∀ a, f a ≤ g a) : P >>= f ≤ P >>= g := bind_mono (le_refl P) hfg

theorem iUnion_bind {ι : Sort*} (x : ι → Comp Loc Val A) (f : A → Comp Loc Val B) :
    iUnion x >>= f = iUnion (fun i ↦ x i >>= f) := by
  apply ext
  rw [traces_bind, traces_iUnion, traces_iUnion, bindGen_iUnion_left, closure_iUnion]
  rfl

theorem bind_iUnion {ι : Sort*} (P : Comp Loc Val A) (f : ι → A → Comp Loc Val B) :
    (P >>= fun a ↦ iUnion (fun i ↦ f i a)) = iUnion (fun i ↦ P >>= f i) := by
  apply ext
  rw [traces_bind, traces_iUnion]
  rw [show (fun a ↦ (iUnion (fun i ↦ f i a)).traces) = (fun a ↦ ⋃ i, (f i a).traces) from rfl]
  rw [bindGen_iUnion_right, closure_iUnion]
  rfl

end Comp

end Isotope.Elgot.RA
