import Isotope.Elgot.Brookes.Basic
import Isotope.Elgot.Brookes.Closure
import Isotope.Elgot.Brookes.Monad
import Isotope.Elgot.Brookes.Iteration
import Isotope.Elgot.Brookes.Parallel
import Isotope.Elgot.Brookes.SeqCst
import Isotope.Elgot.Brookes.SeqCst.Parallel
import Isotope.Elgot.Brookes.SeqCst.Chunk
import Isotope.Elgot.Brookes.SeqCst.Syntax
import Isotope.Elgot.Brookes.SeqCst.Context
import Isotope.Elgot.Brookes.TSO
import Isotope.Elgot.Brookes.Compare
import Isotope.Elgot.Brookes.Examples

/-!
# Brookes-style trace monads, and sequential consistency

A *Brookes computation* is a closed set of pairs `t ⊢ a` of a finite trace and a
returned value; the closure operator is generated by a trace-rewriting system.
For the standard model traces are words of rely-guarantee pairs `⟨μ, ρ⟩` over a
state type `S`, and the rules are Brookes's stuttering and mumbling.  Sequential
consistency is that model with `S := Loc → Val`.

## What is proved

* `Isotope.Elgot.Brookes` — the carrier, a `c`-closed set of executions, for an
  arbitrary rewriting system `c : Brookes.Rewriting E` over an arbitrary event
  alphabet `E`.
* `Monad (Brookes c)` and `LawfulMonad (Brookes c)`: `pure` is the closure of the
  empty-trace execution, `bind` the closure of all trace concatenations.
* `Iterate (Brookes c)` by the paper's approximants `f† = ⋃ᵢ fᵢ`, and the full
  `LawfulElgotMonad (Brookes c)` instance — all four laws, including codiagonal.
  Iteration is computable; no choice principle is used.
* `SeqCst.rewriting` — the stuttering/mumbling closure — with `SeqCst.write`
  (the paper's definition) and `SeqCst.read`.
* `Brookes.ofFiniteTrace`, a morphism from the deterministic `FiniteTrace` model
  commuting with `pure`, `bind` and `iter` on the nose, together with the proof
  that it is not order-reflecting.
* Representative examples: reads, writes, the `st-st` and `st-ld` refinements,
  observable interference between two reads, a terminating loop, and divergent
  loops.

## Honest boundary

* **Partial correctness only.**  `iter` discards infinite executions, so a body
  that always recurses denotes `⊥` (`Brookes.iter_forever`,
  `SeqCst.iter_write_forever`).  Divergence is the bottom of the refinement
  order and is not observationally distinguished from "no execution".  This is
  exactly the paper's construction, not a weakening of it.
* **No infinite-trace extension.**  The appendix gives no construction for
  productive infinite traces, and mumbling does not extend to them cleanly:
  finitely many rewriting steps can never contract an infinite trace, whereas
  the intended semantics wants ω-many mumbles.  That needs a coinductive or
  limit closure plus a fairness side condition, and it changes what the union of
  finite and infinite behaviours means.  Nothing about infinite traces is
  claimed here.
* **No comparison with a nondeterministic trace-set model.**  No such carrier
  exists in this formalization yet; `Brookes/Compare.lean` records the intended
  statement in a docstring only.
* **No `InstructionModel` instance.**  `Brookes c` satisfies every class the
  lambda-iter denotational semantics requires, so any `InstructionModel` over
  those classes yields a lambda-iter model; but choosing a concrete instruction
  signature and effect lattice is left out of scope, and no specific lambda-iter
  model is shipped.
* **`SeqCst.read` is an extrapolation.**  The paper gives `write` only; `read` is
  the obvious dual and is flagged as such where it is defined.
* The paper's closure-operator axioms (extensive, idempotent, distributing over
  countable unions) are **not sufficient** for `B_c` to be a monad: the unit and
  associativity laws additionally need compatibility with concatenation.  That
  is why `Rewriting` carries two congruence fields, from which
  `Rewriting.refines_append` follows.

## API for downstream models

A different memory model — TSO, release/acquire — should reuse this development
by supplying **only a new `Rewriting`** (or only a new state type, if the rules
are still stuttering and mumbling with a richer state).  Nothing below needs to
be reproved:

* `Brookes.Trace`, `Brookes.Rewriting`, `Rewriting.Refines`, and the congruence
  lemmas `Rewriting.step_appendLeft`, `Rewriting.refines_appendRight`,
  `Rewriting.refines_appendLeft`, `Rewriting.refines_append` (`Brookes/Basic.lean`).
* The closure operator `Rewriting.closure` and predicate `Rewriting.Closed`,
  with `Rewriting.subset_closure`, `closure_mono`, `closure_closed`,
  `Closed.closure_eq`, `closure_idem`, `closed_iff`, `Closed.mem_of_refines`,
  `Closed.iUnion`, `Closed.iInter`, `closure_iUnion`, `closure_empty`
  (`Brookes/Closure.lean`).
* The carrier and its algebra: `Brookes.close`, `Brookes.mem_close_iff`,
  `Brookes.mem_pure_iff`, `Brookes.mem_bind_iff`, `Brookes.mem_kcomp_iff`,
  `Brookes.iUnion`, `Brookes.iUnion_bind`, `Brookes.bind_iUnion`,
  `Brookes.bind_mono`, and the `Monad`/`LawfulMonad` instances
  (`Brookes/Monad.lean`).
* Iteration: `Brookes.approx`, `Brookes.iterate`, `Brookes.mem_iter_iff`,
  `Brookes.mem_iter_done`, `Brookes.mem_iter_more`, `Brookes.Runs`,
  `Brookes.mem_iter_iff_runs`, and the `Iterate`/`LawfulElgotMonad` instances
  (`Brookes/Iteration.lean`).
* The bridge `Brookes.ofFiniteTrace` and its `pure`/`bind`/`iter` equations
  (`Brookes/Compare.lean`), which are stated for an arbitrary `Rewriting`.

Only `Brookes/SeqCst.lean` is specific to stuttering and mumbling; a new model
should mirror that file and nothing else.

`Brookes/TSO.lean` is the worked instance: a store-buffer model of TSO weak
memory obtained by keeping the stuttering and mumbling rules and enriching the
state with one write buffer per thread.  It reproves nothing from this file.
-/
