import Isotope.Elgot.Brookes.Basic

/-!
# The closure operator generated by a trace rewriting system

Following the paper, the closure operator acts *fibrewise over the return value*:
a computation is a set of pairs `t ⊢ a` of a trace and a returned value, and
closing it never changes the value component.  Concretely, `c.closure X` adds
every `c`-rewrite of every trace in `X`.

This file proves the closure-operator laws — extensivity, monotonicity,
idempotence — together with the facts the monad structure actually consumes:
closed sets are exactly the fixed points, closure distributes over *arbitrary*
(not merely countable) unions, and closed sets are stable under arbitrary unions.
Downstream models (TSO, release/acquire, …) should reuse this API unchanged and
only supply a different `Rewriting`.
-/

namespace Isotope.Elgot.Brookes

universe u v

namespace Rewriting

variable {E : Type u} {A : Type u} (c : Rewriting E)

/-- A set of `(trace, value)` pairs is `c`-closed when rewriting never leaves it. -/
def Closed (X : Set (Trace E × A)) : Prop :=
  ∀ t a, (t, a) ∈ X → ∀ t', c.Step t t' → (t', a) ∈ X

/-- The `c`-closure of a raw set of executions: every rewrite of every member. -/
def closure (X : Set (Trace E × A)) : Set (Trace E × A) :=
  {p | ∃ t, (t, p.2) ∈ X ∧ c.Refines t p.1}

variable {c}

@[simp] theorem mem_closure_iff {X : Set (Trace E × A)} {t : Trace E} {a : A} :
    (t, a) ∈ c.closure X ↔ ∃ t₀, (t₀, a) ∈ X ∧ c.Refines t₀ t := Iff.rfl

/-- A closed set absorbs refinement, not merely single steps. -/
theorem Closed.mem_of_refines {X : Set (Trace E × A)} (h : c.Closed X)
    {t t' : Trace E} {a : A} (hmem : (t, a) ∈ X) (hr : c.Refines t t') : (t', a) ∈ X := by
  induction hr with
  | refl => exact hmem
  | tail _ hstep ih => exact h _ a ih _ hstep

/-- Closure is extensive. -/
theorem subset_closure (X : Set (Trace E × A)) : X ⊆ c.closure X := by
  rintro ⟨t, a⟩ h
  exact ⟨t, h, .refl⟩

/-- Closure is monotone. -/
theorem closure_mono {X Y : Set (Trace E × A)} (h : X ⊆ Y) : c.closure X ⊆ c.closure Y := by
  rintro ⟨t, a⟩ ⟨t₀, hmem, hr⟩
  exact ⟨t₀, h hmem, hr⟩

/-- Closures are closed. -/
theorem closure_closed (X : Set (Trace E × A)) : c.Closed (c.closure X) := by
  rintro t a ⟨t₀, hmem, hr⟩ t' hstep
  exact ⟨t₀, hmem, hr.tail hstep⟩

/-- A closed set is its own closure. -/
theorem Closed.closure_eq {X : Set (Trace E × A)} (h : c.Closed X) : c.closure X = X := by
  apply Set.Subset.antisymm
  · rintro ⟨t, a⟩ ⟨t₀, hmem, hr⟩
    exact h.mem_of_refines hmem hr
  · exact subset_closure X

/-- Closure is idempotent. -/
theorem closure_idem (X : Set (Trace E × A)) :
    c.closure (c.closure X) = c.closure X :=
  (closure_closed X).closure_eq

/-- Closed sets are exactly the fixed points of the closure operator. -/
theorem closed_iff (X : Set (Trace E × A)) : c.Closed X ↔ c.closure X = X :=
  ⟨Closed.closure_eq, fun h ↦ h ▸ closure_closed X⟩

/-- Closure preserves inclusion into a closed set. -/
theorem closure_subset_of_closed {X Y : Set (Trace E × A)} (hY : c.Closed Y) (h : X ⊆ Y) :
    c.closure X ⊆ Y := by
  rw [← hY.closure_eq]; exact closure_mono h

/-- The empty set is closed. -/
theorem closed_empty : c.Closed (∅ : Set (Trace E × A)) := by
  rintro t a h; exact h.elim

@[simp] theorem closure_empty : c.closure (∅ : Set (Trace E × A)) = ∅ :=
  closed_empty.closure_eq

/-- Closed sets are stable under arbitrary unions.  In particular joins in the
Brookes carrier need no closure step; only `pure` and `bind` do. -/
theorem Closed.iUnion {ι : Sort v} {X : ι → Set (Trace E × A)}
    (h : ∀ i, c.Closed (X i)) : c.Closed (⋃ i, X i) := by
  rintro t a hmem t' hstep
  rw [Set.mem_iUnion] at hmem ⊢
  obtain ⟨i, hi⟩ := hmem
  exact ⟨i, h i _ a hi _ hstep⟩

/-- Closed sets are stable under arbitrary intersections. -/
theorem Closed.iInter {ι : Sort v} {X : ι → Set (Trace E × A)}
    (h : ∀ i, c.Closed (X i)) : c.Closed (⋂ i, X i) := by
  rintro t a hmem t' hstep
  rw [Set.mem_iInter] at hmem ⊢
  exact fun i ↦ h i _ a (hmem i) _ hstep

/-- Closure distributes over arbitrary unions; the paper only asks for countable
ones. -/
theorem closure_iUnion {ι : Sort v} (X : ι → Set (Trace E × A)) :
    c.closure (⋃ i, X i) = ⋃ i, c.closure (X i) := by
  apply Set.Subset.antisymm
  · rintro ⟨t, a⟩ ⟨t₀, hmem, hr⟩
    rw [Set.mem_iUnion] at hmem
    obtain ⟨i, hi⟩ := hmem
    exact Set.mem_iUnion.2 ⟨i, ⟨t₀, hi, hr⟩⟩
  · rintro ⟨t, a⟩ hmem
    rw [Set.mem_iUnion] at hmem
    obtain ⟨i, t₀, hi, hr⟩ := hmem
    exact ⟨t₀, Set.mem_iUnion.2 ⟨i, hi⟩, hr⟩

end Rewriting

end Isotope.Elgot.Brookes
