import Isotope.Elgot.Basic
import Isotope.Elgot.Brookes.Closure
import Mathlib.Order.Basic

/-!
# The Brookes monad

`Brookes c A` is the carrier of the paper's Brookes monad `B_c`: a `c`-closed set
of terminating executions, each a finite trace paired with the value it returns.

`pure a` is the closure of the single empty-trace execution, and `x >>= f` is the
closure of all concatenations of an `x`-execution with an execution of `f` of its
returned value.

**There is no compatibility check in `bind`.**  Adjacent steps `⟨μ, ρ⟩⟨μ', θ⟩`
with `ρ ≠ μ'` are deliberately allowed: that discontinuity *is* the environment's
interference.  Composability is only rewarded, by the mumbling rule of the
closure operator.  A `bind` that checked `ρ = μ'` would be a different,
interference-free model.

The closure in `bind` is not decoration: the raw concatenation set is not closed,
because a rewrite may cross the concatenation seam (for stutter/mumble, mumbling
`⟨μ, ρ⟩⟨ρ, θ⟩` into `⟨μ, θ⟩` merges the last step of `x` with the first step of
`f a`, and the result is generally not a concatenation of an `x`-trace with an
`f a`-trace).
-/

namespace Isotope.Elgot

universe u v

/-- A Brookes computation over the closure operator generated by `c`: a closed
set of terminating executions, each a finite trace paired with a return value. -/
structure Brookes {E : Type u} (c : Brookes.Rewriting E) (A : Type u) : Type u where
  /-- The executions of the computation. -/
  traces : Set (Brookes.Trace E × A)
  /-- Executions are closed under the rewriting system generating `c`. -/
  closed : c.Closed traces

namespace Brookes

variable {E : Type u} {c : Rewriting E} {A B C : Type u}

@[ext] theorem ext {x y : Brookes c A} (h : x.traces = y.traces) : x = y := by
  cases x; cases y; cases h; rfl

instance : Membership (Trace E × A) (Brookes c A) :=
  ⟨fun x p ↦ p ∈ x.traces⟩

theorem mem_def {x : Brookes c A} {p : Trace E × A} : p ∈ x ↔ p ∈ x.traces := Iff.rfl

/-- A computation absorbs refinement of its traces. -/
theorem mem_of_refines {x : Brookes c A} {t t' : Trace E} {a : A}
    (hmem : (t, a) ∈ x) (hr : c.Refines t t') : (t', a) ∈ x :=
  x.closed.mem_of_refines hmem hr

theorem ext_mem {x y : Brookes c A} (h : ∀ t a, (t, a) ∈ x ↔ (t, a) ∈ y) : x = y := by
  apply ext
  apply Set.ext
  rintro ⟨t, a⟩
  exact h t a

/-- The computation generated by a raw set of executions. -/
def close (c : Rewriting E) (X : Set (Trace E × A)) : Brookes c A :=
  ⟨c.closure X, c.closure_closed X⟩

@[simp] theorem mem_close_iff {X : Set (Trace E × A)} {t : Trace E} {a : A} :
    (t, a) ∈ close c X ↔ ∃ t₀, (t₀, a) ∈ X ∧ c.Refines t₀ t := Iff.rfl

/-! ## The refinement order -/

instance : PartialOrder (Brookes c A) where
  le x y := x.traces ⊆ y.traces
  le_refl _ := subset_rfl
  le_trans _ _ _ h h' := Set.Subset.trans h h'
  le_antisymm _ _ h h' := ext (Set.Subset.antisymm h h')

theorem le_def {x y : Brookes c A} : x ≤ y ↔ ∀ t a, (t, a) ∈ x → (t, a) ∈ y := by
  constructor
  · exact fun h t a hm ↦ h hm
  · rintro h ⟨t, a⟩ hm; exact h t a hm

theorem le_of_mem {x y : Brookes c A} (h : ∀ t a, (t, a) ∈ x → (t, a) ∈ y) : x ≤ y :=
  le_def.2 h

instance : OrderBot (Brookes c A) where
  bot := ⟨∅, Rewriting.closed_empty⟩
  bot_le _ := Set.empty_subset _

@[simp] theorem not_mem_bot (p : Trace E × A) : p ∉ (⊥ : Brookes c A) := id

@[simp] theorem traces_bot : (⊥ : Brookes c A).traces = ∅ := rfl

theorem eq_bot_iff_forall {x : Brookes c A} : x = ⊥ ↔ ∀ t a, (t, a) ∉ x := by
  constructor
  · rintro rfl t a h; exact h
  · intro h; exact ext_mem fun t a ↦ ⟨fun hm ↦ (h t a hm).elim, fun hm ↦ hm.elim⟩

/-- Nondeterministic choice: an arbitrary union of computations.  No closure step
is needed, since closed sets are stable under unions. -/
def iUnion {ι : Sort v} (x : ι → Brookes c A) : Brookes c A :=
  ⟨⋃ i, (x i).traces, Rewriting.Closed.iUnion fun i ↦ (x i).closed⟩

@[simp] theorem mem_iUnion_iff {ι : Sort v} {x : ι → Brookes c A} {p : Trace E × A} :
    p ∈ iUnion x ↔ ∃ i, p ∈ x i := Set.mem_iUnion

theorem le_iUnion {ι : Sort v} (x : ι → Brookes c A) (i : ι) : x i ≤ iUnion x :=
  le_of_mem fun _ _ h ↦ mem_iUnion_iff.2 ⟨i, h⟩

theorem iUnion_le {ι : Sort v} {x : ι → Brookes c A} {y : Brookes c A}
    (h : ∀ i, x i ≤ y) : iUnion x ≤ y :=
  le_of_mem fun t a hm ↦ by
    obtain ⟨i, hi⟩ := mem_iUnion_iff.1 hm
    exact h i hi

/-! ## Monad structure -/

instance : Monad (Brookes c) where
  pure a := close c {(([] : Trace E), a)}
  bind x f := close c {p | ∃ a u v, (u, a) ∈ x.traces ∧ (v, p.2) ∈ (f a).traces ∧ p.1 = u ++ v}

theorem mem_pure_iff (a b : A) (t : Trace E) :
    (t, b) ∈ (pure a : Brookes c A) ↔ b = a ∧ c.Refines [] t := by
  constructor
  · rintro ⟨t₀, ht₀, hr⟩
    simp only [Set.mem_singleton_iff, Prod.mk.injEq] at ht₀
    obtain ⟨rfl, rfl⟩ := ht₀
    exact ⟨rfl, hr⟩
  · rintro ⟨rfl, hr⟩
    exact ⟨[], rfl, hr⟩

theorem mem_pure (a : A) : (([] : Trace E), a) ∈ (pure a : Brookes c A) :=
  (mem_pure_iff a a []).2 ⟨rfl, .refl⟩

theorem mem_bind_iff (x : Brookes c A) (f : A → Brookes c B) (t : Trace E) (b : B) :
    (t, b) ∈ (x >>= f) ↔ ∃ a u v, (u, a) ∈ x ∧ (v, b) ∈ f a ∧ c.Refines (u ++ v) t := by
  constructor
  · rintro ⟨t₀, ⟨a, u, v, hu, hv, rfl⟩, hr⟩
    exact ⟨a, u, v, hu, hv, hr⟩
  · rintro ⟨a, u, v, hu, hv, hr⟩
    exact ⟨u ++ v, ⟨a, u, v, hu, hv, rfl⟩, hr⟩

theorem mem_bind (x : Brookes c A) (f : A → Brookes c B) {u v : Trace E} {a : A} {b : B}
    (hu : (u, a) ∈ x) (hv : (v, b) ∈ f a) : (u ++ v, b) ∈ (x >>= f) :=
  (mem_bind_iff x f _ b).2 ⟨a, u, v, hu, hv, .refl⟩

theorem mem_kcomp_iff (f : A → Brookes c B) (g : B → Brookes c C) (a : A) (t : Trace E) (d : C) :
    (t, d) ∈ kcomp f g a ↔ ∃ b u v, (u, b) ∈ f a ∧ (v, d) ∈ g b ∧ c.Refines (u ++ v) t :=
  mem_bind_iff (f a) g t d

@[simp] theorem bot_bind (f : A → Brookes c B) : (⊥ : Brookes c A) >>= f = ⊥ := by
  apply ext_mem
  intro t b
  rw [mem_bind_iff]
  exact ⟨by rintro ⟨a, u, v, hu, -, -⟩; exact hu.elim, fun h ↦ h.elim⟩

@[simp] theorem bind_bot (x : Brookes c A) : (x >>= fun _ ↦ (⊥ : Brookes c B)) = ⊥ := by
  apply ext_mem
  intro t b
  rw [mem_bind_iff]
  exact ⟨by rintro ⟨a, u, v, -, hv, -⟩; exact hv.elim, fun h ↦ h.elim⟩

theorem bind_mono {x y : Brookes c A} {f g : A → Brookes c B}
    (hxy : x ≤ y) (hfg : ∀ a, f a ≤ g a) : x >>= f ≤ y >>= g := by
  apply le_of_mem
  intro t b hm
  rw [mem_bind_iff] at hm ⊢
  obtain ⟨a, u, v, hu, hv, hr⟩ := hm
  exact ⟨a, u, v, hxy hu, hfg a hv, hr⟩

theorem bind_mono_left {x y : Brookes c A} (h : x ≤ y) (f : A → Brookes c B) :
    x >>= f ≤ y >>= f := bind_mono h fun _ ↦ le_rfl

theorem bind_mono_right (x : Brookes c A) {f g : A → Brookes c B} (h : ∀ a, f a ≤ g a) :
    x >>= f ≤ x >>= g := bind_mono le_rfl h

/-- Kleisli composition is continuous in its first argument, for arbitrary unions. -/
theorem iUnion_bind {ι : Sort v} (x : ι → Brookes c A) (f : A → Brookes c B) :
    (iUnion x >>= f) = iUnion fun i ↦ (x i >>= f) := by
  apply ext_mem
  intro t b
  rw [mem_bind_iff, mem_iUnion_iff]
  constructor
  · rintro ⟨a, u, v, hu, hv, hr⟩
    obtain ⟨i, hi⟩ := mem_iUnion_iff.1 hu
    exact ⟨i, (mem_bind_iff _ f t b).2 ⟨a, u, v, hi, hv, hr⟩⟩
  · rintro ⟨i, hi⟩
    obtain ⟨a, u, v, hu, hv, hr⟩ := (mem_bind_iff _ f t b).1 hi
    exact ⟨a, u, v, mem_iUnion_iff.2 ⟨i, hu⟩, hv, hr⟩

/-- Kleisli composition is continuous in its second argument, for arbitrary unions. -/
theorem bind_iUnion {ι : Sort v} (x : Brookes c A) (f : ι → A → Brookes c B) :
    (x >>= fun a ↦ iUnion fun i ↦ f i a) = iUnion fun i ↦ (x >>= f i) := by
  apply ext_mem
  intro t b
  rw [mem_bind_iff, mem_iUnion_iff]
  constructor
  · rintro ⟨a, u, v, hu, hv, hr⟩
    obtain ⟨i, hi⟩ := mem_iUnion_iff.1 hv
    exact ⟨i, (mem_bind_iff _ (f i) t b).2 ⟨a, u, v, hu, hi, hr⟩⟩
  · rintro ⟨i, hi⟩
    obtain ⟨a, u, v, hu, hv, hr⟩ := (mem_bind_iff _ (f i) t b).1 hi
    exact ⟨a, u, v, hu, mem_iUnion_iff.2 ⟨i, hv⟩, hr⟩

/-- Left unit: the empty trace of `pure` is absorbed by refinement. -/
theorem pure_bind_eq (a : A) (f : A → Brookes c B) : (pure a : Brookes c A) >>= f = f a := by
  apply ext_mem
  intro t b
  rw [mem_bind_iff]
  constructor
  · rintro ⟨a', u, v, hu, hv, hr⟩
    obtain ⟨rfl, hu0⟩ := (mem_pure_iff a a' u).1 hu
    have h1 : c.Refines ([] ++ v) (u ++ v) := Rewriting.refines_appendRight hu0 v
    rw [List.nil_append] at h1
    exact mem_of_refines hv (h1.trans hr)
  · intro hm
    refine ⟨a, [], t, mem_pure a, hm, ?_⟩
    rw [List.nil_append]

/-- Right unit: the empty trace of `pure` is absorbed by refinement. -/
theorem bind_pure_eq (x : Brookes c A) : (x >>= fun a ↦ (pure a : Brookes c A)) = x := by
  apply ext_mem
  intro t a
  rw [mem_bind_iff]
  constructor
  · rintro ⟨a', u, v, hu, hv, hr⟩
    obtain ⟨rfl, hv0⟩ := (mem_pure_iff a' a v).1 hv
    have h1 : c.Refines (u ++ []) (u ++ v) := Rewriting.refines_appendLeft u hv0
    rw [List.append_nil] at h1
    exact mem_of_refines hu (h1.trans hr)
  · intro hm
    refine ⟨a, t, [], hm, mem_pure a, ?_⟩
    rw [List.append_nil]

/-- Associativity: concatenation of traces is associative, and closure absorbs
refinement on either side of the seam. -/
theorem bind_assoc_eq (x : Brookes c A) (f : A → Brookes c B) (g : B → Brookes c C) :
    x >>= f >>= g = x >>= fun a ↦ f a >>= g := by
  apply ext_mem
  intro t d
  rw [mem_bind_iff, mem_bind_iff]
  constructor
  · rintro ⟨b, u', v', hu', hv', hr'⟩
    obtain ⟨a, u, v, hu, hv, hr⟩ := (mem_bind_iff x f u' b).1 hu'
    refine ⟨a, u, v ++ v', hu, (mem_bind_iff (f a) g _ d).2 ⟨b, v, v', hv, hv', .refl⟩, ?_⟩
    rw [← List.append_assoc]
    exact (Rewriting.refines_appendRight hr v').trans hr'
  · rintro ⟨a, u, w, hu, hw, hr⟩
    obtain ⟨b, v, v', hv, hv', hr'⟩ := (mem_bind_iff (f a) g w d).1 hw
    refine ⟨b, u ++ v, v', (mem_bind_iff x f _ b).2 ⟨a, u, v, hu, hv, .refl⟩, hv', ?_⟩
    rw [List.append_assoc]
    exact (Rewriting.refines_appendLeft u hr').trans hr

instance : LawfulMonad (Brookes c) := LawfulMonad.mk'
  (id_map := fun x ↦ bind_pure_eq x)
  (pure_bind := fun a f ↦ pure_bind_eq a f)
  (bind_assoc := fun x f g ↦ bind_assoc_eq x f g)
  (bind_pure_comp := by intro A B f x; rfl)

end Brookes

end Isotope.Elgot
