import Isotope.LambdaIter.Subtyping.Semantics.Instruction

/-!
# Set-valued models of the freely generated type universe

`Isotope.LambdaIter.Ty α` is the simple type universe freely generated by base
types `α`.  Fixing an interpretation `β : α → Type v` of the base types
determines an interpretation of every type by structural recursion, and of
every proof-relevant subtyping derivation by recursion on the derivation.

This is the generic construction; the concrete models in
`Models/{Null,BitVec,Nat}.lean` choose `α` and `β`.  Before this file the
repository contained no `TypeModel` instance at all, so nothing could be
plugged into the denotational semantics.

The two structural coercions are forced by the `Subtyping` interface: `empty`
is initial and `unit` is terminal, so `Subty.empty` denotes the empty
eliminator and `Subty.unit` the constant map.  Nothing else is coerced, so the
model is *not* proof-irrelevant by accident: distinct derivations between the
same pair of types may still denote distinct coercions in general, and the
`LawfulTypeModel` laws below are exactly the coherence the equational theory
needs, no more.
-/

namespace Isotope.LambdaIter.Subtyping.Semantics

universe u v

namespace Free

variable {α : Type u}

/-- The interpretation of a freely generated type, given one for base types. -/
@[reducible] def interp (β : α → Type v) : LambdaIter.Ty α → Type v
  | .base a => β a
  | .tensor A B => interp β A × interp β B
  | .unit => PUnit
  | .coprod A B => interp β A ⊕ interp β B
  | .empty => PEmpty

@[simp] theorem interp_base (β : α → Type v) (a : α) :
    interp β (.base a) = β a := rfl

@[simp] theorem interp_tensor (β : α → Type v) (A B : LambdaIter.Ty α) :
    interp β (.tensor A B) = (interp β A × interp β B) := rfl

@[simp] theorem interp_unit (β : α → Type v) :
    interp β (.unit : LambdaIter.Ty α) = PUnit := rfl

@[simp] theorem interp_coprod (β : α → Type v) (A B : LambdaIter.Ty α) :
    interp β (.coprod A B) = (interp β A ⊕ interp β B) := rfl

@[simp] theorem interp_empty (β : α → Type v) :
    interp β (.empty : LambdaIter.Ty α) = PEmpty := rfl

/-- The coercion denoted by a proof-relevant subtyping derivation. -/
def coe (β : α → Type v) :
    {A B : LambdaIter.Ty α} → LambdaIter.Ty.Subty A B → interp β A → interp β B
  | _, _, .refl _ => id
  | _, _, .trans f g => coe β g ∘ coe β f
  | _, _, .tensor f g => fun p => (coe β f p.1, coe β g p.2)
  | _, _, .coprod f g => Sum.map (coe β f) (coe β g)
  | _, _, .empty _ => PEmpty.elim
  | _, _, .unit _ => fun _ => PUnit.unit

/-- The model of the freely generated universe determined by `β`. -/
@[reducible] def typeModel (β : α → Type v) : TypeModel.{u, v} (LambdaIter.Ty α) where
  interp := interp β
  tensorEquiv _ _ := Equiv.refl _
  unitEquiv := ⟨fun _ => (), fun _ => PUnit.unit, fun _ => rfl, fun _ => rfl⟩
  coprodEquiv _ _ := Equiv.refl _
  emptyEquiv := ⟨PEmpty.elim, Empty.elim, fun x => x.elim, fun x => x.elim⟩
  coe := coe β

/-- The free model is coherent: every operation of the `Subtyping` interface
receives its expected semantics. -/
theorem lawfulTypeModel (β : α → Type v) :
    @LawfulTypeModel (LambdaIter.Ty α) _ _ (typeModel β) :=
  letI := typeModel β
  { coe_refl := fun _ => rfl
    coe_trans := fun _ _ => rfl
    coe_tensor := fun _ _ _ => rfl
    coe_coprod := fun _ _ _ => rfl
    coe_empty := fun _ z => z.elim
    coe_unit := fun _ _ => rfl }

end Free

end Isotope.LambdaIter.Subtyping.Semantics
