import Isotope.LambdaIter.Subtyping.Semantics.Models.Empty

/-!
# The null model: the empty signature at a two-element effect set

This file used to be an ad-hoc copy of the empty base-type set and the empty
instruction set.  Both are now first-class
(`Isotope.LambdaIter.Signature.Empty`), and what remains here is the *named
example* that motivated them, re-derived from the general construction:

* `NullTy` is `EmptyTy`, the universe generated by `1`, `0`, `⊗`, `⊕` alone;
* `NullInstr` is `EmptyInstr`, the instruction set with no instructions;
* the effect set is `Eff`, the two-element lattice with `⊥ = Eff.pure`.

The effect set is the one place where `Null` differs from the empty signature
proper.  `EmptyEff` is `PUnit`, the *initial* pointed effect set; `Eff` has two
elements, so a `⊥`-preserving map out of it is not unique and `Eff` is **not**
initial.  Keeping both is deliberate: `Eff` is what the concrete `BitVec` and
`Nat` models annotate their instructions with, and `EmptyEff` is what makes the
empty signature initial among signatures.

It is not vacuous: `NullTy` has infinitely many inhabited types — the finite
types built from `1` and `⊕` — so `bool := 1 ⊕ 1` and every finite type lives
here.  What is absent is *base* types, not types.
-/

namespace Isotope.LambdaIter.Subtyping.Semantics

universe v

/-- A minimal two-element effect lattice: `pure` is the bottom. -/
inductive Eff : Type where
  | pure
  | impure
  deriving DecidableEq, Repr

namespace Eff

instance : Bot Eff := ⟨Eff.pure⟩

@[simp] theorem bot_eq : (⊥ : Eff) = Eff.pure := rfl

/-- `Eff` is **not** the initial pointed effect set: it has a second element,
so a bottom-preserving map out of it is not determined.  This is why the empty
signature uses `EmptyEff = PUnit` instead. -/
theorem impure_ne_bot : Eff.impure ≠ (⊥ : Eff) := by decide

end Eff

namespace Null

/-- The type universe with no base types: the empty signature's universe. -/
abbrev NullTy : Type := LambdaIter.EmptyTy.{0}

/-- The empty instruction signature. -/
abbrev NullInstr : Type := LambdaIter.EmptyInstr.{0}

/-- Instruction typing is inherited from the empty signature. -/
example : LambdaIter.HasTy NullInstr NullTy := inferInstance

/-- The null model annotates instructions with the two-element effect lattice
rather than with `EmptyEff`; vacuously, since there are no instructions. -/
instance : LambdaIter.HasEff NullInstr Eff where
  eff := PEmpty.elim

/-- The set-valued type model is the empty signature's, from
`Models/Free.lean`. -/
example : TypeModel.{0, v} NullTy := inferInstance

/-- Lawfulness likewise. -/
example : LawfulTypeModel.{0, v} NullTy := inferInstance

/-- Every monad models the empty instruction signature at the two-element
effect set, vacuously.  This is `emptyInstructionModel` at `ε := Eff`. -/
example (m : Type v → Type v) [Pure m] : InstructionModel NullInstr NullTy Eff m :=
  inferInstance

/-! ### The universe is not vacuous -/

/-- The booleans, as a type of the null universe. -/
abbrev boolTy : NullTy := LambdaIter.EmptyTy.boolTy.{0}

/-- The interpretation of the (empty) base types of the null universe. -/
@[reducible] def nullBase : LambdaIter.EmptyBase.{0} → Type := fun a => a.elim

/-- `bool` denotes a two-element type. -/
def boolEquiv : Free.interp nullBase boolTy ≃ Bool where
  toFun := Sum.elim (fun _ => false) (fun _ => true)
  invFun b := if b then .inr PUnit.unit else .inl PUnit.unit
  left_inv := by rintro (⟨⟩ | ⟨⟩) <;> rfl
  right_inv := by rintro (_ | _) <;> rfl

/-- **Every type of the null universe denotes a finite type.**  This is what
makes the null universe the "finite" fragment, and it is the obstruction that
separates it from the natural-number model. -/
instance fintypeInterp : (A : NullTy) → Fintype (Free.interp nullBase A)
  | .base a => a.elim
  | .tensor A B =>
      letI := fintypeInterp A
      letI := fintypeInterp B
      inferInstanceAs (Fintype (_ × _))
  | .unit => inferInstanceAs (Fintype PUnit)
  | .coprod A B =>
      letI := fintypeInterp A
      letI := fintypeInterp B
      inferInstanceAs (Fintype (_ ⊕ _))
  | .empty => inferInstanceAs (Fintype PEmpty)

/-- Iterated tensor: `pow A n` is `A` tensored with itself `n` times. -/
abbrev pow (A : NullTy) (n : Nat) : NullTy := LambdaIter.EmptyTy.pow A n

@[simp] theorem pow_zero (A : NullTy) : pow A 0 = .unit := rfl

@[simp] theorem pow_succ (A : NullTy) (n : Nat) :
    pow A (n + 1) = .tensor A (pow A n) := rfl

end Null

end Isotope.LambdaIter.Subtyping.Semantics
