import Isotope.LambdaIter.Subtyping.Semantics.Models.Free

/-!
# The null model: no base types, no instructions

`NullTy := Ty Empty` is the type universe generated by `unit`, `empty`,
tensor and coproduct alone, and `NullInstr := Empty` is the empty instruction
signature.  This is the smallest thing that satisfies every interface the
denotational semantics asks for, and it is the base case against which the
richer models are compared.

It is not vacuous: `NullTy` has infinitely many inhabited types — the finite
types built from `1` and `+` — so `bool := 1 ⊕ 1` and every finite type lives
here.  What is absent is *base* types, not types.

Effects are the two-element lattice `Eff`, whose bottom is `Eff.pure`; with no
instructions the effect assignment is vacuous, but the instance is still
required by `HasEff` and `Bot`.
-/

namespace Isotope.LambdaIter.Subtyping.Semantics

universe v

/-- A minimal two-element effect lattice: `pure` is the bottom. -/
inductive Eff : Type where
  | pure
  | impure
  deriving DecidableEq, Repr

namespace Eff

instance : Bot Eff := ⟨Eff.pure⟩

@[simp] theorem bot_eq : (⊥ : Eff) = Eff.pure := rfl

end Eff

namespace Null

/-- The type universe with no base types. -/
abbrev NullTy : Type := LambdaIter.Ty Empty

/-- The empty instruction signature. -/
abbrev NullInstr : Type := Empty

instance : LambdaIter.HasTy NullInstr NullTy where
  src := Empty.elim
  trg := Empty.elim

instance : LambdaIter.HasEff NullInstr Eff where
  eff := Empty.elim

/-- The interpretation of the null universe: base types are interpreted by the
empty family, which has no instances to supply. -/
@[reducible] def typeModel : TypeModel.{0, v} NullTy :=
  Free.typeModel (fun (a : Empty) => a.elim)

attribute [instance] typeModel

instance : LawfulTypeModel.{0, v} NullTy := Free.lawfulTypeModel _

/-- Every monad models the empty instruction signature, vacuously. -/
instance instructionModel (m : Type v → Type v) [Pure m] :
    InstructionModel NullInstr NullTy Eff m where
  denote f := f.elim
  denotePure f := f.elim
  denote_pure f := f.elim

/-! ### The universe is not vacuous -/

/-- The booleans, as a type of the null universe. -/
abbrev boolTy : NullTy := .coprod .unit .unit

/-- `bool` denotes a two-element type. -/
def boolEquiv : Free.interp (fun (a : Empty) => a.elim) boolTy ≃ Bool where
  toFun := Sum.elim (fun _ => false) (fun _ => true)
  invFun b := if b then .inr PUnit.unit else .inl PUnit.unit
  left_inv := by rintro (⟨⟩ | ⟨⟩) <;> rfl
  right_inv := by rintro (_ | _) <;> rfl

/-- The interpretation of the (empty) base types of the null universe. -/
@[reducible] def nullBase : Empty → Type := fun a => a.elim

/-- **Every type of the null universe denotes a finite type.**  This is what
makes the null universe the "finite" fragment, and it is the obstruction that
separates it from the natural-number model. -/
instance fintypeInterp : (A : NullTy) → Fintype (Free.interp nullBase A)
  | .base a => a.elim
  | .tensor A B =>
      letI := fintypeInterp A
      letI := fintypeInterp B
      inferInstanceAs (Fintype (_ × _))
  | .unit => inferInstanceAs (Fintype PUnit)
  | .coprod A B =>
      letI := fintypeInterp A
      letI := fintypeInterp B
      inferInstanceAs (Fintype (_ ⊕ _))
  | .empty => inferInstanceAs (Fintype PEmpty)

/-- Iterated tensor: `pow A n` is `A` tensored with itself `n` times. -/
def pow (A : NullTy) : Nat → NullTy
  | 0 => .unit
  | n + 1 => .tensor A (pow A n)

@[simp] theorem pow_zero (A : NullTy) : pow A 0 = .unit := rfl

@[simp] theorem pow_succ (A : NullTy) (n : Nat) :
    pow A (n + 1) = .tensor A (pow A n) := rfl

end Null

end Isotope.LambdaIter.Subtyping.Semantics
