// Notation for the λ_iter expression language.
//
// Mirrors the surface syntax used in the paper (the `\let`, `\case`, `\iter`,
// injection, abort, and quantity macros). Kept in one place so the rendering
// of every λ_iter term can be tweaked from here.

// Keyword styling: sans-serif, matching `\ms{...}` from the paper.
#let kw(name) = $sans(#name)$

// --- Types ---
#let tyunit = $bold(1)$   // unit type
#let tyempty = $bold(0)$  // empty type
#let tytensor = $⊗$       // tensor product
#let tysum = $+$          // coproduct

// --- Expressions ---

// Coproduct injections: ι_l a and ι_r b.
#let linl(a) = $iota_l med #a$
#let linr(b) = $iota_r med #b$

// Abort (eliminator of the empty type): abort a.
#let labort(a) = $#kw("abort") med #a$

// The arrow separating a pattern from a branch body. In the paper `\lto` is
// rendered as a colon; isolate it here so it is easy to change.
#let lto = $:$

// Let-binding: let x = a; b. The binder `x` may itself be a pattern, e.g.
// `(x, y)`, so this covers both ordinary and destructuring lets.
#let seq = $\; med$
#let letx(x, a, b) = $#kw("let") med #x = #a seq #b$

// Case-expression: case e { ι_l x : a, ι_r y : b }.
#let casex(e, x, a, y, b) = $#kw("case") med #e med {linl(#x) lto #a, linr(#y) lto #b}$

// Iteration: iter a { ι_r x : b } -- a tail-controlled loop.
#let iterx(a, x, b) = $#kw("iter") med #a med {linr(#x) lto #b}$

// --- Instructions ---
// Source and target of an instruction f ∈ I, and the typing f : A → B that
// they induce.
#let isrc(f) = $sans("src")(#f)$
#let itrg(f) = $sans("trg")(#f)$
#let instty(f, a, b) = $#f : #a -> #b$

// --- Subtyping & weakening ---
// Subtyping A <: B, freely generated by the base-type order, tensor, and
// coproduct, with 0 initial and 1 terminal.
#let subty(a, b) = $#a <: #b$
// Context weakening Γ ⊑ Δ: Γ weakens to Δ by dropping unshadowed variables
// and relaxing types along subtyping.
#let wkns(g, d) = $#g ⊑ #d$

// --- Substitution ---
// Substitution typing Γ ⊢ σ ▷ Δ: σ maps the variables of Δ to terms over Γ.
#let issub(g, s, d) = $#g ⊢ #s ▷ #d$
// Substitute a variable x with a term a in a term b: [a/x]b
#let subvar(a, x, b) = $[#a slash #x] #b$
// Action [σ]a of a substitution σ on a term a.
#let subap(s, a) = $[#s] #a$
// Extend a substitution σ with a new mapping x ↦ a: (σ, x ↦ a).
#let subcons(s, x, a) = $(#s, #x ↦ #a)$

// --- Equational theory ---
#let eqat(ctx, exp1, exp2, ty) = $ctx ⊢ exp1 ≈ exp2 : ty$

// --- Effects ---
// The lattice E of effects, with ⊥ the pure effect and ⊤ the unrestricted one.
#let effs = $cal(E)$
#let effpure = $⊥$
#let efftop = $⊤$
// The effect of an instruction f.
#let ieff(f) = $sans("eff")(#f)$
// The monotone operator E → E giving the effect of iterating an effect.
#let effiter(e) = $attach(#e, tr: ↺)$
// Effectful typing Γ ⊢_ε a : A. The effect rides the bottom-right corner of
// the turnstile (via `attach`) rather than tucking under it as a subscript.
#let hastye(g, e, a, ty) = $#g attach(⊢, br: #e) #a : #ty$
// Effectful instruction typing f : A →_ε B, effect on the arrow's bottom-right.
#let insttye(f, a, e, b) = $#f : #a attach(->, br: #e) #b$

// --- Quantities ---
// The join-semilattice of usage quantities Q^0 = {0, 1, 1^?, ω^+, ω}.
#let zeroq = $0$        // used zero times
#let oneq = $1$         // used exactly once
#let delq = $1^?$       // used at most once (0 ⊔ 1)
#let cpyq = $omega^+$   // used one or more times
#let topq = $omega$     // used any number of times
