#import "/lib/prelude.typ": *
#show: chapter.with(title: "Iteration Expressions")

SSA is a useful IR because it enables complex, 
whole-procedure transformation of code, 
but its block-statement-value hierarchy 
makes it difficult to uniformly formulate the allowed transformations 
as an (in)equational theory. 
Instead, therefore, we will start by studying a simple, 
first-order language of expressions, 
#liter,
equipped with an _iteration operator_
--
we will then show that this language is _equivalent_ to SSA,
and therefore we'll be able to use it as a tool to more effectively
give a sound and complete equational, and later refinement, theory for SSA.

= Syntax

#liter is a standard first-order expression language with branching and
iteration: a functional analogue of #msc[Imp]~@winskel1993.
Its grammar is parametrized by a set of _base types_ $X ∈ cal(X)$
and a set of _instructions_ $f ∈ cal(I)$.
To model multiple arguments and control flow,
our grammar of types $A, B, C$ includes all _tensor products_ $A tytensor B$
and _coproducts_ $A tysum B$ generated by base types $X$,
along with a _unit type_ $tyunit$ and an _empty type_ $tyempty$.
Mirroring this, expressions $a, b, c$ consist of

- _Variables_ $x, y, z$

- _Applications_ $f med a$, consisting of instructions $f ∈ cal(I)$
  applied to an expression $a$

- _Pairs_ $(a, b)$ and the unique empty tuple $()$ (_nil_).

- _Let-bindings_ $#letx($x$, $a$, $b$)$ 
  and _destructuring let-bindings_ $#letx($(x, y)$, $a$, $b$)$. 
  
  We write $a seq b$ as syntactic sugar for
  $#letx($·$, $a$, $b$)$ 
  (i.e., a let-binding where the bound variable is not used in $b$).

- _Case-expressions_ $#casex($e$, $x$, $a$, $y$, $b$)$,
  representing branching control-flow

- _Iteration-expressions_ $#iterx($a$, $x$, $b$)$, representing a variant of
  _tail-controlled loop_, which:

  - Evaluates an initial value $a : A$

  - Evaluates the loop body $b : B tysum A$ with $x = a$;
    if the loop evaluates to a value of type $B$, we return it,
    otherwise, we re-evaluate the loop with $x$ having the new value of type $A$

We give the full grammar for #liter types, expressions, and
contexts in @fig-expr-syntax.

#figure(
  grammar(
    production($A, B, C$,
      $X$, $A tytensor B$, $tyunit$, $A tysum B$, $tyempty$,
    ),
    production($a, b, c$,
      $x$,
      $f med a$,
      letx($x$, $a$, $b$),
      linebreak(),
      $()$,
      $(a, b)$,
      letx($(x, y)$, $a$, $b$),
      linebreak(),
      linl($a$),
      linr($b$),
      casex($a$, $x$, $b$, $y$, $c$),
      labort($a$),
      iterx($a$, $x$, $b$),
    ),
    production($Γ$, $·$, cond($Γ, x : A$, $x ∉ Γ$)),
  ),
  caption: [Syntax for #liter types, expressions, and contexts.],
) <fig-expr-syntax>

This language is intentionally very minimal -- in particular:

- We interpret constants $c$ as syntactic sugar for applications $c med ()$

- We interpret $n$-ary tuples $(a, b, c)$
  as syntactic sugar for left-associative nested pairs $((a, b), c)$
  -- likewise, we interpret an $n$-ary destructure
  $
    #letx($(x_1, x_2, x_3)$, $a$, $b$)
  $
  as syntactic sugar for left-associative nested destructures
  $
    #letx($(x_(12), x_3)$, $a$, 
      letx($(x_1, x_2)$, $x_(12)$, $b$)
    )
  $

#todo[
  Add note about locally-nameless syntax
]

== Typing

Our typing judgement is #hasty($Γ$, $a$, $A$),
read "in the context $Γ$, the expression $a$ has type $A$".
The rules, given in @fig-expr-typing, are _syntax-directed_:
there is one rule for each production in our grammar.
As before, we work over a fixed _signature_ consisting of: 

- A fixed set of _base types_ $X ∈ cal(X)$, 
  equipped with a partial order $subty(X, Y)$

- A fixed set of _instructions_ $f ∈ cal(I)$, 
  each of which has a _source type_ $isrc(f)$ and a _target type_ $itrg(f)$

To state our typing rules, we rely on two auxiliary judgements: 
_subtyping_ #subty($A$, $B$) 
and _weakening_ #wkns($Γ$, $Δ$).
In particular, the subtyping relation from the order on base types $X$ by:

- Taking the empty type $tyempty$ as the bottom element of the order
  -- i.e., as a subtype of all types

- Taking the unit type $tyunit$ as the top element of the order
  -- i.e., as a supertype of all types

- Defining subtyping on products and coproducts pointwise

_Weakening_ is then defined as partial order on typing contexts generated by:

- Weakening individual types (see: #msc[cons])

- Adding new variables of an arbitrary type to the context (see: #msc[drop])

We give these rules, along with our typing rules, in @fig-expr-typing.
In particular:

- #msc[var] looks up a variable's type in the context.

- #msc[op] applies an instruction $f$ to an argument, using the
  instruction's signature given by #msc[inst]
  --
  we note instructions are _contravariant_ in the source type 
  (i.e. if $f$ accepts an $A$ and $subty(A', A)$ then $f$ accepts an $A'$)
  and _covariant_ in the target type
  (i.e. if $f$ returns a $B$ and $subty(B, B')$, 
    then $f$'s return value may be interpreted as a $B'$)

- #msc[let] and #msc[let-pair] bind the result of $a$
  --
  either to a single variable or, by destructuring, to a pair of variables
  --
  in the body.

- #msc[unit] and #msc[pair] introduce the unit and tensor product;
  #msc[let-pair] eliminates the latter.

- #msc[inl], #msc[inr], and #msc[case] introduce and
  eliminate the coproduct, while #msc[abort] eliminates the empty type.

- #msc[iter] types a tail-controlled loop: the body $b$ is evaluated with
  $x$ bound to the current value of type $A$, and either returns a final value
  of type $B$ or a new value of type $A$ to loop with.

#let s-base = rule(
  label: msc("base"),
  $X ≤ Y$,
  subty($X$, $Y$),
)
#let s-tensor = rule(
  label: msc("tensor"),
  subty($A$, $A'$), subty($B$, $B'$),
  subty($A tytensor B$, $A' tytensor B'$),
)
#let s-sum = rule(
  label: msc("sum"),
  subty($A$, $A'$), subty($B$, $B'$),
  subty($A tysum B$, $A' tysum B'$),
)
#let s-initial = rule(
  label: msc("initial"),
  subty($tyempty$, $A$),
)
#let s-terminal = rule(
  label: msc("terminal"),
  subty($A$, $tyunit$),
)

#let w-nil = rule(
  label: msc("nil"),
  wkns($·$, $·$),
)
#let w-cons = rule(
  label: msc("cons"),
  wkns($Γ$, $Δ$), subty($A$, $B$),
  wkns($Γ, x : A$, $Δ, x : B$),
)
#let w-drop = rule(
  label: msc("drop"),
  wkns($Γ$, $Δ$),
  wkns($Γ, x : A$, $Δ$),
)

#let t-var = rule(
  label: msc("var"),
  wkns($Γ$, $x : A$),
  hasty($Γ$, $x$, $A$),
)
#let t-inst = rule(
  label: msc("inst"),
  $f ∈ cal(I)$, $subty(A, isrc(f))$, $subty(itrg(f), B)$,
  instty($f$, $A$, $B$),
)
#let t-op = rule(
  label: msc("op"),
  instty($f$, $A$, $B$), hasty($Γ$, $a$, $A$),
  hasty($Γ$, $f med a$, $B$),
)
#let t-let = rule(
  label: msc("let"),
  hasty($Γ$, $a$, $A$), hasty($Γ, x : A$, $b$, $B$),
  hasty($Γ$, letx($x$, $a$, $b$), $B$),
)
#let t-unit = rule(
  label: msc("unit"),
  hasty($Γ$, $()$, $tyunit$),
)
#let t-pair = rule(
  label: msc("pair"),
  hasty($Γ$, $a$, $A$), hasty($Γ$, $b$, $B$),
  hasty($Γ$, $(a, b)$, $A tytensor B$),
)
#let t-let-pair = rule(
  label: msc("let-pair"),
  hasty($Γ$, $a$, $A tytensor B$), hasty($Γ, x : A, y : B$, $c$, $C$),
  hasty($Γ$, letx($(x, y)$, $a$, $c$), $C$),
)
#let t-inl = rule(
  label: msc("inl"),
  hasty($Γ$, $a$, $A$),
  hasty($Γ$, linl($a$), $A tysum B$),
)
#let t-inr = rule(
  label: msc("inr"),
  hasty($Γ$, $b$, $B$),
  hasty($Γ$, linr($b$), $A tysum B$),
)
#let t-abort = rule(
  label: msc("abort"),
  hasty($Γ$, $a$, $tyempty$),
  hasty($Γ$, labort($a$), $C$),
)
#let t-case = rule(
  label: msc("case"),
  hasty($Γ$, $e$, $A tysum B$),
  hasty($Γ, x : A$, $a$, $C$),
  hasty($Γ, y : B$, $b$, $C$),
  hasty($Γ$, casex($e$, $x$, $a$, $y$, $b$), $C$),
)
#let t-iter = rule(
  label: msc("iter"),
  hasty($Γ$, $a$, $A$),
  hasty($Γ, x : A$, $b$, $B tysum A$),
  hasty($Γ$, iterx($a$, $x$, $b$), $B$),
)

#figure(
  stack(
    spacing: 1.5em,
    rule-set(
      prooftree(s-base),
      prooftree(s-tensor),
      prooftree(s-sum),
      prooftree(s-initial),
      prooftree(s-terminal),
    ),
    rule-set(
      prooftree(w-nil),
      prooftree(w-cons),
      prooftree(w-drop),
    ),
    rule-set(
      prooftree(t-var),
      prooftree(t-inst),
      prooftree(t-op),
      prooftree(t-let),
      prooftree(t-unit),
      prooftree(t-pair),
      prooftree(t-let-pair),
      prooftree(t-inl),
      prooftree(t-inr),
      prooftree(t-abort),
      prooftree(t-case),
      prooftree(t-iter),
    ),
  ),
  caption: [Typing rules for #liter, including subtyping and weakening.],
) <fig-expr-typing>

As a basic sanity check, we note that the rules given in @fig-expr-typing
satisfy _syntactic weakening_, as stated below: 

#lemma("Weakening")[
  If #wkns($Γ$, $Δ$), #subty($A$, $B$), and #hasty($Δ$, $a$, $A$),
  then #hasty($Γ$, $a$, $B$).
]

== Substitution

Recall that our high-level goal here is to develop a syntactic equational theory to reason about compiler optimizations on #liter -- that means, we want to be able to introduce a judgement

$
  #eqat($Γ$, $a_1$, $a_2$, $A$)
$

meaning that replacing $a_1$ with $a_2$ shouldn't change observable program behaviour.

In particular, this means that we want $a_1$ and $a_2$ to be indistinguishable in any _program context_ -- that is, we want, for all $#hasty($Γ, x : A$, $b$, $B$)$
$
  eqat(Γ, subvar(a_1, x, b), subvar(a_2, x, b), B)
$

where $subvar(a, x, b)$ denotes replacing all occurrences of $x$ in $b$ with $a$
--
i.e.,

#todo[improve segue here]

#rule-set(
  $subvar(a, x, x) = a$,
  $subvar(a, x, y) = y "where" x ≠ y$,
  $subvar(a, x, f med b) = f med subvar(a, x, b)$,
  $subvar(a, x, letx(x, b, c)) = letx(x, subvar(a, x, b), subvar(a, x, c))$,
  $subvar(a, x, letx((x, y), b, c)) 
    = letx((x, y), subvar(a, x, b), subvar(a, x, c))$,
  $subvar(a, x, ()) = ()$,
  $subvar(a, x, (b, c)) = (subvar(a, x, b), subvar(a, x, c))$,
  $subvar(a, x, linl(b)) = linl(subvar(a, x, b))$,
  $subvar(a, x, linr(b)) = linr(subvar(a, x, b))$,
  $subvar(a, x, casex(e, x, a, y, b)) 
    = casex(subvar(a, x, e), x, subvar(a, x, a), y, subvar(a, x, b))$,
  $subvar(a, x, labort(a)) = labort(subvar(a, x, a))$,
  $subvar(a, x, iterx(a, x, b)) = iterx(subvar(a, x, a), x, subvar(a, x, b))$,
)

#todo["both sides are well-typed"]

#todo[segue to _parallel_ substitution; rewrite below]

To be able to reason about algebraic rewrites, however,
we need to make sure that each side of the equation is at least _well-typed_
so that we can assign it a meaning at all, before worrying
about whether both sides have the _same_ meaning.

To this end, we require our calculus to satisfy _syntactic substitution_.
We begin by defining a _substition_ 
$issub(Γ, σ, Δ)$ as an ordered mapping from variables
$#wkns($Δ$, $x : A$)$ to well-typed values $hasty(Γ, a, A)$
-- as described in @fig-expr-subst.

#let sub-nil = rule(
  label: msc("nil"),
  issub($Γ$, $·$, $·$),
)
#let sub-cons = rule(
  label: msc("cons"),
  issub($Γ$, $σ$, $Δ$), hasty($Γ$, $a$, $A$), $x ∉ σ$,
  issub($Γ$, $σ, x ↦ a$, $Δ, x : A$),
)

#figure(
  rule-set(
    prooftree(sub-nil),
    prooftree(sub-cons),
  ),
  caption: [Substitution rules for #liter.],
) <fig-expr-subst>

We can then define substitution of #liter expressions as a 
partial function from pairs $σ, a$ to terms $subap(σ, a)$
in the usual manner as follows:

#rule-set(
  $subap(subcons(σ, x, a), x) = a$,
  $subap(subcons(σ, y, a), x) = subap(σ, x) "where" x ≠ y$,
  $subap(σ, f med a) = f med subap(σ, a)$,
  $subap(σ, letx(x, a, b)) = letx(x, subap(σ, a), subap(subcons(σ, x, x), b))$,
  $subap(σ, letx((x, y), a, b)) 
    = letx((x, y), subap(σ, a), subap(subcons(subcons(σ, x, x), y, y), b))$,
  $subap(σ, ()) = ()$,
  $subap(σ, (a, b)) = (subap(σ, a), subap(σ, b))$,
  $subap(σ, linl(a)) = linl(subap(σ, a))$,
  $subap(σ, linr(b)) = linr(subap(σ, b))$,
  $subap(σ, casex(e, x, a, y, b)) 
    = casex(subap(σ, e), x, subap(subcons(σ, x, x), a), y, subap(subcons(σ, y, y), b))$,
  $subap(σ, labort(a)) = labort(subap(σ, a))$,
  $subap(σ, iterx(a, x, b)) = iterx(subap(σ, a), x, subap(subcons(σ, x, x), b))$
)


We can then state _syntactic substition_ as usual:

#lemma("Substitution")[
  If #issub($Γ'$, $σ$, $Γ$) and #hasty($Γ$, $a$, $A$),
  then #hasty($Γ'$, subap($σ$, $a$), $A$).
]

== Effects

Syntactic substitution tells me that the term is _well-typed_...

#todo[We want to define congruence via substitution... doesn't work here]

#todo[Typical move: substitute a syntactic category of _values_/_constants_]

#todo[Instead: distinguish _pure_ vs. _impure_ expressions via _effect system_]

#todo[introduce the effect lattice #effs, with #effpure the pure effect and #efftop the unrestricted effect, ordered by $≤$ with joins $⊔$]

#todo[each instruction $f ∈ cal(I)$ carries an effect #ieff($f$); the effectful judgement #hastye($Γ$, $ε$, $a$, $A$) bounds the effects of $a$ above by $ε$, so pure constructors may be typed at any $ε$]

#todo[#effiter($ε$) is a monotone closure operator on #effs giving the effect of iterating an $ε$-effectful body: extensive ($ε ≤ effiter(ε)$) and idempotent ($effiter(effiter(ε)) = effiter(ε)$)]

#let te-var = rule(
  label: msc("var"),
  wkns($Γ$, $x : A$),
  hastye($Γ$, $ε$, $x$, $A$),
)
#let te-inst = rule(
  label: msc("inst"),
  $f ∈ cal(I)$, $isrc(f) = A$, $itrg(f) = B$, $ieff(f) ≤ ε$,
  insttye($f$, $A$, $ε$, $B$),
)
#let te-op = rule(
  label: msc("op"),
  insttye($f$, $A$, $ε$, $B$), hastye($Γ$, $ε$, $a$, $A$),
  hastye($Γ$, $ε$, $f med a$, $B$),
)
#let te-let = rule(
  label: msc("let"),
  hastye($Γ$, $ε$, $a$, $A$), hastye($Γ, x : A$, $ε$, $b$, $B$),
  hastye($Γ$, $ε$, letx($x$, $a$, $b$), $B$),
)
#let te-unit = rule(
  label: msc("unit"),
  hastye($Γ$, $ε$, $()$, $tyunit$),
)
#let te-pair = rule(
  label: msc("pair"),
  hastye($Γ$, $ε$, $a$, $A$), hastye($Γ$, $ε$, $b$, $B$),
  hastye($Γ$, $ε$, $(a, b)$, $A tytensor B$),
)
#let te-let-pair = rule(
  label: msc("let-pair"),
  hastye($Γ$, $ε$, $a$, $A tytensor B$), hastye($Γ, x : A, y : B$, $ε$, $c$, $C$),
  hastye($Γ$, $ε$, letx($(x, y)$, $a$, $c$), $C$),
)
#let te-inl = rule(
  label: msc("inl"),
  hastye($Γ$, $ε$, $a$, $A$),
  hastye($Γ$, $ε$, linl($a$), $A tysum B$),
)
#let te-inr = rule(
  label: msc("inr"),
  hastye($Γ$, $ε$, $b$, $B$),
  hastye($Γ$, $ε$, linr($b$), $A tysum B$),
)
#let te-abort = rule(
  label: msc("abort"),
  hastye($Γ$, $ε$, $a$, $tyempty$),
  hastye($Γ$, $ε$, labort($a$), $C$),
)
#let te-case = rule(
  label: msc("case"),
  hastye($Γ$, $ε$, $e$, $A tysum B$),
  hastye($Γ, x : A$, $ε$, $a$, $C$),
  hastye($Γ, y : B$, $ε$, $b$, $C$),
  hastye($Γ$, $ε$, casex($e$, $x$, $a$, $y$, $b$), $C$),
)
#let te-iter = rule(
  label: msc("iter"),
  hastye($Γ$, $ε$, $a$, $A$),
  hastye($Γ, x : A$, $ε$, $b$, $B tysum A$),
  hastye($Γ$, effiter($ε$), iterx($a$, $x$, $b$), $B$),
)

#figure(
  rule-set(
    prooftree(te-var),
    prooftree(te-inst),
    prooftree(te-op),
    prooftree(te-let),
    prooftree(te-unit),
    prooftree(te-pair),
    prooftree(te-let-pair),
    prooftree(te-inl),
    prooftree(te-inr),
    prooftree(te-abort),
    prooftree(te-case),
    prooftree(te-iter),
  ),
  caption: [Effectful typing rules for #liter.],
) <fig-expr-typing-eff>

== Equational Theory

#todo[give equational theory for #liter]

== Refinement Theory

#todo[give refinement theory for #liter]

= Semantics

== Interaction Trees

#todo[this]

== Monadic Semantics

#todo[this]

== Categorical Semantics

#todo[this]