#import "/lib/prelude.typ": *
#show: chapter.with(title: "Iteration Expressions")

SSA is a useful IR because it enables complex, 
whole-procedure transformation of code, 
but its block-statement-value hierarchy 
makes it difficult to uniformly formulate the allowed transformations 
as an (in)equational theory. 
Instead, therefore, we will start by studying a simple, 
first-order language of expressions, 
#liter,
equipped with an _iteration operator_
--
we will then show that this language is _equivalent_ to SSA,
and therefore we'll be able to use it as a tool to more effectively
give a sound and complete equational, and later refinement, theory for SSA.

== Syntax

#liter is a standard first-order expression language with branching and
iteration: a functional analogue of #smallcaps[While].
Its grammar is parametrized by a set of _base types_ $X ∈ cal(X)$
and a set of _instructions_ $f ∈ cal(I)$.
To model multiple arguments and control flow,
our grammar of types $A, B, C$ includes all _tensor products_ $A tytensor B$
and _coproducts_ $A tysum B$ generated by base types $X$,
along with a _unit type_ $tyunit$ and an _empty type_ $tyempty$.
Mirroring this, expressions $a, b, c$ consist of

- _Variables_ $x, y, z$

- _Applications_ $f med a$, consisting of instructions $f ∈ cal(I)$
  applied to an expression $a$

- _Let-bindings_ $#letx($x$, $a$, $b$)$ and _destructuring let-bindings_
  $#letx($(x, y)$, $a$, $b$)$. We write $a; b$ as syntactic sugar for
  $#letx($·$, $a$, $b$)$ (i.e., a let-binding where the bound variable is not
  used in $b$).

- _Case-expressions_ $#casex($e$, $x$, $a$, $y$, $b$)$,
  representing branching control-flow

- _Iteration-expressions_ $#iterx($a$, $x$, $b$)$, representing a variant of
  _tail-controlled loop_, which:

  - Evaluates an initial value $a : A$

  - Evaluates the loop body $b : B tysum A$ with $x = a$;
    if the loop evaluates to a value of type $B$, we return it,
    otherwise, we re-evaluate the loop with $x$ having the new value of type $A$

We give the full grammar for #liter types, expressions, and
contexts in @fig-expr-syntax.

#figure(
  grammar(
    production($A, B, C$,
      $X$, $A tytensor B$, $tyunit$, $A tysum B$, $tyempty$,
    ),
    production($a, b, c$,
      $x$,
      $f med a$,
      letx($x$, $a$, $b$),
      $()$,
      $(a, b)$,
      letx($(x, y)$, $a$, $b$),
      linl($a$),
      linr($b$),
      casex($a$, $x$, $b$, $y$, $c$),
      labort($a$),
      iterx($a$, $x$, $b$),
    ),
    production($Γ$, $·$, $Γ, x : A$),
  ),
  caption: [Syntax for #liter types, expressions, and contexts.],
) <fig-expr-syntax>

We can then give typing rules for #liter as follows:
#todo[give raw typing rules]

#todo[weakening]

#todo[substitution]

#todo[]
