#import "/lib/prelude.typ": *
#show: chapter.with(title: "Iteration Expressions")

SSA is a useful IR because it enables complex, 
whole-procedure transformation of code, 
but its block-statement-value hierarchy 
makes it difficult to uniformly formulate the allowed transformations 
as an (in)equational theory. 
Instead, therefore, we will start by studying a simple, 
first-order language of expressions, 
#liter,
equipped with an _iteration operator_
--
we will then show that this language is _equivalent_ to SSA,
and therefore we'll be able to use it as a tool to more effectively
give a sound and complete equational, and later refinement, theory for SSA.

= Syntax

#liter is a standard first-order expression language with branching and
iteration: a functional analogue of #msc[Imp]~@winskel1993.
Its grammar is parametrized by a set of _base types_ $X ∈ cal(X)$
and a set of _instructions_ $f ∈ cal(I)$.
To model multiple arguments and control flow,
our grammar of types $A, B, C$ includes all _tensor products_ $A tytensor B$
and _coproducts_ $A tysum B$ generated by base types $X$,
along with a _unit type_ $tyunit$ and an _empty type_ $tyempty$.
Mirroring this, expressions $a, b, c$ consist of

- _Variables_ $x, y, z$

- _Applications_ $f med a$, consisting of instructions $f ∈ cal(I)$
  applied to an expression $a$

- _Let-bindings_ $#letx($x$, $a$, $b$)$ 
  and _destructuring let-bindings_ $#letx($(x, y)$, $a$, $b$)$. 
  
  We write $a seq b$ as syntactic sugar for
  $#letx($·$, $a$, $b$)$ 
  (i.e., a let-binding where the bound variable is not used in $b$).

- _Case-expressions_ $#casex($e$, $x$, $a$, $y$, $b$)$,
  representing branching control-flow

- _Iteration-expressions_ $#iterx($a$, $x$, $b$)$, representing a variant of
  _tail-controlled loop_, which:

  - Evaluates an initial value $a : A$

  - Evaluates the loop body $b : B tysum A$ with $x = a$;
    if the loop evaluates to a value of type $B$, we return it,
    otherwise, we re-evaluate the loop with $x$ having the new value of type $A$

We give the full grammar for #liter types, expressions, and
contexts in @fig-expr-syntax.

#figure(
  grammar(
    production($A, B, C$,
      $X$, $A tytensor B$, $tyunit$, $A tysum B$, $tyempty$,
    ),
    production($a, b, c$,
      $x$,
      $f med a$,
      letx($x$, $a$, $b$),
      linebreak(),
      $()$,
      $(a, b)$,
      letx($(x, y)$, $a$, $b$),
      linebreak(),
      linl($a$),
      linr($b$),
      casex($a$, $x$, $b$, $y$, $c$),
      labort($a$),
      iterx($a$, $x$, $b$),
    ),
    production($Γ$, $·$, cond($Γ, x : A$, $x ∉ Γ$)),
  ),
  caption: [Syntax for #liter types, expressions, and contexts.],
) <fig-expr-syntax>

#let s-base = rule(
  label: msc("base"),
  $X ≤ Y$,
  subty($X$, $Y$),
)
#let s-tensor = rule(
  label: msc("tensor"),
  subty($A$, $A'$), subty($B$, $B'$),
  subty($A tytensor B$, $A' tytensor B'$),
)
#let s-sum = rule(
  label: msc("sum"),
  subty($A$, $A'$), subty($B$, $B'$),
  subty($A tysum B$, $A' tysum B'$),
)
#let s-initial = rule(
  label: msc("initial"),
  subty($tyempty$, $A$),
)
#let s-terminal = rule(
  label: msc("terminal"),
  subty($A$, $tyunit$),
)

#let w-nil = rule(
  label: msc("nil"),
  wkns($·$, $·$),
)
#let w-cons = rule(
  label: msc("cons"),
  wkns($Γ$, $Δ$), subty($A$, $B$),
  wkns($Γ, x : A$, $Δ, x : B$),
)
#let w-drop = rule(
  label: msc("drop"),
  wkns($Γ$, $Δ$),
  wkns($Γ, x : A$, $Δ$),
)

== Typing

Our typing judgement is #hasty($Γ$, $a$, $A$),
read "in the context $Γ$, the expression $a$ has type $A$".
The rules, given in @fig-expr-typing, are _syntax-directed_:
there is one rule for each production in our grammar.
For now, we work over a fixed _signature_ assigning each instruction $f ∈ cal(I)$
a _source type_ $isrc(f)$ and a _target type_ $itrg(f)$:

- #msc[var] looks up a variable's type in the context.

- #msc[op] applies an instruction $f$ to an argument, using the
  instruction's signature given by #msc[inst].

- #msc[let] and #msc[let-pair] bind the result of $a$
  --
  either to a single variable or, by destructuring, to a pair of variables
  --
  in the body.

- #msc[unit] and #msc[pair] introduce the unit and tensor product;
  #msc[let-pair] eliminates the latter.

- #msc[inl], #msc[inr], and #msc[case] introduce and
  eliminate the coproduct, while #msc[abort] eliminates the empty type.

- #msc[iter] types a tail-controlled loop: the body $b$ is evaluated with
  $x$ bound to the current value of type $A$, and either returns a final value
  of type $B$ or a new value of type $A$ to loop with.

The typing rules rely on two auxiliary judgements, bundled into the same
figure: _subtyping_ #subty($A$, $B$) and _context weakening_ #wkns($Γ$, $Δ$).

#todo[subtyping: freely generated by the base-type partial order, tensor, and coproduct, with $tyempty$ initial and $tyunit$ terminal]

#todo[weakening: drop variables and relax types along subtyping (variables are assumed unique within a context, per the grammar's side condition, so there is no shadowing to worry about)]

#let t-var = rule(
  label: msc("var"),
  wkns($Γ$, $x : A$),
  hasty($Γ$, $x$, $A$),
)
#let t-inst = rule(
  label: msc("inst"),
  $f ∈ cal(I)$, $isrc(f) = A$, $itrg(f) = B$,
  instty($f$, $A$, $B$),
)
#let t-op = rule(
  label: msc("op"),
  instty($f$, $A$, $B$), hasty($Γ$, $a$, $A$),
  hasty($Γ$, $f med a$, $B$),
)
#let t-let = rule(
  label: msc("let"),
  hasty($Γ$, $a$, $A$), hasty($Γ, x : A$, $b$, $B$),
  hasty($Γ$, letx($x$, $a$, $b$), $B$),
)
#let t-unit = rule(
  label: msc("unit"),
  hasty($Γ$, $()$, $tyunit$),
)
#let t-pair = rule(
  label: msc("pair"),
  hasty($Γ$, $a$, $A$), hasty($Γ$, $b$, $B$),
  hasty($Γ$, $(a, b)$, $A tytensor B$),
)
#let t-let-pair = rule(
  label: msc("let-pair"),
  hasty($Γ$, $a$, $A tytensor B$), hasty($Γ, x : A, y : B$, $c$, $C$),
  hasty($Γ$, letx($(x, y)$, $a$, $c$), $C$),
)
#let t-inl = rule(
  label: msc("inl"),
  hasty($Γ$, $a$, $A$),
  hasty($Γ$, linl($a$), $A tysum B$),
)
#let t-inr = rule(
  label: msc("inr"),
  hasty($Γ$, $b$, $B$),
  hasty($Γ$, linr($b$), $A tysum B$),
)
#let t-abort = rule(
  label: msc("abort"),
  hasty($Γ$, $a$, $tyempty$),
  hasty($Γ$, labort($a$), $C$),
)
#let t-case = rule(
  label: msc("case"),
  hasty($Γ$, $e$, $A tysum B$),
  hasty($Γ, x : A$, $a$, $C$),
  hasty($Γ, y : B$, $b$, $C$),
  hasty($Γ$, casex($e$, $x$, $a$, $y$, $b$), $C$),
)
#let t-iter = rule(
  label: msc("iter"),
  hasty($Γ$, $a$, $A$),
  hasty($Γ, x : A$, $b$, $B tysum A$),
  hasty($Γ$, iterx($a$, $x$, $b$), $B$),
)

#figure(
  stack(
    spacing: 1.5em,
    rule-set(
      prooftree(s-base),
      prooftree(s-tensor),
      prooftree(s-sum),
      prooftree(s-initial),
      prooftree(s-terminal),
    ),
    rule-set(
      prooftree(w-nil),
      prooftree(w-cons),
      prooftree(w-drop),
    ),
    rule-set(
      prooftree(t-var),
      prooftree(t-inst),
      prooftree(t-op),
      prooftree(t-let),
      prooftree(t-unit),
      prooftree(t-pair),
      prooftree(t-let-pair),
      prooftree(t-inl),
      prooftree(t-inr),
      prooftree(t-abort),
      prooftree(t-case),
      prooftree(t-iter),
    ),
  ),
  caption: [Typing rules for #liter, including subtyping and weakening.],
) <fig-expr-typing>

== Syntactic Metatheory

#todo[explain weakening: it folds context weakening and subtyping on the result type into a single admissible rule]

#lemma("Weakening")[
  If #wkns($Γ$, $Δ$), #subty($A$, $B$), and #hasty($Δ$, $a$, $A$),
  then #hasty($Γ$, $a$, $B$).
]

#todo[explain the substitution typing judgement #issub($Γ$, $σ$, $Δ$): a substitution $σ$ assigns to each variable of $Δ$ a term well-typed over $Γ$]

#let sub-nil = rule(
  label: msc("nil"),
  issub($Γ$, $·$, $·$),
)
#let sub-cons = rule(
  label: msc("cons"),
  issub($Γ$, $σ$, $Δ$), hasty($Γ$, $a$, $A$), $x ∉ σ$,
  issub($Γ$, $σ, x ↦ a$, $Δ, x : A$),
)

#figure(
  rule-set(
    prooftree(sub-nil),
    prooftree(sub-cons),
  ),
  caption: [Substitution rules for #liter.],
) <fig-expr-subst>

#todo[the substitution defined here is *syntactic*, not *semantic*: it does not take side-effects into account, so substituting an effectful term for a variable used zero or many times may drop or duplicate its effects. It is sound only for pure terms, and must be revisited once effects are introduced.]

#lemma("Substitution")[
  If #issub($Γ'$, $σ$, $Γ$) and #hasty($Γ$, $a$, $A$),
  then #hasty($Γ'$, subap($σ$, $a$), $A$).
]

- Well typed

- But not semantically valid -- as it discards / duplicates effects

- Usual thing: restrict substitution to values 
  -- but we want to use substitution to do _algebraic_ reasoning inside a compiler

== Effects

#todo[introduce the effect lattice #effs, with #effpure the pure effect and #efftop the unrestricted effect, ordered by $≤$ with joins $⊔$]

#todo[each instruction $f ∈ cal(I)$ carries an effect #ieff($f$); the effectful judgement #hastye($Γ$, $ε$, $a$, $A$) bounds the effects of $a$ above by $ε$, so pure constructors may be typed at any $ε$]

#todo[#effiter($ε$) is a monotone closure operator on #effs giving the effect of iterating an $ε$-effectful body: extensive ($ε ≤ effiter(ε)$) and idempotent ($effiter(effiter(ε)) = effiter(ε)$)]

#let te-var = rule(
  label: msc("var"),
  wkns($Γ$, $x : A$),
  hastye($Γ$, $ε$, $x$, $A$),
)
#let te-inst = rule(
  label: msc("inst"),
  $f ∈ cal(I)$, $isrc(f) = A$, $itrg(f) = B$, $ieff(f) ≤ ε$,
  insttye($f$, $A$, $ε$, $B$),
)
#let te-op = rule(
  label: msc("op"),
  insttye($f$, $A$, $ε$, $B$), hastye($Γ$, $ε$, $a$, $A$),
  hastye($Γ$, $ε$, $f med a$, $B$),
)
#let te-let = rule(
  label: msc("let"),
  hastye($Γ$, $ε$, $a$, $A$), hastye($Γ, x : A$, $ε$, $b$, $B$),
  hastye($Γ$, $ε$, letx($x$, $a$, $b$), $B$),
)
#let te-unit = rule(
  label: msc("unit"),
  hastye($Γ$, $ε$, $()$, $tyunit$),
)
#let te-pair = rule(
  label: msc("pair"),
  hastye($Γ$, $ε$, $a$, $A$), hastye($Γ$, $ε$, $b$, $B$),
  hastye($Γ$, $ε$, $(a, b)$, $A tytensor B$),
)
#let te-let-pair = rule(
  label: msc("let-pair"),
  hastye($Γ$, $ε$, $a$, $A tytensor B$), hastye($Γ, x : A, y : B$, $ε$, $c$, $C$),
  hastye($Γ$, $ε$, letx($(x, y)$, $a$, $c$), $C$),
)
#let te-inl = rule(
  label: msc("inl"),
  hastye($Γ$, $ε$, $a$, $A$),
  hastye($Γ$, $ε$, linl($a$), $A tysum B$),
)
#let te-inr = rule(
  label: msc("inr"),
  hastye($Γ$, $ε$, $b$, $B$),
  hastye($Γ$, $ε$, linr($b$), $A tysum B$),
)
#let te-abort = rule(
  label: msc("abort"),
  hastye($Γ$, $ε$, $a$, $tyempty$),
  hastye($Γ$, $ε$, labort($a$), $C$),
)
#let te-case = rule(
  label: msc("case"),
  hastye($Γ$, $ε$, $e$, $A tysum B$),
  hastye($Γ, x : A$, $ε$, $a$, $C$),
  hastye($Γ, y : B$, $ε$, $b$, $C$),
  hastye($Γ$, $ε$, casex($e$, $x$, $a$, $y$, $b$), $C$),
)
#let te-iter = rule(
  label: msc("iter"),
  hastye($Γ$, $ε$, $a$, $A$),
  hastye($Γ, x : A$, $ε$, $b$, $B tysum A$),
  hastye($Γ$, effiter($ε$), iterx($a$, $x$, $b$), $B$),
)

#figure(
  rule-set(
    prooftree(te-var),
    prooftree(te-inst),
    prooftree(te-op),
    prooftree(te-let),
    prooftree(te-unit),
    prooftree(te-pair),
    prooftree(te-let-pair),
    prooftree(te-inl),
    prooftree(te-inr),
    prooftree(te-abort),
    prooftree(te-case),
    prooftree(te-iter),
  ),
  caption: [Effectful typing rules for #liter.],
) <fig-expr-typing-eff>
