// Mechanical transcription from:
// papers/isotope/complete-refinement-ssa.tex
// Repository commit: 9480278f2503902f0fa632d05d7f0c8faae893f3
// Section: Concrete Models
// Source lines: 2956--3204
// Conversion: prose preserved verbatim; LaTeX presentation translated mechanically to Typst.

#import "/lib/prelude.typ": *

= Concrete Models
<refall:concrete-models>
In this section, we sketch some concrete models. All the given models
have types with unrestricted linearity, and so we will write our typing
rules using #emph[un-annotated] contexts and variables $Gamma \, x : A$,
assuming every quantity annotation is $omega$.

== UB
<refall:ssec:ub>
The simplest model exercising all the features of our refinement
calculus is the language with nondeterminism, undefined behavior and
nontermination. We represent this using the monad
$sans(U B) #h(0em) A = cal(P)^(+) \( A union { oo } \) union { arrow.zigzag }$
over sets, with $oo$ a sentinel value for nontermination and
$arrow.zigzag$ for UB. Its ordering is the inclusion order on nonempty
sets $cal(P)^(+) \( A union { oo } \)$ extended with a top element
$arrow.zigzag$. (The full description of this model is in
Appendix~#todo[Cross-reference: `refall:apx:ub`.]) The monadic bind is:
$ arrow.zigzag upright(">>=")_(sans("UB")) f &= arrow.zigzag #h(2em)
  X upright(">>=")_(sans("UB")) f = {f a | a in X} quad upright("if ") forall a in X, f a != arrow.zigzag #h(2em)
  X upright(">>=")_(sans("UB")) f &= arrow.zigzag quad upright("otherwise") $
where we define $f #h(0em) oo = oo$. The Kleisli
category of $sans(U B)$ has the lattice of effects generated by the
nontermination effect $oo$, the UB effect $arrow.zigzag$, and the
nondeterminism effect $?$. In Figure~@refall:fig:ub-submonads, we give the
submonad for each effect, along with its linearity and commutativity
with other effects.

This model lets us interpret instructions
$arrow.zigzag_A : upright(bold(1)) arrow.r_arrow.zigzag A$ analogous to
LLVM's `unreachable` intrinsic. We write $arrow.zigzag$ as shorthand for
$arrow.zigzag_A #h(0em) \( \)$. This instruction lets us define
#emph[unsafe unwrap] operators $rho_l : A + B arrow.r_arrow.zigzag A$
and $rho_r : A + B arrow.r_arrow.zigzag B$ which take the other branch
to $arrow.zigzag$. These satisfy the usual rewrite rules for UB, some of
which are given in Figure~@refall:fig:ub-rewrites.

#figure([#block[
  minipage=1.1,scale=0.9

  #figure(
    align(center)[#table(
      columns: 10,
      align: (left,center,center,center,center,center,center,center,center,center,),
      [], [$oo$], [$arrow.zigzag$], [$?$], [$oo arrow.zigzag$], [$oo ?$], [$arrow.zigzag ?$], [$oo arrow.zigzag ?$], [$sans(q)^(+)$], [$sans(q)^(-)$],
      [$sans(U B)_oo \( A \, B \) approx A arrow.r B union { oo }$], [$harpoons.rtlb$], [$harpoon.lb$], [$harpoons.rtlb$], [$harpoon.lb$], [$harpoons.rtlb$], [$harpoon.lb$], [$harpoon.lb$], [$omega^(+)$], [$omega^(+)$],
      [$sans(U B)_arrow.zigzag \( A \, B \) approx A arrow.r B union { arrow.zigzag }$], [$harpoon.rt$], [$harpoons.rtlb$], [$harpoons.rtlb$], [$harpoon.rt$], [$harpoon.rt$], [$harpoons.rtlb$], [$harpoon.rt$], [$omega$], [$omega^(+)$],
      [$sans(U B)_(?) \( A \, B \) approx A arrow.r cal(P)^(+) \( B \)$], [$harpoons.rtlb$], [$harpoons.rtlb$], [$harpoons.rtlb$], [$harpoons.rtlb$], [$harpoons.rtlb$], [$harpoons.rtlb$], [$harpoons.rtlb$], [$1^(?)$], [$omega$],
      [$sans(U B)_(oo arrow.zigzag) \( A \, B \) approx A arrow.r B union { oo } union { arrow.zigzag }$], [$harpoon.rt$], [$harpoon.lb$], [$harpoons.rtlb$], [$dot.op$], [$harpoon.rt$], [$harpoon.lb$], [$dot.op$], [$omega^(+)$], [$omega^(+)$],
      [$sans(U B)_(oo ?) \( A \, B \) approx A arrow.r cal(P)^(+) \( B union { oo } \)$], [$harpoons.rtlb$], [$harpoon.lb$], [$harpoons.rtlb$], [$harpoon.lb$], [$harpoons.rtlb$], [$harpoon.lb$], [$harpoon.lb$], [$1$], [$omega^(+)$],
      [$sans(U B)_(arrow.zigzag ?) \( A \, B \) approx A arrow.r cal(P)^(+) \( B \) union { arrow.zigzag }$], [$harpoon.rt$], [$harpoons.rtlb$], [$harpoons.rtlb$], [$harpoon.rt$], [$harpoon.rt$], [$harpoons.rtlb$], [$harpoon.rt$], [$1$], [$omega^(+)$],
    )]
    , kind: table
    )

  ]],
  caption: [
    Submonads of $sans(U B)$, along with their commutativity information
    (i.e. whether they are a left or right mover w.r.t. other effects)
    and lineary information (given as positive and negative quantities
    $sans(q)^(+) \, sans(q)^(-) in sans(Q)$)
  ]
)
<refall:fig:ub-submonads>

#figure([#block[
#rule-set(
  prooftree(rule(label: msc("ub-then"), $Gamma \, x : A tack.r epsilon.alt b : B$, $Gamma tack.r sans(l e t) #h(0em) x = arrow.zigzag ; #h(0em) b approx arrow.zigzag : B$)),
  prooftree(rule(label: msc("ub-left"), $Gamma tack.r epsilon.alt a : A + B$, $Gamma \, x : A tack.r epsilon.alt c : C$, $Gamma tack.r sans(c a s e) #h(0em) a #h(0em) { iota_l #h(0em) x : c \, iota_r #h(0em) y : arrow.zigzag } approx sans(l e t) #h(0em) x = rho_l #h(0em) a ; #h(0em) c : C$)),
  prooftree(rule(label: msc("ub-right"), $Gamma tack.r epsilon.alt a : A + B$, $Gamma \, y : B tack.r epsilon.alt c : C$, $Gamma tack.r sans(c a s e) #h(0em) a #h(0em) { iota_l #h(0em) x : arrow.zigzag \, iota_r #h(0em) y : c } approx sans(l e t) #h(0em) y = rho_r #h(0em) a ; #h(0em) c : C$)),
)

  ]],
  caption: [
    Some of the usual rewrite rules for undefined behavior.
  ]
)
<refall:fig:ub-rewrites>

== Heaps
<refall:ssec:heaps>
We model a single-threaded heap as a finitely-supported function of type
$S := bb(N) harpoon.rt_(sans(f i n)) bb(N)$. Using the state transformer
on $sans(U B)$, we can define a heap monad
$sans(H e a p) #h(0em) A = S arrow.r sans(U B) #h(0em) \( A times S \)$,
with the natural pointwise partial order. (The full description of this
model is in Appendix~#todo[Cross-reference: `refall:apx:ub-st`.]) Our effect system is the bounded
lattice generated by
${ oo \, arrow.zigzag \, ? \, sans(r) \, sans(w) \, sans(a) }$, with
$sans(r) \, sans(w)$, and $sans(a)$ corresponding to "read", "write",
and "allocate" respectively. The new primitive operations are:

- $sans(l d) : sans(H e a p)_(sans(r) arrow.zigzag) \( bb(N) \, bb(N) \) := lambda p #h(0em) s . sans(i f) #h(0em) p in s #h(0em) sans(t h e n) #h(0em) sans(p u r e)_(sans(N D)) \( s #h(0em) p \, s \) #h(0em) sans(e l s e) #h(0em) arrow.zigzag$

- $sans(s t) : sans(H e a p)_(sans(w) arrow.zigzag) \( bb(N) ⊗ bb(N) \, upright(bold(1)) \) := lambda \( p \, x \) #h(0em) s . sans(i f) #h(0em) p in s #h(0em) sans(t h e n) #h(0em) sans(p u r e)_(sans(N D)) \( \( \) \, \[ p mapsto x \] s \) #h(0em) sans(e l s e) #h(0em) arrow.zigzag$

- $sans(m k) : sans(H e a p)_(sans(a) ?) \( bb(N) \, bb(N) \) := lambda x #h(0em) s . { \( p \, \[ p mapsto x \] s \) divides p in.not s }$

- $sans(r m) : sans(H e a p)_(sans(w) arrow.zigzag) \( bb(N) \, \( \) \) := lambda p . sans(i f) #h(0em) p in s #h(0em) sans(t h e n) #h(0em) s \\ p #h(0em) sans(e l s e) #h(0em) arrow.zigzag$

This model validates the usual properties of heaps (see
Figure~@refall:fig:heap-eqns), as well as that allocation is central, reads and
writes are relevant, and reads are eliminable and commutative.

#figure([#block[
#rule-set(
  prooftree(rule(label: msc("st-ld"), $Gamma tack.r tack.t p : bb(N)$, $Gamma tack.r tack.t a : bb(N)$, $Gamma tack.r sans(s t) #h(0em) \( p \, a \) ; sans(l d) #h(0em) p approx sans(s t) #h(0em) \( p \, a \) ; a : bb(N)$)),
  prooftree(rule(label: msc("mk-ld"), $Gamma tack.r tack.t a : bb(N)$, $Gamma tack.r sans(l e t) #h(0em) p = sans(m k) #h(0em) a ; #h(0em) \( p \, sans(l d) #h(0em) p \) approx \( sans(m k) #h(0em) a ; a \) : bb(N) ⊗ bb(N)$)),
  prooftree(rule(label: msc("st-st"), $Gamma tack.r tack.t p : bb(N)$, $Gamma tack.r tack.t a : bb(N)$, $Gamma tack.r tack.t b : bb(N)$, $Gamma tack.r sans(s t) #h(0em) \( p \, a \) ; sans(s t) #h(0em) \( p \, b \) approx sans(s t) #h(0em) \( p \, b \) : upright(bold(1))$)),
  prooftree(rule(label: msc("mk-st"), $Gamma tack.r tack.t a : bb(N)$, $Gamma tack.r tack.t b : bb(N)$, $Gamma tack.r sans(l e t) #h(0em) p = sans(m k) #h(0em) a ; #h(0em) sans(s t) #h(0em) \( p \, b \) ; p approx sans(m k #h(0em) b) : bb(N)$)),
  prooftree(rule(label: msc("mk-rm"), $Gamma tack.r tack.t a : bb(N)$, $Gamma tack.r sans(l e t) #h(0em) p = sans(m k) #h(0em) a ; #h(0em) sans(r m) #h(0em) p approx \( \) : upright(bold(1))$)),
  prooftree(rule(label: msc("st-rm"), $Gamma tack.r tack.t p : bb(N)$, $Gamma tack.r tack.t a : bb(N)$, $Gamma tack.r sans(s t) #h(0em) \( p \, a \) ; sans(r m) #h(0em) p approx sans(r m) #h(0em) p : upright(bold(1))$)),
)

  ]],
  caption: [
    Some properties of heaps
  ]
)
<refall:fig:heap-eqns>

== Concurrency
<refall:concurrency>
In Brookes's #cite(<brookes-full-abstraction-96>) concurrency semantics, a
memory effect is a trace consisting of a finite sequence of transitions
$⟨ mu \, rho ⟩$ between memory states $mu$ and $rho$. Traces
represent #emph[interrupted] program executions: a transition
$⟨ mu \, rho ⟩$ represents a single step in which the
program, #emph[relying on] a state $mu$ from the environment,
#emph[guarantees] it will return a state $rho$ to the environment. A
program's denotation is now a #emph[set] of pairs $xi therefore r$ of a
trace $xi$ and return value $r$. Each pair corresponds to a possible
execution of the program given potential interference (e.g., an external
thread reading and writing).

#cite(<brookes-full-abstraction-96>, form: "prose") observed that to
make a denotational model sound with respect to the operational
semantics, the traces need to satisfy certain #emph[closure properties].
Trace sets should be closed under "#emph[stuttering]" (adding
transitions of the form $⟨ mu \, mu ⟩$, corresponding to the
program doing nothing) and "#emph[mumbling]" (merging
$⟨ mu \, rho ⟩ ⟨ rho \, theta ⟩ arrow.r.twohead ⟨ mu \, theta ⟩$,
corresponding to the environment doing nothing).

By choosing appropriate state types, closure properties, and operations
on states, we can model a variety of memory models. In particular,
#cite(<release-acquire>, form: "prose") show how to define a monad
$cal(I) #h(0em) A = cal(P) \( { xi therefore r divides r in A } \)$,
which they use to guve a denotational semantics for release-acquire weak
memory. This monad has a poset-enriched Kleisli category under the usual
subset order, and can be equipped with an Elgot structure, which we show
how to do in Appendix~#todo[Cross-reference: `refall:apx:rel-acq`], hence giving us a
$lambda_(sans(i t e r))$-model.

Just like for heaps, we can define an effect lattice
${ sans(r) \, sans(w) \, oo }$, though for trace models reading is
#emph[not] commutative; similarly, we have instructions
$sans(l d) : bb(N) arrow.r_(sans(r)) bb(N)$ and
$sans(s t) : bb(N) ⊗ bb(N) arrow.r_(sans(w)) upright(bold(1))$,
as well as an atomic #emph[fetch-and-add] instruction
$sans(f a a) : bb(N) ⊗ bb(N) arrow.r_(sans(r w)) bb(N)$. We
may validate numerous refinements on memory operations in this model,
some of which we give in Figure~@refall:fig:weak-refinements. Note that all of
these are valid #emph[equalities] in the heap model given above. Both
the read and write effects are duplicable in this model, while the read
effect is not only eliminable, but also #emph[introducable], since we
do not have UB.

#figure([#block[
#rule-set(
  prooftree(rule(label: msc("st-ld"), $Gamma tack.r tack.t p : bb(N)$, $Gamma tack.r tack.t a : bb(N)$, $Gamma tack.r sans(s t) #h(0em) \( p \, a \) ; sans(l d) #h(0em) p arrow.r.twohead sans(s t) #h(0em) \( p \, a \) ; a : bb(N)$)),
  prooftree(rule(label: msc("st-st"), $Gamma tack.r tack.t p : bb(N)$, $Gamma tack.r tack.t a : bb(N)$, $Gamma tack.r tack.t b : bb(N)$, $Gamma tack.r sans(s t) #h(0em) \( p \, a \) ; sans(s t) #h(0em) \( p \, b \) arrow.r.twohead sans(s t) #h(0em) \( p \, b \) : upright(bold(1))$)),
  prooftree(rule(label: msc("ld-st"), $Gamma tack.r tack.t p : bb(N)$, $Gamma tack.r tack.t a : bb(N)$, $Gamma tack.r sans(l e t) #h(0em) x = sans(l d) #h(0em) p ; #h(0em) sans(s t) #h(0em) p #h(0em) \( x + a \) ; x arrow.r.twohead sans(f a a) #h(0em) \( p \, a \) : bb(N)$)),
)

  ]],
  caption: [
    Some refinements valid in the release-acquire
    $lambda_(sans(i t e r))$-model.
  ]
)
<refall:fig:weak-refinements>

#standalone-bibliography()
