import Isotope.LambdaIter.Models.Monadic.Coupling
import Isotope.LambdaIter.Signature.Initial
import Isotope.Elgot.Basic

/-!
# A concrete monadic model: the partiality monad over the empty signature

`Alg.ofSeqModel` and `Alg.ofModel` are only interesting if some instance of
them is not the terminal algebra.  This file supplies one, shared by the three
calculi: the freely generated type universe of the empty signature,
interpreted by the evident sets, with `Part` as the monad.

Since the empty signature has no instructions, the model is pure data about
types; the separation of terms comes from the carrier alone and would survive
replacing `Part` by any monad whose `pure` is injective.
-/

namespace Isotope.LambdaIter.Monadic

open Isotope.Elgot

/-- The evident set-valued interpretation of the type universe freely
generated by `1`, `0`, `⊗` and `⊕`. -/
def freeInterp : EmptyTy.{0} → Type
  | .base a => a.elim
  | .tensor A B => freeInterp A × freeInterp B
  | .unit => Unit
  | .coprod A B => freeInterp A ⊕ freeInterp B
  | .empty => Empty

/-- The partiality model of the empty signature. -/
def partModel : Model.{0, 0} Sig.empty.{0} Part where
  interp := freeInterp
  denoteInstr f := f.elim
  denotePureInstr f := f.elim
  denoteInstr_pure f := f.elim
  tensorEquiv _ _ := Equiv.refl _
  unitEquiv := Equiv.refl _
  coprodEquiv _ _ := Equiv.refl _
  emptyEquiv := Equiv.refl _

/-- The booleans of the empty type universe. -/
def boolTy : EmptyTy.{0} := .coprod .unit .unit

end Isotope.LambdaIter.Monadic
