import Isotope.Elgot.TraceSet.Laws
import Isotope.Elgot.TraceSet.Nondeterminism

/-!
# Worked examples

Finite termination, step-produced divergence, productive infinite iteration (whose
trace this model discards), nondeterministic choice, and a loop that may exit at
any iteration.
-/

namespace Isotope.Elgot

universe u

namespace TraceSet

variable {E T A B : Type u} [Monoid E] [MulAction E T]

/-- A body that returns immediately terminates with exactly that trace. -/
@[simp] theorem iter_immediate (a : A) (b : B) (e : E) :
    iter (fun _ : A ↦ ({Trace.done (Sum.inl b) e} : TraceSet E T (B ⊕ A))) a
      = {Trace.done b e} := by
  apply ext
  intro u
  rw [mem_singleton_iff]
  constructor
  · intro hr
    cases hr with
    | ret hs =>
        rw [mem_singleton_iff] at hs
        cases hs
        rfl
    | div hs => simp at hs
    | more hs _ => simp at hs
  · rintro rfl
    exact Runs.ret rfl

/-- A body that diverges outright keeps its infinite observation: this is
divergence *with* an observable trace, produced by a single step. -/
@[simp] theorem iter_diverging_step (a : A) (t : T) :
    iter (fun _ : A ↦ ({Trace.inf t} : TraceSet E T (B ⊕ A))) a = {Trace.inf t} := by
  apply ext
  intro u
  rw [mem_singleton_iff]
  constructor
  · intro hr
    cases hr with
    | ret hs => simp at hs
    | div hs =>
        rw [mem_singleton_iff] at hs
        cases hs
        rfl
    | more hs _ => simp at hs
  · rintro rfl
    exact Runs.div rfl

/-- A productive infinite loop contributes **no** trace: this model discards the
trace of divergence generated by infinitely many unfoldings. -/
@[simp] theorem iter_forever (a : A) (e : E) :
    iter (fun a' : A ↦ ({Trace.done (Sum.inr a') e} : TraceSet E T (B ⊕ A))) a
      = (∅ : TraceSet E T B) := by
  apply ext
  intro u
  constructor
  · intro hr
    induction hr with
    | ret hs => simp at hs
    | div hs => simp at hs
    | more _ _ ih => exact ih
  · intro hu
    exact hu.elim

/-- Nondeterministic choice between two immediate results is retained. -/
@[simp] theorem iter_choice (a : A) (b b' : B) (e e' : E) :
    iter (fun _ : A ↦
        ({Trace.done (Sum.inl b) e, Trace.done (Sum.inl b') e'} : TraceSet E T (B ⊕ A))) a
      = {Trace.done b e, Trace.done b' e'} := by
  apply ext
  intro u
  constructor
  · intro hr
    cases hr with
    | ret hs =>
        rw [mem_insert_iff] at hs
        rcases hs with hs | hs
        · cases hs
          exact Or.inl rfl
        · rw [mem_singleton_iff] at hs
          cases hs
          exact Or.inr rfl
    | div hs => rw [mem_insert_iff, mem_singleton_iff] at hs; simp at hs
    | more hs _ => rw [mem_insert_iff, mem_singleton_iff] at hs; simp at hs
  · intro hu
    rw [mem_insert_iff] at hu
    rcases hu with rfl | hu
    · exact Runs.ret (Or.inl rfl)
    · rw [mem_singleton_iff] at hu
      subst hu
      exact Runs.ret (Or.inr rfl)

/-- A loop that may either exit or go round again: the traces are exactly the
finite unrollings.  Nondeterminism turns one body into infinitely many traces. -/
theorem mem_iter_loop_or_exit (a : A) (b : B) (e e' : E) (u : Trace E T B) :
    u ∈ iter (fun a' : A ↦
        ({Trace.done (Sum.inl b) e, Trace.done (Sum.inr a') e'} : TraceSet E T (B ⊕ A))) a
      ↔ ∃ n : ℕ, u = Trace.done b (e' ^ n * e) := by
  constructor
  · intro hr
    induction hr with
    | ret hs =>
        rw [mem_insert_iff, mem_singleton_iff] at hs
        rcases hs with hs | hs
        · cases hs
          exact ⟨0, by simp⟩
        · simp at hs
    | div hs => rw [mem_insert_iff, mem_singleton_iff] at hs; simp at hs
    | more hs _ ih =>
        rw [mem_insert_iff, mem_singleton_iff] at hs
        rcases hs with hs | hs
        · simp at hs
        · cases hs
          rcases ih with ⟨n, rfl⟩
          exact ⟨n + 1, by simp [pow_succ', mul_assoc]⟩
  · rintro ⟨n, rfl⟩
    induction n with
    | zero => simpa using Runs.ret (Or.inl rfl)
    | succ n ih =>
        have hstep := Runs.more (Or.inr rfl) ih
        simpa [pow_succ', mul_assoc] using hstep

/-- Divergence whose trace is discarded is the **empty** trace set: the least
element for nondeterministic refinement, absorbed by any alternative behaviour.
It is therefore not an "undefined behaviour" element, which would absorb every
alternative instead. -/
theorem discarded_divergence_not_absorbing (a : A) (e : E) (x : TraceSet E T B) :
    iter (fun a' : A ↦ ({Trace.done (Sum.inr a') e} : TraceSet E T (B ⊕ A))) a ∪ x = x := by
  rw [iter_forever]
  exact empty_union x

end TraceSet

end Isotope.Elgot
