import Isotope.Elgot.TraceSet.Basic

/-!
# Finite-observation iteration on trace sets

Iteration is defined by an inductive `Runs` relation collecting every *finite*
unfolding of the body.  A run either returns (`Runs.ret`), hits a step that
itself diverges with an infinite observation (`Runs.div`), or recurses
(`Runs.more`), prepending that step's effect to the rest of the trace.

Traces generated by *infinitely many* unfoldings are **not** in the image of
`Runs`: this is the partial-correctness reading of iteration, in which a
productive infinite loop contributes no observation at all.  See the honest
boundary in `Isotope.Elgot.TraceSet`.

Only `Mul E` and `SMul E T` are needed to define iteration.
-/

namespace Isotope.Elgot

universe u

namespace TraceSet

variable {E T A B C : Type u}

/-- A finite unfolding of an iteration body: it returns, it hits a diverging
step, or it recurses, prepending the step's effect. -/
inductive Runs [Mul E] [SMul E T] (f : A → TraceSet E T (B ⊕ A)) : A → Trace E T B → Prop
  /-- The body returned a value. -/
  | ret {a b e} : Trace.done (Sum.inl b) e ∈ f a → Runs f a (Trace.done b e)
  /-- The body diverged outright, with an infinite observation. -/
  | div {a t} : Trace.inf t ∈ f a → Runs f a (Trace.inf t)
  /-- The body asked to recurse. -/
  | more {a a' e u} : Trace.done (Sum.inr a') e ∈ f a → Runs f a' u → Runs f a (e • u)

/-- The set of traces produced by finitely many unfoldings of `f`. -/
def iterate [Mul E] [SMul E T] (f : A → TraceSet E T (B ⊕ A)) (a : A) : TraceSet E T B :=
  ⟨{u | Runs f a u}⟩

instance instIterate [Mul E] [SMul E T] : Iterate (TraceSet E T) where
  iter := iterate

@[simp] theorem mem_iter_iff [Mul E] [SMul E T] (f : A → TraceSet E T (B ⊕ A)) (a : A)
    (u : Trace E T B) : u ∈ iter f a ↔ Runs f a u := Iff.rfl

/-- Iteration is monotone in the body. -/
theorem Runs.mono [Mul E] [SMul E T] {f g : A → TraceSet E T (B ⊕ A)} (h : ∀ a, f a ⊆ g a)
    {a : A} {u : Trace E T B} (hr : Runs f a u) : Runs g a u := by
  induction hr with
  | ret hs => exact .ret (h _ _ hs)
  | div hs => exact .div (h _ _ hs)
  | more hs _ ih => exact .more (h _ _ hs) ih

theorem iter_mono [Mul E] [SMul E T] {f g : A → TraceSet E T (B ⊕ A)} (h : ∀ a, f a ⊆ g a)
    (a : A) : iter f a ⊆ iter g a := fun _ hu ↦ hu.mono h

end TraceSet

end Isotope.Elgot
