import Isotope.CategoryTheory.AddMonoidal.Basic
import Isotope.CategoryTheory.AddMonoidal.Cocartesian
import Isotope.CategoryTheory.AddMonoidal.Types
import Isotope.CategoryTheory.AddMonoidal.Kleisli
import Isotope.CategoryTheory.AddMonoidal.Elgot
import Isotope.CategoryTheory.AddMonoidal.Examples
