import Isotope.LambdaIter.Ty

/-!
# The universal property of the freely generated type universe

`Ty α` is the type universe freely generated by the base types `α` under the
four type formers.  This file records the corresponding universal property:
an interpretation `f : α → τ` of the base types in any other universe with
type formers extends to `Ty α → τ` in exactly one former-preserving way.

This is the only content behind "the empty signature is initial": at
`α = PEmpty` there is exactly one `f`, hence exactly one extension.

## Shared-namespace note

`Ty.lift` and `Ty.lift_unique` live in the shared namespace
`Isotope.LambdaIter.Ty` and are deliberately stated in terms of the generic
`tensor`/`unit`/`coprod`/`empty` of `TypeFormers`, not the constructors of
`Ty`, so that they apply verbatim to the former-preservation fields of a
signature morphism.
-/

namespace Isotope.LambdaIter

universe u v

variable {α : Type u} {τ : Type v} [TypeFormers τ]

/-- The extension of an interpretation of base types to the freely generated
type universe: type formers go to type formers, base types go where `f`
sends them. -/
def Ty.lift (f : α → τ) : Ty α → τ
  | .base a => f a
  | .tensor A B => LambdaIter.tensor (Ty.lift f A) (Ty.lift f B)
  | .unit => LambdaIter.unit
  | .coprod A B => LambdaIter.coprod (Ty.lift f A) (Ty.lift f B)
  | .empty => LambdaIter.empty

@[simp] theorem Ty.lift_base (f : α → τ) (a : α) : Ty.lift f (.base a) = f a := rfl

@[simp] theorem Ty.lift_tensor (f : α → τ) (A B : Ty α) :
    Ty.lift f (LambdaIter.tensor A B) = LambdaIter.tensor (Ty.lift f A) (Ty.lift f B) := rfl

@[simp] theorem Ty.lift_unit (f : α → τ) :
    Ty.lift f (LambdaIter.unit : Ty α) = LambdaIter.unit := rfl

@[simp] theorem Ty.lift_coprod (f : α → τ) (A B : Ty α) :
    Ty.lift f (LambdaIter.coprod A B) = LambdaIter.coprod (Ty.lift f A) (Ty.lift f B) := rfl

@[simp] theorem Ty.lift_empty (f : α → τ) :
    Ty.lift f (LambdaIter.empty : Ty α) = LambdaIter.empty := rfl

/-- **Uniqueness.**  Any map out of `Ty α` that strictly preserves the four
type formers and agrees with `f` on base types *is* `Ty.lift f`. -/
theorem Ty.lift_unique {f : α → τ} {g : Ty α → τ}
    (hbase : ∀ a : α, g (.base a) = f a)
    (htensor : ∀ A B : Ty α,
      g (LambdaIter.tensor A B) = LambdaIter.tensor (g A) (g B))
    (hunit : g LambdaIter.unit = LambdaIter.unit)
    (hcoprod : ∀ A B : Ty α,
      g (LambdaIter.coprod A B) = LambdaIter.coprod (g A) (g B))
    (hempty : g LambdaIter.empty = LambdaIter.empty) : g = Ty.lift f := by
  funext A
  induction A with
  | base a => exact hbase a
  | tensor A B ihA ihB =>
      change g (LambdaIter.tensor A B) = _
      rw [htensor A B, ihA, ihB]; rfl
  | unit => exact hunit
  | coprod A B ihA ihB =>
      change g (LambdaIter.coprod A B) = _
      rw [hcoprod A B, ihA, ihB]; rfl
  | empty => exact hempty

/-- Two former-preserving maps out of `Ty α` that agree on base types are
equal. -/
theorem Ty.eq_of_forms {g h : Ty α → τ}
    (hgbase : ∀ a : α, g (.base a) = h (.base a))
    (hgtensor : ∀ A B : Ty α,
      g (LambdaIter.tensor A B) = LambdaIter.tensor (g A) (g B))
    (hgunit : g LambdaIter.unit = LambdaIter.unit)
    (hgcoprod : ∀ A B : Ty α,
      g (LambdaIter.coprod A B) = LambdaIter.coprod (g A) (g B))
    (hgempty : g LambdaIter.empty = LambdaIter.empty)
    (hhtensor : ∀ A B : Ty α,
      h (LambdaIter.tensor A B) = LambdaIter.tensor (h A) (h B))
    (hhunit : h LambdaIter.unit = LambdaIter.unit)
    (hhcoprod : ∀ A B : Ty α,
      h (LambdaIter.coprod A B) = LambdaIter.coprod (h A) (h B))
    (hhempty : h LambdaIter.empty = LambdaIter.empty) : g = h :=
  (Ty.lift_unique (f := fun a => h (.base a)) hgbase hgtensor hgunit hgcoprod
      hgempty).trans
    (Ty.lift_unique (f := fun a => h (.base a)) (fun _ => rfl) hhtensor hhunit
      hhcoprod hhempty).symm

end Isotope.LambdaIter
