import Isotope.LambdaSeq.Models.Monadic.Alg
import Isotope.LambdaIter.Signature.Initial

/-!
# A concrete lambda-seq algebra: the partiality monad over the empty signature

`Alg.ofSeqModel` is only interesting if some instance of it is not the terminal
algebra.  This file exhibits one: the free set-valued interpretation of the
empty signature's type universe, with the partiality monad `Part`, and two
bound variables whose denotations differ in it.

Since the empty signature has no instructions, the model uses no data beyond
the type interpretation; the separation comes from the carrier alone, and would
survive replacing `Part` by any monad whose `pure` is injective.
-/

namespace Isotope.LambdaSeq.Monadic

open LocallyNameless

open Isotope.LambdaIter (Sig EmptyTy EmptyInstr)
open Isotope.LambdaIter.Monadic
open Isotope.LambdaIter.Monadic.SeqModel

/-- The free set-valued interpretation of the type universe freely generated by
`1`, `0`, `⊗` and `⊕`. -/
def freeInterp : EmptyTy.{0} → Type
  | .base a => a.elim
  | .tensor A B => freeInterp A × freeInterp B
  | .unit => Unit
  | .coprod A B => freeInterp A ⊕ freeInterp B
  | .empty => Empty

/-- The partiality model of the empty signature: types denote their free
interpretation, and there is no instruction to interpret. -/
def partModel : SeqModel.{0, 0} Isotope.LambdaIter.Sig.empty.{0} Part where
  interp := freeInterp
  denoteInstr f := f.elim
  denotePureInstr f := f.elim
  denoteInstr_pure f := f.elim

/-- The booleans of the empty type universe. -/
def bool : EmptyTy.{0} := .coprod .unit .unit

/-- The two-slot bound context of booleans. -/
def boolPair : BoundCtx EmptyTy.{0} 2 := (.snoc (.snoc .nil bool) bool)

/-- **The partiality algebra of lambda-seq is not the terminal one**: the two
bound variables of `boolPair` have different denotations in it.  Hence
`Alg.ofSeqModel` produces algebras with genuine semantic content, and the two
variables are not identified by the lambda-seq equational theory. -/
theorem var_ne_var :
    (Alg.ofSeqModel partModel).var (β := boolPair) 0 ≠
      (Alg.ofSeqModel partModel).var (β := boolPair) 1 := by
  intro h
  have h' : (Part.some (Sum.inr () : Unit ⊕ Unit)) = Part.some (Sum.inl ()) :=
    congrArg
      (fun F => F (((PUnit.unit, Sum.inl ()), Sum.inr ()) :
        partModel.Env boolPair)) h
  have h2 : (Sum.inr () : Unit ⊕ Unit) = Sum.inl () :=
    _root_.Part.some_injective h'
  exact absurd h2 (by decide)

end Isotope.LambdaSeq.Monadic
