import Isotope.LambdaSeq.Typing
import Isotope.LambdaCase.Equiv
import Isotope.LambdaCase.Subtyping.Equiv

/-! # Equational theory of lambda-seq -/

namespace Isotope.LambdaSeq

namespace Named

def Eqv [DecidableEq ν] [LambdaIter.TypeFormers τ]
    [LambdaIter.HasTy Φ τ] [LambdaIter.HasEff Φ ε] (pureEff : ε)
    (Γ : Ctx ν τ) (a b : Tm ν Φ) (A : τ) : Prop :=
  LambdaCase.Named.Eqv pureEff Γ (embedCase a) (embedCase b) A

theorem Eqv.embedCase [DecidableEq ν] [LambdaIter.TypeFormers τ]
    [LambdaIter.HasTy Φ τ] [LambdaIter.HasEff Φ ε]
    {pureEff : ε} {Γ : Ctx ν τ} {a b : Tm ν Φ} {A : τ} :
    Eqv pureEff Γ a b A → LambdaCase.Named.Eqv pureEff Γ (embedCase a) (embedCase b) A := id

end Named

namespace Subtyping.Named

def Eqv [DecidableEq ν] [LambdaIter.TypeFormers τ] [LambdaIter.Subtyping τ]
    [LambdaIter.HasTy Φ τ] [LambdaIter.HasEff Φ ε] (pureEff : ε)
    (Γ : Ctx ν τ) (a b : LambdaSeq.Named.Tm ν Φ) (A : τ) : Prop :=
  LambdaCase.Subtyping.Named.Eqv pureEff Γ
    (LambdaSeq.Named.embedCase a) (LambdaSeq.Named.embedCase b) A

end Subtyping.Named

namespace LocallyNameless

variable {τ : Type u} [LambdaIter.TypeFormers τ]
variable {ν : Type w} [DecidableEq ν]
variable {Φ : Type q} [LambdaIter.HasTy Φ τ]
variable {ε : Type r} [LambdaIter.HasEff Φ ε]

/-- The exact typed monadic theory generated by beta/eta and associativity for `let`. -/
inductive Equiv (pureEff : ε) (Γ : Ctx ν τ) :
    {n : Nat} → BoundCtx τ n → Tm ν Φ n → Tm ν Φ n → τ → Prop where
  | var (h : Γ.lookup x = some A) : Equiv pureEff Γ β (.fv x) (.fv x) A
  | bvar : Equiv pureEff Γ β (.bv i) (.bv i) (β.get i)
  | symm : Equiv pureEff Γ β a b A → Equiv pureEff Γ β b a A
  | trans : Equiv pureEff Γ β a b A → Equiv pureEff Γ β b c A → Equiv pureEff Γ β a c A
  | op (h : Equiv pureEff Γ β a a' (LambdaIter.instrSrc f)) :
      Equiv pureEff Γ β (.op f a) (.op f a') (LambdaIter.instrTrg f)
  | let₁ (ha : Equiv pureEff Γ β a a' A)
      (hb : Equiv pureEff Γ (.snoc β A) b b' B) :
      Equiv pureEff Γ β (.let₁ a b) (.let₁ a' b') B
  | letBeta (hp : Pure pureEff a) (ha : HasType Φ Γ β a A)
      (hb : HasType Φ Γ (.snoc β A) b B) :
      Equiv pureEff Γ β (.let₁ a b) (Tm.instantiate b a) B
  | letEta {n} {β : BoundCtx τ n} {a : Tm ν Φ n} (ha : HasType Φ Γ β a A) :
      Equiv pureEff Γ β (.let₁ a (.bv 0)) a A
  | bindOp {n} {β : BoundCtx τ n} {a : Tm ν Φ n} {c : Tm ν Φ (n + 1)}
      (ha : HasType Φ Γ β a (LambdaIter.instrSrc f))
      (hc : HasType Φ Γ (.snoc β (LambdaIter.instrTrg f)) c C) :
      Equiv pureEff Γ β (.let₁ (.op f a) c)
        (.let₁ a (.let₁ (.op f (.bv 0)) (Tm.underBinder c))) C
  | bindLet (ha : HasType Φ Γ β a A) (hb : HasType Φ Γ (.snoc β A) b B)
      (hc : HasType Φ Γ (.snoc β B) c C) :
      Equiv pureEff Γ β (.let₁ (.let₁ a b) c)
        (.let₁ a (.let₁ b (Tm.underBinder c))) C

def Equiv.embedCase {pureEff : ε} {Γ : Ctx ν τ} {n : Nat} {β : BoundCtx τ n}
    {a b : Tm ν Φ n} {A : τ} : Equiv pureEff Γ β a b A →
    LambdaCase.LocallyNameless.Equiv pureEff Γ β a.embedCase b.embedCase A
  | .var h => .var h
  | .bvar => .bvar
  | .symm h => .symm h.embedCase
  | .trans h k => .trans h.embedCase k.embedCase
  | .op h => .op h.embedCase
  | .let₁ ha hb => .let₁ ha.embedCase hb.embedCase
  | .letBeta hp ha hb => by
      simpa only [Tm.embedCase_instantiate] using
        LambdaCase.LocallyNameless.Equiv.letBeta hp.embedCase ha.embedCase hb.embedCase
  | .letEta ha => LambdaCase.LocallyNameless.Equiv.letEta (pureEff := pureEff) ha.embedCase
  | .bindOp ha hc => by
      simpa only [Tm.embedCase, Tm.embedCase_underBinder] using
        LambdaCase.LocallyNameless.Equiv.bindOp (pureEff := pureEff) ha.embedCase hc.embedCase
  | .bindLet ha hb hc => by
      simpa only [Tm.embedCase, Tm.embedCase_underBinder] using
        LambdaCase.LocallyNameless.Equiv.bindLet (pureEff := pureEff)
          ha.embedCase hb.embedCase hc.embedCase

end LocallyNameless

namespace Subtyping.LocallyNameless

variable {τ : Type u} [LambdaIter.TypeFormers τ] [LambdaIter.Subtyping τ]
variable {ν : Type w} [DecidableEq ν]
variable {Φ : Type q} [LambdaIter.HasTy Φ τ]
variable {ε : Type r} [LambdaIter.HasEff Φ ε]

/-- The coercive variant of the typed monadic theory. -/
inductive Equiv (pureEff : ε) (Γ : Ctx ν τ) : {n : Nat} →
    LambdaSeq.LocallyNameless.BoundCtx τ n → LambdaSeq.LocallyNameless.Tm ν Φ n →
    LambdaSeq.LocallyNameless.Tm ν Φ n → τ → Prop where
  | var (h : Γ.lookup x = some A) : Equiv pureEff Γ β (.fv x) (.fv x) A
  | bvar : Equiv pureEff Γ β (.bv i) (.bv i) (β.get i)
  | symm : Equiv pureEff Γ β a b A → Equiv pureEff Γ β b a A
  | trans : Equiv pureEff Γ β a b A → Equiv pureEff Γ β b c A → Equiv pureEff Γ β a c A
  | sub : Equiv pureEff Γ β a b A → LambdaIter.Subty A B → Equiv pureEff Γ β a b B
  | op (h : Equiv pureEff Γ β a a' (LambdaIter.instrSrc f)) :
      Equiv pureEff Γ β (.op f a) (.op f a') (LambdaIter.instrTrg f)
  | let₁ (ha : Equiv pureEff Γ β a a' A) (hb : Equiv pureEff Γ (.snoc β A) b b' B) :
      Equiv pureEff Γ β (.let₁ a b) (.let₁ a' b') B
  | letBeta (hp : LambdaSeq.LocallyNameless.Pure pureEff a)
      (ha : HasType Φ Γ β a A) (hb : HasType Φ Γ (.snoc β A) b B) :
      Equiv pureEff Γ β (.let₁ a b) (LambdaSeq.LocallyNameless.Tm.instantiate b a) B
  | letEta {n} {β : LambdaSeq.LocallyNameless.BoundCtx τ n}
      {a : LambdaSeq.LocallyNameless.Tm ν Φ n} (ha : HasType Φ Γ β a A) :
      Equiv pureEff Γ β (.let₁ a (.bv 0)) a A
  | bindOp {n} {β : LambdaSeq.LocallyNameless.BoundCtx τ n}
      {a : LambdaSeq.LocallyNameless.Tm ν Φ n}
      {c : LambdaSeq.LocallyNameless.Tm ν Φ (n + 1)}
      (ha : HasType Φ Γ β a (LambdaIter.instrSrc f))
      (hc : HasType Φ Γ (.snoc β (LambdaIter.instrTrg f)) c C) :
      Equiv pureEff Γ β (.let₁ (.op f a) c)
        (.let₁ a (.let₁ (.op f (.bv 0))
          (LambdaSeq.LocallyNameless.Tm.underBinder c))) C
  | bindLet (ha : HasType Φ Γ β a A) (hb : HasType Φ Γ (.snoc β A) b B)
      (hc : HasType Φ Γ (.snoc β B) c C) :
      Equiv pureEff Γ β (.let₁ (.let₁ a b) c)
        (.let₁ a (.let₁ b (LambdaSeq.LocallyNameless.Tm.underBinder c))) C

end Subtyping.LocallyNameless
end Isotope.LambdaSeq
